{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "screen-adapter",
    "version": "1.3.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "screen-adapter-1.3.7-SNAPSHOT.jar",
          "url": "screen-adapter-1.3.7-SNAPSHOT.jar",
          "size": 4227,
          "sha512": "feb9026e77ad091729eacc7dc909a5825e57f31a36fb9b1eed48d86d968df640cc3feb29aee5c46adf1b1f79b1b7dac369f926ce9da64ff7662abd31e95dbb78",
          "sha256": "07e86cf1e4a318cf18ccc502f537beea0715d313c0b440af65df4286024ff07c",
          "sha1": "c39549b906500b21979c3374e35ceebebdfa935f",
          "md5": "b6eac1df64f2cc32b11213545efeebcc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.33"
          }
        }
      ],
      "files": [
        {
          "name": "screen-adapter-1.3.7-SNAPSHOT.jar",
          "url": "screen-adapter-1.3.7-SNAPSHOT.jar",
          "size": 4227,
          "sha512": "feb9026e77ad091729eacc7dc909a5825e57f31a36fb9b1eed48d86d968df640cc3feb29aee5c46adf1b1f79b1b7dac369f926ce9da64ff7662abd31e95dbb78",
          "sha256": "07e86cf1e4a318cf18ccc502f537beea0715d313c0b440af65df4286024ff07c",
          "sha1": "c39549b906500b21979c3374e35ceebebdfa935f",
          "md5": "b6eac1df64f2cc32b11213545efeebcc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen-adapter-1.3.7-SNAPSHOT-sources.jar",
          "url": "screen-adapter-1.3.7-SNAPSHOT-sources.jar",
          "size": 2606,
          "sha512": "3d637a4bc6eb47003383dc3273dead394f200c80a21031451de2d2ffbe449fabf9b5f7b7b89e27ef3dff74922634476c5f27c8eb17e5a7e4461ad604f8440aaa",
          "sha256": "48687db46263fdbeae98faed6173c7407f323dd804776b3cc861ffd5daf57343",
          "sha1": "0744383a8962031120c01d9399c590a6e6e6dc7d",
          "md5": "46adcf20d90b53a2546ae6fc768398d0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen-adapter-1.3.7-SNAPSHOT-javadoc.jar",
          "url": "screen-adapter-1.3.7-SNAPSHOT-javadoc.jar",
          "size": 27925,
          "sha512": "0ab91399fa26c3c3c819ecde2087533d192a4d426cc6e195b73dd9fff3d5f29710a071fb6eca51e10e5db4fcfa72353d21416820aba14defadb57b2b7052592a",
          "sha256": "f29a97cce29321bc840ca1b6c18c30dde659911fce2b5394055d4caa406fa0c6",
          "sha1": "fc29ad8bf567484a0767b7113a6081de4713c88c",
          "md5": "b358e982806070f7b088e85214ed446e"
        }
      ]
    }
  ]
}
