{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.datagateways",
    "module": "datagateways",
    "version": "1.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "datagateways-1.0.24.jar",
          "url": "datagateways-1.0.24.jar",
          "size": 261,
          "sha512": "2ca0aa23ff121e7cacb9aa1d86e792bf32ab20d25ed114d5778235fc104a3c95cee00d8a6730032a28be5d0fe3412b57ed0caeedea9954d13c457634f4087648",
          "sha256": "f846e7aa30da3c02a3fb00c7d9e129e1a5cc82c3059f7e219f2656ef5fea2ffb",
          "sha1": "fd45859f6e04cc34ec9831f5352b687442ab493f",
          "md5": "088e27a23af126e1fe8a27e2652b84b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.24.jar",
          "url": "datagateways-1.0.24.jar",
          "size": 261,
          "sha512": "2ca0aa23ff121e7cacb9aa1d86e792bf32ab20d25ed114d5778235fc104a3c95cee00d8a6730032a28be5d0fe3412b57ed0caeedea9954d13c457634f4087648",
          "sha256": "f846e7aa30da3c02a3fb00c7d9e129e1a5cc82c3059f7e219f2656ef5fea2ffb",
          "sha1": "fd45859f6e04cc34ec9831f5352b687442ab493f",
          "md5": "088e27a23af126e1fe8a27e2652b84b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.24-sources.jar",
          "url": "datagateways-1.0.24-sources.jar",
          "size": 261,
          "sha512": "2ca0aa23ff121e7cacb9aa1d86e792bf32ab20d25ed114d5778235fc104a3c95cee00d8a6730032a28be5d0fe3412b57ed0caeedea9954d13c457634f4087648",
          "sha256": "f846e7aa30da3c02a3fb00c7d9e129e1a5cc82c3059f7e219f2656ef5fea2ffb",
          "sha1": "fd45859f6e04cc34ec9831f5352b687442ab493f",
          "md5": "088e27a23af126e1fe8a27e2652b84b0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.24-javadoc.jar",
          "url": "datagateways-1.0.24-javadoc.jar",
          "size": 261,
          "sha512": "2ca0aa23ff121e7cacb9aa1d86e792bf32ab20d25ed114d5778235fc104a3c95cee00d8a6730032a28be5d0fe3412b57ed0caeedea9954d13c457634f4087648",
          "sha256": "f846e7aa30da3c02a3fb00c7d9e129e1a5cc82c3059f7e219f2656ef5fea2ffb",
          "sha1": "fd45859f6e04cc34ec9831f5352b687442ab493f",
          "md5": "088e27a23af126e1fe8a27e2652b84b0"
        }
      ]
    }
  ]
}
