{
  "formatVersion": "1.1",
  "component": {
    "group": "io.libp2p",
    "module": "jvm-libp2p",
    "version": "1.2.2R.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-libp2p-1.2.2R.1-SNAPSHOT.jar",
          "url": "jvm-libp2p-1.2.2R.1-SNAPSHOT.jar",
          "size": 1725972,
          "sha512": "28824349801f2b0560e556d7301c365aa8689db153a087b4fb45e2df44f3294723908097e7578b616dd3df7aeea564d7efff1fccc6d3d39435b56fe5ec02247a",
          "sha256": "e0869fdeeefcde950beec5758358de0fd76b8b0e144e0de4e5e7ed79754ef894",
          "sha1": "0b816f0dfc7cd93db556673ec09ef81505214ba5",
          "md5": "2c75866b8e6bc86ef80214d427c2e779"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-codec-http",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-classes-epoll",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-x86_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-aarch_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-x86_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-aarch_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "windows-x86_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-x86_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-aarch_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-x86_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-aarch_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "windows-x86_64"
            }
          }
        },
        {
          "group": "com.github.multiformats",
          "module": "java-multibase",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "tech.pegasys",
          "module": "noise-java",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-libp2p-1.2.2R.1-SNAPSHOT.jar",
          "url": "jvm-libp2p-1.2.2R.1-SNAPSHOT.jar",
          "size": 1725972,
          "sha512": "28824349801f2b0560e556d7301c365aa8689db153a087b4fb45e2df44f3294723908097e7578b616dd3df7aeea564d7efff1fccc6d3d39435b56fe5ec02247a",
          "sha256": "e0869fdeeefcde950beec5758358de0fd76b8b0e144e0de4e5e7ed79754ef894",
          "sha1": "0b816f0dfc7cd93db556673ec09ef81505214ba5",
          "md5": "2c75866b8e6bc86ef80214d427c2e779"
        }
      ]
    }
  ]
}
