{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.controllers",
    "module": "caller",
    "version": "1.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "caller-1.0.36.jar",
          "url": "caller-1.0.36.jar",
          "size": 261,
          "sha512": "db947b0745d1f030370b1bbb7a0fd1e59dc1319a481fb3c779ebd6715be8ced5f7099399d82fe6597279ce1d721b6b95e76e0fdba633af7397417d6828c8fdb3",
          "sha256": "8efcf4f7564d3b28859f36343def0220905e59da221c5162c7e84f501df32911",
          "sha1": "f207f29801308f575624cdf71e851da3cd391c89",
          "md5": "27711ed1bd4969a98ef92d34fca93277"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.36"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "caller-1.0.36.jar",
          "url": "caller-1.0.36.jar",
          "size": 261,
          "sha512": "db947b0745d1f030370b1bbb7a0fd1e59dc1319a481fb3c779ebd6715be8ced5f7099399d82fe6597279ce1d721b6b95e76e0fdba633af7397417d6828c8fdb3",
          "sha256": "8efcf4f7564d3b28859f36343def0220905e59da221c5162c7e84f501df32911",
          "sha1": "f207f29801308f575624cdf71e851da3cd391c89",
          "md5": "27711ed1bd4969a98ef92d34fca93277"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caller-1.0.36-sources.jar",
          "url": "caller-1.0.36-sources.jar",
          "size": 261,
          "sha512": "db947b0745d1f030370b1bbb7a0fd1e59dc1319a481fb3c779ebd6715be8ced5f7099399d82fe6597279ce1d721b6b95e76e0fdba633af7397417d6828c8fdb3",
          "sha256": "8efcf4f7564d3b28859f36343def0220905e59da221c5162c7e84f501df32911",
          "sha1": "f207f29801308f575624cdf71e851da3cd391c89",
          "md5": "27711ed1bd4969a98ef92d34fca93277"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caller-1.0.36-javadoc.jar",
          "url": "caller-1.0.36-javadoc.jar",
          "size": 261,
          "sha512": "db947b0745d1f030370b1bbb7a0fd1e59dc1319a481fb3c779ebd6715be8ced5f7099399d82fe6597279ce1d721b6b95e76e0fdba633af7397417d6828c8fdb3",
          "sha256": "8efcf4f7564d3b28859f36343def0220905e59da221c5162c7e84f501df32911",
          "sha1": "f207f29801308f575624cdf71e851da3cd391c89",
          "md5": "27711ed1bd4969a98ef92d34fca93277"
        }
      ]
    }
  ]
}
