{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "config",
    "version": "1.3.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-1.3.2-SNAPSHOT.jar",
          "url": "config-1.3.2-SNAPSHOT.jar",
          "size": 8215,
          "sha512": "38e834281e03fe1e1e97fa0ba29d52c60838f98f8f2da944e6dd9a73837e34a7ee79c3582409725f5c33bd942fcee9284473d58fa300153f0b57f3faba7f9f7e",
          "sha256": "82049ac0a5a9a7299236cca377e6dfbdab3c6008d4592ad413fdac8e54f3a77a",
          "sha1": "617b6b74c3521b7e7640eb41f6764c8bc0ffed5f",
          "md5": "0b43b672ec8235a5bb36ee5f31621cb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.33"
          }
        }
      ],
      "files": [
        {
          "name": "config-1.3.2-SNAPSHOT.jar",
          "url": "config-1.3.2-SNAPSHOT.jar",
          "size": 8215,
          "sha512": "38e834281e03fe1e1e97fa0ba29d52c60838f98f8f2da944e6dd9a73837e34a7ee79c3582409725f5c33bd942fcee9284473d58fa300153f0b57f3faba7f9f7e",
          "sha256": "82049ac0a5a9a7299236cca377e6dfbdab3c6008d4592ad413fdac8e54f3a77a",
          "sha1": "617b6b74c3521b7e7640eb41f6764c8bc0ffed5f",
          "md5": "0b43b672ec8235a5bb36ee5f31621cb2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.2-SNAPSHOT-sources.jar",
          "url": "config-1.3.2-SNAPSHOT-sources.jar",
          "size": 4221,
          "sha512": "2ef483da3478de949959780ab326314485ab912948538aa6da861447b6190d0b73e84ccee5f28d2de8a83d1981261730a6b2aea1fd629c2dfe3e2ee38b233c73",
          "sha256": "24b50173dc1ce6a8620945bda4fdc449810f0cc1417e54ec28f6e32380f0d87b",
          "sha1": "17bb3b11b7e54bd125b9a8d432ed55f47774a9a7",
          "md5": "4a69a0d2c612ed640c5b4c7dfddd2b64"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.2-SNAPSHOT-javadoc.jar",
          "url": "config-1.3.2-SNAPSHOT-javadoc.jar",
          "size": 45716,
          "sha512": "62c080257811d27aec6e845514aa9352bd5a25921dd6dbbd0deb6a8baf2d32ea4fbffa915d4c552f6d4c299f721880d4e17f49eb64e21c31e5e47bfc7ff43e0d",
          "sha256": "25dd00324e808a2410a1666ecc00045274c99fa40092a280f37adc4026732840",
          "sha1": "4f5e3de33610198764306cf94547ff7c71c45024",
          "md5": "d5e5dc97a3f1f42aca72438571f67d85"
        }
      ]
    }
  ]
}
