{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "admin",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.15.jar",
          "url": "admin-1.0.15.jar",
          "size": 26661,
          "sha512": "4e67962c8ef679815be854a73ceba1a7f917248ed2bb26d3e9f154340b5a4153bbb0ff28ac284d39ff23fa4ecd7dfeca655e18e4bb48d16c5f2cb4416232decf",
          "sha256": "51f51c255357cfcdcbec2ab4f840c135794a2539de9e9883e0b9a4b7afcd3d38",
          "sha1": "684e35c7238bf0f7798bb12af27f8229d3e82b1f",
          "md5": "446427e49f27d7b8ad8ab956aff2e785"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.15"
          }
        }
      ],
      "files": [
        {
          "name": "admin-1.0.15.jar",
          "url": "admin-1.0.15.jar",
          "size": 26661,
          "sha512": "4e67962c8ef679815be854a73ceba1a7f917248ed2bb26d3e9f154340b5a4153bbb0ff28ac284d39ff23fa4ecd7dfeca655e18e4bb48d16c5f2cb4416232decf",
          "sha256": "51f51c255357cfcdcbec2ab4f840c135794a2539de9e9883e0b9a4b7afcd3d38",
          "sha1": "684e35c7238bf0f7798bb12af27f8229d3e82b1f",
          "md5": "446427e49f27d7b8ad8ab956aff2e785"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.15-sources.jar",
          "url": "admin-1.0.15-sources.jar",
          "size": 14095,
          "sha512": "9238b4a87b8c834a861976c45471fb3df82917a9cd298a7f5c1961c5083c978cb96f98effea4ef7c9dae6c81bd9237f0b0d285a324b2ab51ed851872bfb68063",
          "sha256": "625752af64110886d4378b75b075d0fc0ec91a0689d7e8a8af988b124c2cf13c",
          "sha1": "1303c1ad27faca2fcc7139eb163a390cef911f5b",
          "md5": "5ffa3a883149a4d2fd90b1191d1b27c9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.15-javadoc.jar",
          "url": "admin-1.0.15-javadoc.jar",
          "size": 175685,
          "sha512": "39e0071b5a2c4db673f169b3cc05aa626db1bdfaccefb0edbcd0aa7d4055cebb9c9c26a23c5df30225462e0ca6686111230c5a3332c894ac81c05d598cbd37bf",
          "sha256": "8d7d8821a44f129ed51172abd0d3ef3d578bb7097049e9b15a06f1782dff4e9e",
          "sha1": "88d869f72ae19a25b2a862467e57ece12ba3e886",
          "md5": "2119a476635fdc9e9e3ec41fa67c143b"
        }
      ]
    }
  ]
}
