{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "admin",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.15.jar",
          "url": "admin-1.0.15.jar",
          "size": 26488,
          "sha512": "58b26e0312bdd19b44107c1d1deab98a836b72a2fd0f76e16b3b5e48c43b4e24f40e66317e818e6b2fd0a2fb17ffa809e9d1b179412b945b83dabd02c73f67eb",
          "sha256": "ec7121f723a70839a5397e169b33d76c29dbf31fefd11d43f7aa699dc71f0886",
          "sha1": "6eeb3f20b0b66f0406cbd24047e6eb6a6b2f0ea6",
          "md5": "cea6dfa7b30482385ee2f4cdbd2d9bea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.15"
          }
        }
      ],
      "files": [
        {
          "name": "admin-1.0.15.jar",
          "url": "admin-1.0.15.jar",
          "size": 26488,
          "sha512": "58b26e0312bdd19b44107c1d1deab98a836b72a2fd0f76e16b3b5e48c43b4e24f40e66317e818e6b2fd0a2fb17ffa809e9d1b179412b945b83dabd02c73f67eb",
          "sha256": "ec7121f723a70839a5397e169b33d76c29dbf31fefd11d43f7aa699dc71f0886",
          "sha1": "6eeb3f20b0b66f0406cbd24047e6eb6a6b2f0ea6",
          "md5": "cea6dfa7b30482385ee2f4cdbd2d9bea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.15-sources.jar",
          "url": "admin-1.0.15-sources.jar",
          "size": 14095,
          "sha512": "9238b4a87b8c834a861976c45471fb3df82917a9cd298a7f5c1961c5083c978cb96f98effea4ef7c9dae6c81bd9237f0b0d285a324b2ab51ed851872bfb68063",
          "sha256": "625752af64110886d4378b75b075d0fc0ec91a0689d7e8a8af988b124c2cf13c",
          "sha1": "1303c1ad27faca2fcc7139eb163a390cef911f5b",
          "md5": "5ffa3a883149a4d2fd90b1191d1b27c9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.15-javadoc.jar",
          "url": "admin-1.0.15-javadoc.jar",
          "size": 124450,
          "sha512": "d2a1aa3093adf65370f03962da203321f56a74e8e623acb8ec8145a6f986e95f81e3ee5f65a610e81798ad178fc33409446c25a189d53b6140826f0546d7579c",
          "sha256": "747810b2c0068356b873394169bca3c2b5c3ff28b962e15076a12f097ea2f128",
          "sha1": "254753d1bac571d563d6291813578ea81acbeb51",
          "md5": "24974b527d6718c574a7cfb3b85932ed"
        }
      ]
    }
  ]
}
