{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.elenterius.fabiko",
    "module": "visualisation",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.elenterius.fabiko",
          "module": "core",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bom",
          "version": {
            "requires": "3.3.5"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        }
      ],
      "files": [
        {
          "name": "visualisation-0.0.1.jar",
          "url": "visualisation-0.0.1.jar",
          "size": 37889,
          "sha512": "7383d7d89e14198b781223fa36a0738a2d63c5f021158bbdfcc68a27008287994105b0d85e3610fcfbc3bc241aeb46accb3a14ce4ec80a55c83fb81b8c968f3d",
          "sha256": "0e2d163f8b6b7b06454455dbf40b8653edba7c5b5fc8f50a5dbac805a5ff7f05",
          "sha1": "ec559200329dcf5207a2c4fce57eac901d69c053",
          "md5": "4d3de48c26517854359352df1333d27e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.elenterius.fabiko",
          "module": "core",
          "version": {
            "requires": "0.0.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bom",
          "version": {
            "requires": "3.3.5"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        }
      ],
      "files": [
        {
          "name": "visualisation-0.0.1.jar",
          "url": "visualisation-0.0.1.jar",
          "size": 37889,
          "sha512": "7383d7d89e14198b781223fa36a0738a2d63c5f021158bbdfcc68a27008287994105b0d85e3610fcfbc3bc241aeb46accb3a14ce4ec80a55c83fb81b8c968f3d",
          "sha256": "0e2d163f8b6b7b06454455dbf40b8653edba7c5b5fc8f50a5dbac805a5ff7f05",
          "sha1": "ec559200329dcf5207a2c4fce57eac901d69c053",
          "md5": "4d3de48c26517854359352df1333d27e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "visualisation-0.0.1-sources.jar",
          "url": "visualisation-0.0.1-sources.jar",
          "size": 42173,
          "sha512": "4ae48aea6c829615f5530d798e5f4805813cd7cfb51a0a9aa013290454d81cc34a34dbb3940b081ea5e1710ff3231f48f45d0aa65a5304f6d726faad89ba5554",
          "sha256": "b1ce1e7c7b3d469d9fc1782e463812d68f3edc0c9cfe6bde3a8e29aca381b0ce",
          "sha1": "eb17e620e4f2c15fc0f100964335d4e9cb2176a5",
          "md5": "34f5c520c1079d68f00dc0e28ee02131"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "visualisation-0.0.1-javadoc.jar",
          "url": "visualisation-0.0.1-javadoc.jar",
          "size": 124096,
          "sha512": "25b3d70a3fb9f69b01e84e053cb062b2b67a466337542e36191057b3c51b8c54fa45b79a9617a45a20ae71e25b8fa9e5669cd7d54dabe5fcb7a7bc5ce3fac843",
          "sha256": "f09b628647702b8a3c02a219d5d5d9826c58f69be3cef29b15706b77adf93491",
          "sha1": "990db67ce9258c1270b72ae932ffeff975a1e6c6",
          "md5": "08167113e4847e43554f5a868b3dfd64"
        }
      ]
    }
  ]
}
