{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.controllers",
    "module": "admin",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.17.jar",
          "url": "admin-1.0.17.jar",
          "size": 5215,
          "sha512": "e10b45a96eaed470f0857df40ef846873aae116bc4dbb6bbe78cf94dfb3bbea76b7d808569fb000aba8fbd1fc75300b408da2098caf5bd41d5dcdd8185c4726b",
          "sha256": "119d9a8bbe3bf9e150a96fd63facb4b230ff59871592ff0baaafe13d96ea40f5",
          "sha1": "26407066a4c36456465d9929ef430491b66f7a2d",
          "md5": "19b127519b1a432ce845749d4c56af9d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.17"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "admin-1.0.17.jar",
          "url": "admin-1.0.17.jar",
          "size": 5215,
          "sha512": "e10b45a96eaed470f0857df40ef846873aae116bc4dbb6bbe78cf94dfb3bbea76b7d808569fb000aba8fbd1fc75300b408da2098caf5bd41d5dcdd8185c4726b",
          "sha256": "119d9a8bbe3bf9e150a96fd63facb4b230ff59871592ff0baaafe13d96ea40f5",
          "sha1": "26407066a4c36456465d9929ef430491b66f7a2d",
          "md5": "19b127519b1a432ce845749d4c56af9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.17-sources.jar",
          "url": "admin-1.0.17-sources.jar",
          "size": 3383,
          "sha512": "3efbc95a1be393cee1da710dfa636507e5ebe3cdb4cc621aeac8a66cb66b86c855131460dbebc049cb7e6dfb4d3f712f25299e37da1a56fa26d60b34b661b64e",
          "sha256": "1a2f02a4a3ae6b3ad09cc892cea67d3ace22442704ad7b1f950b6295741ea3b9",
          "sha1": "8c1ca9980ff6d669be6826610df35e749decf376",
          "md5": "9269278190137fc1bd23e8e410acc3f8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.17-javadoc.jar",
          "url": "admin-1.0.17-javadoc.jar",
          "size": 26424,
          "sha512": "a927d8f76519658a3869574dbf228fbe1ba93a1e90eaee32c3b81f41ea96cb9fba9b0d615f47ee5d2242ad31643c843d02b26608ab39ba4e019e9e8a74660a8f",
          "sha256": "feb08c22e4ef96b0c9f75e4b6640c9876e55c845838ea02c3bc289147fb9cf32",
          "sha1": "47bd5d916b130068b4a24646eae3b04f6fd1d0fa",
          "md5": "48d9fed264e34fa3da537ea899f1f525"
        }
      ]
    }
  ]
}
