{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.datagateways",
    "module": "datagateways",
    "version": "1.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "datagateways-1.0.36.jar",
          "url": "datagateways-1.0.36.jar",
          "size": 261,
          "sha512": "0814d579355cdb4e71971632787a2747fc01c8c5ee82f67ec5779be2548db9f973eae7e1fc8f16161dad855fc18fad942aaa613e552f752511bf89194684a38b",
          "sha256": "ebe6cc75b9c8dfaf4068edb88afe1d3a6403c2254621df3db8dcebeba4ada5c2",
          "sha1": "6939b83cbc8d36b52d27e9589352bbdd8fb948be",
          "md5": "56f33f783fd0b152142347eab73caefd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.36.jar",
          "url": "datagateways-1.0.36.jar",
          "size": 261,
          "sha512": "0814d579355cdb4e71971632787a2747fc01c8c5ee82f67ec5779be2548db9f973eae7e1fc8f16161dad855fc18fad942aaa613e552f752511bf89194684a38b",
          "sha256": "ebe6cc75b9c8dfaf4068edb88afe1d3a6403c2254621df3db8dcebeba4ada5c2",
          "sha1": "6939b83cbc8d36b52d27e9589352bbdd8fb948be",
          "md5": "56f33f783fd0b152142347eab73caefd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.36-sources.jar",
          "url": "datagateways-1.0.36-sources.jar",
          "size": 261,
          "sha512": "0814d579355cdb4e71971632787a2747fc01c8c5ee82f67ec5779be2548db9f973eae7e1fc8f16161dad855fc18fad942aaa613e552f752511bf89194684a38b",
          "sha256": "ebe6cc75b9c8dfaf4068edb88afe1d3a6403c2254621df3db8dcebeba4ada5c2",
          "sha1": "6939b83cbc8d36b52d27e9589352bbdd8fb948be",
          "md5": "56f33f783fd0b152142347eab73caefd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.36-javadoc.jar",
          "url": "datagateways-1.0.36-javadoc.jar",
          "size": 261,
          "sha512": "0814d579355cdb4e71971632787a2747fc01c8c5ee82f67ec5779be2548db9f973eae7e1fc8f16161dad855fc18fad942aaa613e552f752511bf89194684a38b",
          "sha256": "ebe6cc75b9c8dfaf4068edb88afe1d3a6403c2254621df3db8dcebeba4ada5c2",
          "sha1": "6939b83cbc8d36b52d27e9589352bbdd8fb948be",
          "md5": "56f33f783fd0b152142347eab73caefd"
        }
      ]
    }
  ]
}
