{
  "formatVersion": "1.1",
  "component": {
    "group": "io.libp2p",
    "module": "jvm-libp2p",
    "version": "1.2.4R-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-libp2p-1.2.4R-SNAPSHOT.jar",
          "url": "jvm-libp2p-1.2.4R-SNAPSHOT.jar",
          "size": 1726162,
          "sha512": "cb6ec008ac70a2335679846a8d4c6e6b18614b8c6b380632bb4aa552a27fce74d53c029a89bd96cf085ecc64433dd53bb32140ef6717ef1c357c26a980ae666e",
          "sha256": "c01e102c78a847db6dc1a9e643b268f53373403c2a0ac927c511c674c67b0e77",
          "sha1": "6432e63f3399551be14ec52daaaf8fb7c61c59ed",
          "md5": "af019c171385b323be826c9629996a85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-codec-http",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-classes-epoll",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-x86_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-aarch_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-x86_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-aarch_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "windows-x86_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-x86_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-aarch_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-x86_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-aarch_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "windows-x86_64"
            }
          }
        },
        {
          "group": "com.github.multiformats",
          "module": "java-multibase",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "tech.pegasys",
          "module": "noise-java",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-libp2p-1.2.4R-SNAPSHOT.jar",
          "url": "jvm-libp2p-1.2.4R-SNAPSHOT.jar",
          "size": 1726162,
          "sha512": "cb6ec008ac70a2335679846a8d4c6e6b18614b8c6b380632bb4aa552a27fce74d53c029a89bd96cf085ecc64433dd53bb32140ef6717ef1c357c26a980ae666e",
          "sha256": "c01e102c78a847db6dc1a9e643b268f53373403c2a0ac927c511c674c67b0e77",
          "sha1": "6432e63f3399551be14ec52daaaf8fb7c61c59ed",
          "md5": "af019c171385b323be826c9629996a85"
        }
      ]
    }
  ]
}
