{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "policy-impl",
    "version": "1.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "policy-impl-1.3.1-SNAPSHOT.jar",
          "url": "policy-impl-1.3.1-SNAPSHOT.jar",
          "size": 48627,
          "sha512": "6379bca862e7f7bb6aa148a887f2cc76c7984724bf67bcbc20bcc47028fcb67b1142cd5b1b2b4552ebcffb36765ba19b78db6304dea2d5c4a29a4bfed68a047a",
          "sha256": "83833ad7cdadb20daca46e1dd58d06b28ed4c0fef71de7fc79ab3c8595a800f2",
          "sha1": "808787478f0f6a12cdc7bcb082371a75840a1ddf",
          "md5": "496272fa9e535fdd91dcbb98bae0ef37"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "policy-impl-1.3.1-SNAPSHOT.jar",
          "url": "policy-impl-1.3.1-SNAPSHOT.jar",
          "size": 48627,
          "sha512": "6379bca862e7f7bb6aa148a887f2cc76c7984724bf67bcbc20bcc47028fcb67b1142cd5b1b2b4552ebcffb36765ba19b78db6304dea2d5c4a29a4bfed68a047a",
          "sha256": "83833ad7cdadb20daca46e1dd58d06b28ed4c0fef71de7fc79ab3c8595a800f2",
          "sha1": "808787478f0f6a12cdc7bcb082371a75840a1ddf",
          "md5": "496272fa9e535fdd91dcbb98bae0ef37"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "policy-impl-1.3.1-SNAPSHOT-sources.jar",
          "url": "policy-impl-1.3.1-SNAPSHOT-sources.jar",
          "size": 22750,
          "sha512": "0b893f2df17b7cfa313ebfe76739c33fe87e6443526d8a320aabe77bcf8f2c3f10e160fc1a1b5ccdca486180613ffcd7ddfe52e3f36a79ef8847049423b6c6dd",
          "sha256": "70bbdfb29db0947f5b1052fab6a8c3625d08441d4e88038ad28f41eaec290468",
          "sha1": "3e8389f76d6aabb8d2141ab68ed205dc144248ff",
          "md5": "ff02de78d47417ac389128a418452ff4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "policy-impl-1.3.1-SNAPSHOT-javadoc.jar",
          "url": "policy-impl-1.3.1-SNAPSHOT-javadoc.jar",
          "size": 188819,
          "sha512": "d3b2d26dd9342c63cb363aa695113d3487f54133b1b81d7ed2b2ddb96bed08021eb43a44850a204fba827adfe3da6fa01b017e09f359cf5c47e50ceb51c7d65e",
          "sha256": "6e903f4acb445d98e5412a1aff6b98a9e083884dbd3f570b76643fa670849f8c",
          "sha1": "4f5ba8794c2d30a62dc434e2c0ec3893c9a4c18f",
          "md5": "45dd9c33af6c5e6e5ccba98bf5648776"
        }
      ]
    }
  ]
}
