{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "caller",
    "version": "1.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "caller-1.0.36.jar",
          "url": "caller-1.0.36.jar",
          "size": 9367,
          "sha512": "1e4ab7efcea806e7387c5d909b4a23b1f0a7dd7d17fa8d409801cb03e7850a1ab78027fa09f1f724782d13cf4a0d0317f7f9f26d7a335416ca28e77d2eea6c8f",
          "sha256": "1d9a833a5c8d53d9dccbfa14c991d712439bd5d2d331474fbfb6d5adbf7301fd",
          "sha1": "5c1f796ad0d503da4775868624df15e78eb2461c",
          "md5": "8c8f36073ed62509ceeb9094c631bd5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caller-1.0.36.jar",
          "url": "caller-1.0.36.jar",
          "size": 9367,
          "sha512": "1e4ab7efcea806e7387c5d909b4a23b1f0a7dd7d17fa8d409801cb03e7850a1ab78027fa09f1f724782d13cf4a0d0317f7f9f26d7a335416ca28e77d2eea6c8f",
          "sha256": "1d9a833a5c8d53d9dccbfa14c991d712439bd5d2d331474fbfb6d5adbf7301fd",
          "sha1": "5c1f796ad0d503da4775868624df15e78eb2461c",
          "md5": "8c8f36073ed62509ceeb9094c631bd5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caller-1.0.36-sources.jar",
          "url": "caller-1.0.36-sources.jar",
          "size": 5615,
          "sha512": "db8c587df268590bad7c4b9f17dfc3532b65648b1c6b4990397aab5a482f85b512fd2df003c8f331f308d1c7d10266f524077efc7d0268e5e564192523ea73bc",
          "sha256": "02f5b8149f2b56df05a9b843c92c1976d5bda2daf51d1d9d8a3d18486e579a3a",
          "sha1": "d5c67d70ae46e0818a210b31cc77bfcd703f6fc5",
          "md5": "532467a205df8aa59c63df23a3bbf389"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caller-1.0.36-javadoc.jar",
          "url": "caller-1.0.36-javadoc.jar",
          "size": 61423,
          "sha512": "c5624ff39e1f71ec8ef9f6d548346365d5bdd60da7514d84d1fb1ef95a6177594d84dbf8c62fe84e106a0580005eee1d56960186d0b92d3bcc94b1afd62b1837",
          "sha256": "30ad6119da6f7be9530dbcc326c2b91076977a6cbb1b3a0c278918eaaf2c9539",
          "sha1": "7093818c73a839e3905703d63415940da35259aa",
          "md5": "19baa9757f7c20c8e87e5b245128282b"
        }
      ]
    }
  ]
}
