{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "callee",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callee-1.0.17.jar",
          "url": "callee-1.0.17.jar",
          "size": 11356,
          "sha512": "8bf5eacf87b70a6b84476cdfbc37c57d8955da0c397f401dc04c0fccd358f7661cfd35b2a6ee120021bdac49350fe3007e993cf8b9ba46594c2c15719955d458",
          "sha256": "e284333a173ed60bd95a7501980dd789dd760d8d9c7e80836d96303cc527292f",
          "sha1": "7525f71ce7036015aa8f355a4e3eec3ef06d7c55",
          "md5": "fae5aca317ae7c469a39e8e5e9e88371"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "callee-1.0.17.jar",
          "url": "callee-1.0.17.jar",
          "size": 11356,
          "sha512": "8bf5eacf87b70a6b84476cdfbc37c57d8955da0c397f401dc04c0fccd358f7661cfd35b2a6ee120021bdac49350fe3007e993cf8b9ba46594c2c15719955d458",
          "sha256": "e284333a173ed60bd95a7501980dd789dd760d8d9c7e80836d96303cc527292f",
          "sha1": "7525f71ce7036015aa8f355a4e3eec3ef06d7c55",
          "md5": "fae5aca317ae7c469a39e8e5e9e88371"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.17-sources.jar",
          "url": "callee-1.0.17-sources.jar",
          "size": 8006,
          "sha512": "774b56e01954288829dd5ed8aed636d35f79d1cb8baf8bfbdfdd2ec06b2ab266adff9ad47621a2438f605317cc2c012e15b5303c5ae1f1caa594511ae8d33ba9",
          "sha256": "8bd098b7621cbda1c747cfbca681467fd6966bddd05a3839b62403cbc7f548fd",
          "sha1": "ef041577f3f1d77709b0a1e1d5fd7334c9a28cf7",
          "md5": "33de86293b0dab919febcccd743f966e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.17-javadoc.jar",
          "url": "callee-1.0.17-javadoc.jar",
          "size": 81886,
          "sha512": "7951cc41e9344d019e833e3463860ab558c90218abd97a455f5b834f9bf7351ed9ab71c1adf369399c11a9b743bfaae65b521dea23c194caeef03bef2153b8c7",
          "sha256": "ff395e91b92055b2c44e744da16f2377f312ca7bba60e2fdae11ee00e997d90b",
          "sha1": "2b4276cba9d078895165e4ee2e21ef83e374fa98",
          "md5": "8f5b63a0c32ec9e8ccbbe703382c903d"
        }
      ]
    }
  ]
}
