{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "callee",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callee-1.0.17.jar",
          "url": "callee-1.0.17.jar",
          "size": 11373,
          "sha512": "d865d095e2d1f48b77a035accb51bb22cef75850c0a7d68496e3daffc207928c6909193accbeb6eaaefdd8f6084330c1220038b335a86fd7dfe9996b08fded66",
          "sha256": "84b03aad7a5c3d2ecde987d28837a093c25c4acdfe122adf9b7b5fb327ab668c",
          "sha1": "bb9bad9978df656c4740607ac65496df95e67209",
          "md5": "bb9cae7f01214998162eb85ab7142e47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "callee-1.0.17.jar",
          "url": "callee-1.0.17.jar",
          "size": 11373,
          "sha512": "d865d095e2d1f48b77a035accb51bb22cef75850c0a7d68496e3daffc207928c6909193accbeb6eaaefdd8f6084330c1220038b335a86fd7dfe9996b08fded66",
          "sha256": "84b03aad7a5c3d2ecde987d28837a093c25c4acdfe122adf9b7b5fb327ab668c",
          "sha1": "bb9bad9978df656c4740607ac65496df95e67209",
          "md5": "bb9cae7f01214998162eb85ab7142e47"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.17-sources.jar",
          "url": "callee-1.0.17-sources.jar",
          "size": 7995,
          "sha512": "a012c90fae7d554acd8847ba88b9627b8c38f1e0109cfc766ad6383f55b16207f8a9a566a54f91ad8f518123bf503ab6f0b71fe8dc8ba462ccd45f838ab8e134",
          "sha256": "2407d603dc13addf8d352cd7f349be22280bcc9272d3eedcb6ea858973860855",
          "sha1": "f982f871631f03f9aa4ce43aa2418d3bb7fe07e1",
          "md5": "240f5dc011da29b871157c401496948f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.17-javadoc.jar",
          "url": "callee-1.0.17-javadoc.jar",
          "size": 81870,
          "sha512": "6f8d67ffbd64dd8c5b5ec4a7c7af72c47537d05b351317d711d188a718a8cb12aadef6f0820de588185d4416add3e90a61e92faf14d6d6f8e6dde4ab0a9843e0",
          "sha256": "08de442f1107183d2edf2d74c7fbfbfad458a05f3869c2576fd643a494379071",
          "sha1": "631faf11314b9c3102592d1230b0e9982c5f423e",
          "md5": "4ece0ff236d43a1ab25854143e667d19"
        }
      ]
    }
  ]
}
