{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "admin",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.17.jar",
          "url": "admin-1.0.17.jar",
          "size": 26438,
          "sha512": "8aa136189e936e26f6287ac582261532a8c6db762421c466167cc021cc2ca2d49084b9d16363434298ed8e0251a89c8f66f073eb5d82d3578aeebab329cfd32c",
          "sha256": "b1af1794b978d45adc4b54cd770ddcae3438f7c93e523b3357ef1fb840944314",
          "sha1": "41052f77f28867bff0f3485465eff5832cab5f04",
          "md5": "944bf300a5546bccda9fe57e82bcf603"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "admin-1.0.17.jar",
          "url": "admin-1.0.17.jar",
          "size": 26438,
          "sha512": "8aa136189e936e26f6287ac582261532a8c6db762421c466167cc021cc2ca2d49084b9d16363434298ed8e0251a89c8f66f073eb5d82d3578aeebab329cfd32c",
          "sha256": "b1af1794b978d45adc4b54cd770ddcae3438f7c93e523b3357ef1fb840944314",
          "sha1": "41052f77f28867bff0f3485465eff5832cab5f04",
          "md5": "944bf300a5546bccda9fe57e82bcf603"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.17-sources.jar",
          "url": "admin-1.0.17-sources.jar",
          "size": 14253,
          "sha512": "4fbecd56c4532872c4ae656fad41662de87c4d8cb78273f2acc5e788e8a9f926e2abb898c44f17f0abdce1b21c3a2b6f7c4668cf4bc54bfa3fe879a67cf7088a",
          "sha256": "9804bc27f647be0e6156980170814066fdaf0a4cdf61e5a6588e879486b587c1",
          "sha1": "75fab91beed7157603438165f9908945cbf5ba1f",
          "md5": "d8cf70a4f31ea474f10c69b69e591826"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.17-javadoc.jar",
          "url": "admin-1.0.17-javadoc.jar",
          "size": 124729,
          "sha512": "7aa8d9b25e3568afa42b4b0b6f5edbde51cf955b6dab57767608a95149abe861beb52978bf189bf55bbaa44ce06f9c4569d2a3066269e23baafcb6d31b8715ae",
          "sha256": "bb8a85d6de0e980a34edd2599099e72224bfa485c00b016f868fe20510c42727",
          "sha1": "b5f5fc83b9583deed04c6157be05a6385daedb0c",
          "md5": "07ee91be811bca9af9d7895d6c5dd280"
        }
      ]
    }
  ]
}
