{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr",
    "module": "MediaLibV4",
    "version": "1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MediaLibV4-1.1.0-SNAPSHOT.jar",
          "url": "MediaLibV4-1.1.0-SNAPSHOT.jar",
          "size": 733091,
          "sha512": "3a498fadf50c80f2b8102f681553528be953d3d3dfd8b4043e19f27515265f2e7a25515e0b2e612f262825444ecd8299c9c3dc45dcda070a384f344c9da7aa08",
          "sha256": "a6bde830d9c772162b39bfb1c20555b46b5258a553fb909eea55a7380c46bbb1",
          "sha1": "438cf08997eb408ce23bd3113743e1b919328952",
          "md5": "68e1017eb89cdefcabd4faa58bf3168a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.lwjgl.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.lwjgl.lwjgl",
          "module": "lwjgl_util",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "MediaLibV4-1.1.0-SNAPSHOT.jar",
          "url": "MediaLibV4-1.1.0-SNAPSHOT.jar",
          "size": 733091,
          "sha512": "3a498fadf50c80f2b8102f681553528be953d3d3dfd8b4043e19f27515265f2e7a25515e0b2e612f262825444ecd8299c9c3dc45dcda070a384f344c9da7aa08",
          "sha256": "a6bde830d9c772162b39bfb1c20555b46b5258a553fb909eea55a7380c46bbb1",
          "sha1": "438cf08997eb408ce23bd3113743e1b919328952",
          "md5": "68e1017eb89cdefcabd4faa58bf3168a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MediaLibV4-1.1.0-SNAPSHOT-sources.jar",
          "url": "MediaLibV4-1.1.0-SNAPSHOT-sources.jar",
          "size": 349726,
          "sha512": "2b435c158ee917433b9ea42056b5c08734a24bf0689e677d1eee58b09872fb1decccfa224d88e955c126a7506bf1bd2b7e217a374549a4e5e32aa80b259c1fd5",
          "sha256": "69b2a054e9a6e4412f5df0c82b5fa656bc930ec489ccc1059a35f4384b9e345f",
          "sha1": "bf18a64541725cea469fd13934bb0b13a174b746",
          "md5": "410095afe2f54a7b2b503d96ab178d8e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MediaLibV4-1.1.0-SNAPSHOT-javadoc.jar",
          "url": "MediaLibV4-1.1.0-SNAPSHOT-javadoc.jar",
          "size": 1107932,
          "sha512": "bc41607f29aa62648c06e7b2fb7e8cc8296f8ddc439550565960383e8473c7594b117f35380b77bc7b775840f278bac0ee9e263d6b07e6b7fa78c4a1340afa4d",
          "sha256": "a61a66213a0904b42567c02ca3846d11af189cc861de4c2f81b427236e07c55a",
          "sha1": "35d8ffa672680759d10d8346e97888b4d23e932f",
          "md5": "cf8ca82d42d7f8757f5f73b0547b0d35"
        }
      ]
    }
  ]
}
