{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "callee",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callee-1.0.15.jar",
          "url": "callee-1.0.15.jar",
          "size": 11378,
          "sha512": "9522fc082a8b8df82c6805a2ac672cabe0e0994b1e33fa193dfea53d59cf442824b2976138a22a848644d321879369f4dc8743cd2d7a2c1b655564a899dba563",
          "sha256": "b4d7b01622569392c5ab6e35e7cef8130e21217ace7fe060e283a4bcbe30654c",
          "sha1": "790916a4095dd22b73b29da183ce555c565ff3ff",
          "md5": "ebc8d113df72e5a8bcb6a4ade6e46573"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.15"
          }
        }
      ],
      "files": [
        {
          "name": "callee-1.0.15.jar",
          "url": "callee-1.0.15.jar",
          "size": 11378,
          "sha512": "9522fc082a8b8df82c6805a2ac672cabe0e0994b1e33fa193dfea53d59cf442824b2976138a22a848644d321879369f4dc8743cd2d7a2c1b655564a899dba563",
          "sha256": "b4d7b01622569392c5ab6e35e7cef8130e21217ace7fe060e283a4bcbe30654c",
          "sha1": "790916a4095dd22b73b29da183ce555c565ff3ff",
          "md5": "ebc8d113df72e5a8bcb6a4ade6e46573"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.15-sources.jar",
          "url": "callee-1.0.15-sources.jar",
          "size": 7961,
          "sha512": "3f67596d9be53385fc86ba2d942b68561a3cb56150edb954c60ffc83b0c69462b6c279d37adf9e0621ed1f739ef5d535847dbe33d58a5bbd2a88b3736a6d4cde",
          "sha256": "ea6b3287b7337d41f7d6946e6ffae243f3ac4abbb39123feba1d097e6261ae3a",
          "sha1": "d521536793b31d3c0525a8d5edb85d30538577b8",
          "md5": "010bb2718d0bc15278f9a878e325aa2f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.15-javadoc.jar",
          "url": "callee-1.0.15-javadoc.jar",
          "size": 81772,
          "sha512": "e1083b5ceee9658453c03a14169dfe57ecd07059c1636a44a15f8a76a3fbdbb6064bb80098859231d49888b2de3c76150c82b9c0e02780bbfc3df274ac5e55d7",
          "sha256": "e2b5c2aa46b66f70cd8d22576c12d14d7d6b55c2768704ff6a5294190837dc10",
          "sha1": "90ada2e521e0541a7132889bbf660d71c318e91b",
          "md5": "2c9ce5008e1e8ded415e9628f555072d"
        }
      ]
    }
  ]
}
