{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "callee",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callee-1.0.15.jar",
          "url": "callee-1.0.15.jar",
          "size": 11488,
          "sha512": "d9fdb452ac984419ae361386e27e63671b0090625cd6ec5c80147eae1fd24b100b8bfdf754c9db90a8034e2168c4c66369f991d124a41fff78368795ca586ce0",
          "sha256": "54698f7276752cd3035b6f871b1c79dbde68dbef9f21f69f5d63d13d712a65d1",
          "sha1": "592fd322998c434030efd782af79c9c3f50cc028",
          "md5": "6ae0a65842a40a5be9766c840dfb2b6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.15"
          }
        }
      ],
      "files": [
        {
          "name": "callee-1.0.15.jar",
          "url": "callee-1.0.15.jar",
          "size": 11488,
          "sha512": "d9fdb452ac984419ae361386e27e63671b0090625cd6ec5c80147eae1fd24b100b8bfdf754c9db90a8034e2168c4c66369f991d124a41fff78368795ca586ce0",
          "sha256": "54698f7276752cd3035b6f871b1c79dbde68dbef9f21f69f5d63d13d712a65d1",
          "sha1": "592fd322998c434030efd782af79c9c3f50cc028",
          "md5": "6ae0a65842a40a5be9766c840dfb2b6b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.15-sources.jar",
          "url": "callee-1.0.15-sources.jar",
          "size": 7961,
          "sha512": "3f67596d9be53385fc86ba2d942b68561a3cb56150edb954c60ffc83b0c69462b6c279d37adf9e0621ed1f739ef5d535847dbe33d58a5bbd2a88b3736a6d4cde",
          "sha256": "ea6b3287b7337d41f7d6946e6ffae243f3ac4abbb39123feba1d097e6261ae3a",
          "sha1": "d521536793b31d3c0525a8d5edb85d30538577b8",
          "md5": "010bb2718d0bc15278f9a878e325aa2f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.15-javadoc.jar",
          "url": "callee-1.0.15-javadoc.jar",
          "size": 130827,
          "sha512": "e56214760bfd3f77d688feabfcedc3d90990791bd65c491cabab157b66a069ad7881b69d15ff77596e48c6160528c0ac198c98c86aaac8eeb308154e52b805db",
          "sha256": "92493985e3d4cdec222a90b64d32d58b6dcfb23966c6406e10a211ac224ee8a6",
          "sha1": "d6f91a85be57ae31588f501119edf5ed679e3249",
          "md5": "c4cbaea518c7218cfa9fba0f7e94ed40"
        }
      ]
    }
  ]
}
