{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.controllers",
    "module": "admin",
    "version": "1.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.36.jar",
          "url": "admin-1.0.36.jar",
          "size": 4095,
          "sha512": "60e79abe70077b692b5aaa3b15d0e0dfda8eefa399d3882f6d9b87060fce0a5045023910a9ca0659233cd41d6ec60ad546b9474995dd4f305ccf8d4717589075",
          "sha256": "bfa620b302e75d8fe2612690aee6235000afb55630ba85f1112921c674ef19bc",
          "sha1": "82dec3a490066e0271ceab844c4811aaa84bbeab",
          "md5": "aaffd3fdfa7b6b580243c53f4f35de31"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.36"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "admin-1.0.36.jar",
          "url": "admin-1.0.36.jar",
          "size": 4095,
          "sha512": "60e79abe70077b692b5aaa3b15d0e0dfda8eefa399d3882f6d9b87060fce0a5045023910a9ca0659233cd41d6ec60ad546b9474995dd4f305ccf8d4717589075",
          "sha256": "bfa620b302e75d8fe2612690aee6235000afb55630ba85f1112921c674ef19bc",
          "sha1": "82dec3a490066e0271ceab844c4811aaa84bbeab",
          "md5": "aaffd3fdfa7b6b580243c53f4f35de31"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.36-sources.jar",
          "url": "admin-1.0.36-sources.jar",
          "size": 2668,
          "sha512": "1c4718bcc24027e045b6aeda3d8b0f23d00708b90e0e84ce9a50a095e904ea59bbcb00769d0f246fd0c3bdfdea7a7f26da7daf6f2a4121c6d69739490e841647",
          "sha256": "f48842f103682c7cb82d1496f51b9edb54cc40dd777e7a62551bac4588d6fc75",
          "sha1": "8041ab639af0bb97c613d6bed1a0527100fb41fd",
          "md5": "823c20ea1ca4a4f24269f19122c19ec5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.36-javadoc.jar",
          "url": "admin-1.0.36-javadoc.jar",
          "size": 23518,
          "sha512": "7fde73d3c8e1a88dd6a59954bee214d839d99c12fbda1d28a0ff79daef72687d635808612d46354889b72be76380ca0ae51292960ea9ca2db9fb2493d4082561",
          "sha256": "b605539ab28d323ed6399a4af6cd8701aec591fb641730655b5d9a445ff7d874",
          "sha1": "1f85691bc735cfac43a58cd61d954a8e53abdccd",
          "md5": "9fa9274994388918dcc70edaca0cafc6"
        }
      ]
    }
  ]
}
