{
  "formatVersion": "1.1",
  "component": {
    "group": "com.modularmods.mcgltf",
    "module": "MCglTF",
    "version": "1.20.4-Fabric-2.1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MCglTF-1.20.4-Fabric-2.1.0.2.jar",
          "url": "MCglTF-1.20.4-Fabric-2.1.0.2.jar",
          "size": 584920,
          "sha512": "a85f64196cccda47999c49f6cc95f5278fa0463d319a74bbacb084a508484d6217e7ff7b9f17c6c22f762d107e0968a50ccfac022927c182972c146b2b649ddf",
          "sha256": "861bb53215ad7fbfc41eef106401437515003c0fd5b6ab0e3f0b74d85f3c84dd",
          "sha1": "0fd32e375cda5e7ba0152e2cb2a91fc8ccb25eb0",
          "md5": "391db680a9214098e4553014b4d7f17d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.2+1.20.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "iris",
          "version": {
            "requires": "1.7.2+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "MCglTF-1.20.4-Fabric-2.1.0.2.jar",
          "url": "MCglTF-1.20.4-Fabric-2.1.0.2.jar",
          "size": 584920,
          "sha512": "a85f64196cccda47999c49f6cc95f5278fa0463d319a74bbacb084a508484d6217e7ff7b9f17c6c22f762d107e0968a50ccfac022927c182972c146b2b649ddf",
          "sha256": "861bb53215ad7fbfc41eef106401437515003c0fd5b6ab0e3f0b74d85f3c84dd",
          "sha1": "0fd32e375cda5e7ba0152e2cb2a91fc8ccb25eb0",
          "md5": "391db680a9214098e4553014b4d7f17d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MCglTF-1.20.4-Fabric-2.1.0.2-sources.jar",
          "url": "MCglTF-1.20.4-Fabric-2.1.0.2-sources.jar",
          "size": 505446,
          "sha512": "45c351cf402a4a97f295d54fa7d4c4c028a7bcfed12521e159d4130dd368ef07c220a10796e425b01f6740f119acb19dfaa49935e7c3076b677854f80e4e7da2",
          "sha256": "03a26109ca1dd6e02c4b989d3aead191edf76f50285cce41850b1cc757082894",
          "sha1": "20218c082cb8dd741158186b64f649a352cbf422",
          "md5": "dbae3b12702705198b3ee321286496f7"
        }
      ]
    }
  ]
}
