{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "policy-impl",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "policy-impl-1.3.0-SNAPSHOT.jar",
          "url": "policy-impl-1.3.0-SNAPSHOT.jar",
          "size": 48627,
          "sha512": "b64c0b3afb3fb9055a5d2a221957848d3911e04a9b7d8eafd936ddd14b816fa08c9d643bb5768fd6f8c2df1245a8dca289ea46e886bc7781b50cc332c9ffa363",
          "sha256": "e7f24a5617b97df2d84bbccf0462bc32b077794ae05cecb122b9e9a9b3f811e5",
          "sha1": "4d78926d122c9fbe438cefae74d9053aa26a0f2a",
          "md5": "5239820beafc6fe31822521273ef8629"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "policy-impl-1.3.0-SNAPSHOT.jar",
          "url": "policy-impl-1.3.0-SNAPSHOT.jar",
          "size": 48627,
          "sha512": "b64c0b3afb3fb9055a5d2a221957848d3911e04a9b7d8eafd936ddd14b816fa08c9d643bb5768fd6f8c2df1245a8dca289ea46e886bc7781b50cc332c9ffa363",
          "sha256": "e7f24a5617b97df2d84bbccf0462bc32b077794ae05cecb122b9e9a9b3f811e5",
          "sha1": "4d78926d122c9fbe438cefae74d9053aa26a0f2a",
          "md5": "5239820beafc6fe31822521273ef8629"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "policy-impl-1.3.0-SNAPSHOT-sources.jar",
          "url": "policy-impl-1.3.0-SNAPSHOT-sources.jar",
          "size": 22750,
          "sha512": "615a4cf9555068f83a7490fbfafef2ec1ee6b53a0ebfd0f8c84d9187da703097c02e60d7ec6fdae516d7a558ceda13d305558834d5e30fbd2e90178d465e2821",
          "sha256": "528edfbb5d024424ce5a7a6cf7617194dbd9877bb7599ac60184735ef64c5dee",
          "sha1": "9ab838e55aba4fb6b85f0f5e704303795c82ed9a",
          "md5": "2c8aa1394ed20dc44c2f19d225062b40"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "policy-impl-1.3.0-SNAPSHOT-javadoc.jar",
          "url": "policy-impl-1.3.0-SNAPSHOT-javadoc.jar",
          "size": 188835,
          "sha512": "05f8da457f88dff38d9f06273323976131629fd221468286ccb2fa4321dd611eb518cd8b4256eae705b1544984b9396cfe8422e2c5d50cd3da41eca47ab2dfba",
          "sha256": "2459fe4df1a7317020e2c2760c6dfc722c94a6661b8c36d77ba5717c0df10572",
          "sha1": "e48bf7a90c9ae54f9da3fa272c0c55b62521f878",
          "md5": "fa412d8dfe59d29f62a8e7ca79f4606c"
        }
      ]
    }
  ]
}
