{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "policy-impl",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "policy-impl-1.3.0-SNAPSHOT.jar",
          "url": "policy-impl-1.3.0-SNAPSHOT.jar",
          "size": 48627,
          "sha512": "6cfb38de3930acbd73bb36cf284db5d9965bdd431c3155eca40c7609b506c9627b652a3bacfdb37e3f7a319c23d87f59b6d1e70e3bb6aacce151ed7acbc38018",
          "sha256": "7477c9e70ef7b52da180fca2625074d57bb38fa7699b4ce3d017c3d0de5833d0",
          "sha1": "6f648bf00d0037f62cbe3007bbf6621dea91e7d0",
          "md5": "6704fe893a87911e1c7af8cb386dae6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "policy-impl-1.3.0-SNAPSHOT.jar",
          "url": "policy-impl-1.3.0-SNAPSHOT.jar",
          "size": 48627,
          "sha512": "6cfb38de3930acbd73bb36cf284db5d9965bdd431c3155eca40c7609b506c9627b652a3bacfdb37e3f7a319c23d87f59b6d1e70e3bb6aacce151ed7acbc38018",
          "sha256": "7477c9e70ef7b52da180fca2625074d57bb38fa7699b4ce3d017c3d0de5833d0",
          "sha1": "6f648bf00d0037f62cbe3007bbf6621dea91e7d0",
          "md5": "6704fe893a87911e1c7af8cb386dae6b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "policy-impl-1.3.0-SNAPSHOT-sources.jar",
          "url": "policy-impl-1.3.0-SNAPSHOT-sources.jar",
          "size": 22750,
          "sha512": "618987a027dca7b7335f027cff578448bcc5eabdcd374995fe13e0a421623e21dbf1e71cf4f326eaaa4c7f3e7cc41cc435fe7b7ac817fc19fbe50607865ef521",
          "sha256": "3a7179ea9bec8a1effc0692aef0746f6ab2bfb012c1476e5330812897e5b1995",
          "sha1": "78cb07ac318d4cfdec4e9c9b56da42abae816e9b",
          "md5": "90f804b476dc7a0a203909dd0059c6e6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "policy-impl-1.3.0-SNAPSHOT-javadoc.jar",
          "url": "policy-impl-1.3.0-SNAPSHOT-javadoc.jar",
          "size": 188835,
          "sha512": "ae698f643c54cbecd9c0fa98663f3d0f57af706c55132508eaa5cbe9f679f78dcdfefd2bdc58f2e24caa949a354ad7a4fd4dea5916364c212351b0d9c050cbde",
          "sha256": "b0f598684171646dccd593ecf9dfdcd2fafc2a4f5548c2150532407939907bb5",
          "sha1": "acdc167202d7afb55b3758553a48b14e3e0117c5",
          "md5": "643c5990e8853b7e7e1fbe77a4147777"
        }
      ]
    }
  ]
}
