{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "policy-impl",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "policy-impl-1.3.0-SNAPSHOT.jar",
          "url": "policy-impl-1.3.0-SNAPSHOT.jar",
          "size": 48627,
          "sha512": "b64c0b3afb3fb9055a5d2a221957848d3911e04a9b7d8eafd936ddd14b816fa08c9d643bb5768fd6f8c2df1245a8dca289ea46e886bc7781b50cc332c9ffa363",
          "sha256": "e7f24a5617b97df2d84bbccf0462bc32b077794ae05cecb122b9e9a9b3f811e5",
          "sha1": "4d78926d122c9fbe438cefae74d9053aa26a0f2a",
          "md5": "5239820beafc6fe31822521273ef8629"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "policy-impl-1.3.0-SNAPSHOT.jar",
          "url": "policy-impl-1.3.0-SNAPSHOT.jar",
          "size": 48627,
          "sha512": "b64c0b3afb3fb9055a5d2a221957848d3911e04a9b7d8eafd936ddd14b816fa08c9d643bb5768fd6f8c2df1245a8dca289ea46e886bc7781b50cc332c9ffa363",
          "sha256": "e7f24a5617b97df2d84bbccf0462bc32b077794ae05cecb122b9e9a9b3f811e5",
          "sha1": "4d78926d122c9fbe438cefae74d9053aa26a0f2a",
          "md5": "5239820beafc6fe31822521273ef8629"
        }
      ]
    }
  ]
}
