{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.datagateways",
    "module": "datagateways",
    "version": "1.0.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "datagateways-1.0.38.jar",
          "url": "datagateways-1.0.38.jar",
          "size": 261,
          "sha512": "215964251b4fa578286c13945c538b992488e5a9333ea939a613d971afdbc728a55c35b2a7877a3cb26b5c281863a3f76bb09b43478b16ba91fc550f2a762baf",
          "sha256": "dac8c07d89d323239ab93cbfe54d901ce070480d195e2aaac414c6bc32d32a1c",
          "sha1": "c44e918dd9f9cf07423641afff14f2829b732e17",
          "md5": "6d6aba84899d30ab78681d67f85615c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.38.jar",
          "url": "datagateways-1.0.38.jar",
          "size": 261,
          "sha512": "215964251b4fa578286c13945c538b992488e5a9333ea939a613d971afdbc728a55c35b2a7877a3cb26b5c281863a3f76bb09b43478b16ba91fc550f2a762baf",
          "sha256": "dac8c07d89d323239ab93cbfe54d901ce070480d195e2aaac414c6bc32d32a1c",
          "sha1": "c44e918dd9f9cf07423641afff14f2829b732e17",
          "md5": "6d6aba84899d30ab78681d67f85615c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.38-sources.jar",
          "url": "datagateways-1.0.38-sources.jar",
          "size": 261,
          "sha512": "215964251b4fa578286c13945c538b992488e5a9333ea939a613d971afdbc728a55c35b2a7877a3cb26b5c281863a3f76bb09b43478b16ba91fc550f2a762baf",
          "sha256": "dac8c07d89d323239ab93cbfe54d901ce070480d195e2aaac414c6bc32d32a1c",
          "sha1": "c44e918dd9f9cf07423641afff14f2829b732e17",
          "md5": "6d6aba84899d30ab78681d67f85615c8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.38-javadoc.jar",
          "url": "datagateways-1.0.38-javadoc.jar",
          "size": 261,
          "sha512": "215964251b4fa578286c13945c538b992488e5a9333ea939a613d971afdbc728a55c35b2a7877a3cb26b5c281863a3f76bb09b43478b16ba91fc550f2a762baf",
          "sha256": "dac8c07d89d323239ab93cbfe54d901ce070480d195e2aaac414c6bc32d32a1c",
          "sha1": "c44e918dd9f9cf07423641afff14f2829b732e17",
          "md5": "6d6aba84899d30ab78681d67f85615c8"
        }
      ]
    }
  ]
}
