{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "screen-adapter",
    "version": "1.3.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "screen-adapter-1.3.5-SNAPSHOT.jar",
          "url": "screen-adapter-1.3.5-SNAPSHOT.jar",
          "size": 4227,
          "sha512": "d1b817afe72bc29a07fcb6f0a2fc3b1f35c9040527f622c354994c9dcaadd62e620064ffc9ed2c38dc367bfc1e3a23e5487b4cfb59be0f1c412082347361c1a9",
          "sha256": "53d2c9646cca21c4353b4164c148ec226c09e1442b68e06937c27953a39af0d9",
          "sha1": "1fab9acd410ebbce1bf583e7aa7ea876431787fd",
          "md5": "07021e549bca21c084ad7f8ac8de4bd4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.33"
          }
        }
      ],
      "files": [
        {
          "name": "screen-adapter-1.3.5-SNAPSHOT.jar",
          "url": "screen-adapter-1.3.5-SNAPSHOT.jar",
          "size": 4227,
          "sha512": "d1b817afe72bc29a07fcb6f0a2fc3b1f35c9040527f622c354994c9dcaadd62e620064ffc9ed2c38dc367bfc1e3a23e5487b4cfb59be0f1c412082347361c1a9",
          "sha256": "53d2c9646cca21c4353b4164c148ec226c09e1442b68e06937c27953a39af0d9",
          "sha1": "1fab9acd410ebbce1bf583e7aa7ea876431787fd",
          "md5": "07021e549bca21c084ad7f8ac8de4bd4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen-adapter-1.3.5-SNAPSHOT-sources.jar",
          "url": "screen-adapter-1.3.5-SNAPSHOT-sources.jar",
          "size": 2606,
          "sha512": "7fedd5f7452d36631fe37c92045474454eb0cad13165d69c32a4ba28178278b47bb3e81743eae645938677aba827c0e84986c1c87e53fd6301c3e14bccd20cad",
          "sha256": "612f32797c228ae821d12acc623e7439a40bd516ca3ac5e0517debef42cd92e8",
          "sha1": "06f842d1cc0deb437c2d2e00d14114e3d5c3ca46",
          "md5": "b1dc636c963e995f01f19c9b58983828"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen-adapter-1.3.5-SNAPSHOT-javadoc.jar",
          "url": "screen-adapter-1.3.5-SNAPSHOT-javadoc.jar",
          "size": 27916,
          "sha512": "b5e4c3528220ac5e229ba16db4842d4ca904b1a313ec690891de5e94da3ba5e902cc888c150ce7028408fd025d27a5053b592c4b0f79fd3254983d08e9b5fa41",
          "sha256": "f26036bab60256c9dbc74cae3fd4bb3d128832a125b51a6c466971fe86ea2035",
          "sha1": "b8bf58776c0beb00961732ec356028f905c585d3",
          "md5": "36c120487010d94502fcaa26dfd7888d"
        }
      ]
    }
  ]
}
