{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.views",
    "module": "admin",
    "version": "1.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.36.jar",
          "url": "admin-1.0.36.jar",
          "size": 261,
          "sha512": "445077af86c47d490d58f5f4139c1d639a731984c42b21c313937b903d55edbb7ba1945ff28888a57c2ef460946c8ed4794a759a3b51b850ba0285639aff5d5b",
          "sha256": "e307dbfb94359ab33330866e7e23a38b1238cfecb1bd3c77cfb92014f7d1946f",
          "sha1": "93a22b6f0fd7568e0e3d7958e138681fca04d031",
          "md5": "d1840a7c4cf14b617d0b4201579b6712"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.36.jar",
          "url": "admin-1.0.36.jar",
          "size": 261,
          "sha512": "445077af86c47d490d58f5f4139c1d639a731984c42b21c313937b903d55edbb7ba1945ff28888a57c2ef460946c8ed4794a759a3b51b850ba0285639aff5d5b",
          "sha256": "e307dbfb94359ab33330866e7e23a38b1238cfecb1bd3c77cfb92014f7d1946f",
          "sha1": "93a22b6f0fd7568e0e3d7958e138681fca04d031",
          "md5": "d1840a7c4cf14b617d0b4201579b6712"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.36-sources.jar",
          "url": "admin-1.0.36-sources.jar",
          "size": 999,
          "sha512": "cfbb8d138a040e823a967b973cc09f86c9461a46c894a86a38a132a1ebc081b808da640b7a4fa7e1f7bec29cfac1900cf61b454b4e01e4e20907e09ca835fd18",
          "sha256": "c5e63d1f42ee9a072c4e10e1cdc061e33a721991b90ed833ee3ded383ac1973b",
          "sha1": "1edcf7f774d9b1a1ca9f8f7ee57918d168c26763",
          "md5": "95cc52a0771f4e14276fa6c92be9e9e6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.36-javadoc.jar",
          "url": "admin-1.0.36-javadoc.jar",
          "size": 261,
          "sha512": "445077af86c47d490d58f5f4139c1d639a731984c42b21c313937b903d55edbb7ba1945ff28888a57c2ef460946c8ed4794a759a3b51b850ba0285639aff5d5b",
          "sha256": "e307dbfb94359ab33330866e7e23a38b1238cfecb1bd3c77cfb92014f7d1946f",
          "sha1": "93a22b6f0fd7568e0e3d7958e138681fca04d031",
          "md5": "d1840a7c4cf14b617d0b4201579b6712"
        }
      ]
    }
  ]
}
