{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.callhandler",
    "module": "callhandler",
    "version": "1.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callhandler-1.0.16.jar",
          "url": "callhandler-1.0.16.jar",
          "size": 1401,
          "sha512": "ca6a7c031dcba4401ad4a415ff84349062435dd0d95b0a14bec24bdaae4c4904ae3e2badda659550c61b04ddf70e0009ab30197508cda0cedda29e17df72a7c4",
          "sha256": "6ab6da5182db55e96bd11b227b85ff64c3e15260d175e962b13622fa41a819f1",
          "sha1": "84deac9e3bb52c8be57ccf7d40c25bb4b3e6a7ca",
          "md5": "aaedeef6604e7c06047a12fd08ccd6ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "callhandler-1.0.16.jar",
          "url": "callhandler-1.0.16.jar",
          "size": 1401,
          "sha512": "ca6a7c031dcba4401ad4a415ff84349062435dd0d95b0a14bec24bdaae4c4904ae3e2badda659550c61b04ddf70e0009ab30197508cda0cedda29e17df72a7c4",
          "sha256": "6ab6da5182db55e96bd11b227b85ff64c3e15260d175e962b13622fa41a819f1",
          "sha1": "84deac9e3bb52c8be57ccf7d40c25bb4b3e6a7ca",
          "md5": "aaedeef6604e7c06047a12fd08ccd6ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callhandler-1.0.16-sources.jar",
          "url": "callhandler-1.0.16-sources.jar",
          "size": 1265,
          "sha512": "f6359edd835d9a536fdec97b742dc014efa6e13067f5fa41de0d8761a7bd5986450c1ac5fc9274ba3b575e7c2be4d118db966bc7aea436d9e84cf5a66a769b02",
          "sha256": "e1b9a0b4d23371882454a82f44cc98a8a6424e6e596c7d0f5bfa37264219e486",
          "sha1": "3bbc7d11b830bcdeab35e7b6b58802c85ef3ddc7",
          "md5": "51800054d9c88475ec2ea5e754234160"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callhandler-1.0.16-javadoc.jar",
          "url": "callhandler-1.0.16-javadoc.jar",
          "size": 19261,
          "sha512": "de470d781c9697090cd430d463b896f14db6d29f247cbb56eba39921ce3e83443ec2bdb97fb10964437d45e286561eb614621e489cd497b308009d4ba9ba77e9",
          "sha256": "be1b5b27443f31760c2942d87a6044443486aaa3667c5a22f411f4df996dcb24",
          "sha1": "8ae5f7c88133a958b059bec02ddb1b7c46b2fc33",
          "md5": "be7b61ad0e4b38166d934c26ffe44b56"
        }
      ]
    }
  ]
}
