{
  "formatVersion": "1.1",
  "component": {
    "group": "io.libp2p",
    "module": "jvm-libp2p",
    "version": "1.2.3R-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-libp2p-1.2.3R-SNAPSHOT.jar",
          "url": "jvm-libp2p-1.2.3R-SNAPSHOT.jar",
          "size": 1726162,
          "sha512": "fb5493f648d6f65c3a354e33078ce648ff97e7d8f6cbc440a2f61625c9d81831498e5d51914336390416a2b1a08ed32778a02117e842224e485241f1aba8869e",
          "sha256": "021e7c77952e10e9ee2668b36c22a6b8ce63ca6460fcd195db89ab16b2912861",
          "sha1": "79f7a9e716588b8daf5d297261e595cf84ffba4c",
          "md5": "f7d7542c0e3919c03534109f5128d34d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-codec-http",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-classes-epoll",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-x86_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-aarch_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-x86_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-aarch_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "windows-x86_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-x86_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-aarch_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-x86_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-aarch_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "windows-x86_64"
            }
          }
        },
        {
          "group": "com.github.multiformats",
          "module": "java-multibase",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "tech.pegasys",
          "module": "noise-java",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-libp2p-1.2.3R-SNAPSHOT.jar",
          "url": "jvm-libp2p-1.2.3R-SNAPSHOT.jar",
          "size": 1726162,
          "sha512": "fb5493f648d6f65c3a354e33078ce648ff97e7d8f6cbc440a2f61625c9d81831498e5d51914336390416a2b1a08ed32778a02117e842224e485241f1aba8869e",
          "sha256": "021e7c77952e10e9ee2668b36c22a6b8ce63ca6460fcd195db89ab16b2912861",
          "sha1": "79f7a9e716588b8daf5d297261e595cf84ffba4c",
          "md5": "f7d7542c0e3919c03534109f5128d34d"
        }
      ]
    }
  ]
}
