{
  "formatVersion": "1.1",
  "component": {
    "group": "mod.chiselsandbits",
    "module": "chiselsandbits",
    "version": "1.2.6+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "20.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "chiselsandbits-1.2.6+1.20.4.jar",
          "url": "chiselsandbits-1.2.6+1.20.4.jar",
          "size": 1098160,
          "sha512": "87b001ec526458b2c1c9b56a02daf1d892014c54c8ce26ecc1ed40ee33cb3076a962fd40eba6b1ad034caccc1ed95a5779c43ea61a62abc974165a59dd6d00bb",
          "sha256": "60425e50d48c55fca2e9679f9d0d36cb413a148607d60922583a41c31acc1423",
          "sha1": "0896309ab2c1d820ada415c3de92894ee2588ba7",
          "md5": "8a1cad0e1e09f87fd9db6528e855c182"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "20.4.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.1+1.20.4"
          }
        },
        {
          "group": "com.jamieswhiteshirt",
          "module": "reach-entity-attributes",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.communi-suggestu.saecularia-caudices",
          "module": "saecularia-caudices-fabric",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "io.github.feltmc",
          "module": "fabricated-forge-caps",
          "version": {
            "requires": "0.1-1.20.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modernkeybinding",
          "version": {
            "requires": "1.20.4-1.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.djtheredstoner",
          "module": "DevAuth-fabric",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "chiselsandbits-1.2.6+1.20.4.jar",
          "url": "chiselsandbits-1.2.6+1.20.4.jar",
          "size": 1098160,
          "sha512": "87b001ec526458b2c1c9b56a02daf1d892014c54c8ce26ecc1ed40ee33cb3076a962fd40eba6b1ad034caccc1ed95a5779c43ea61a62abc974165a59dd6d00bb",
          "sha256": "60425e50d48c55fca2e9679f9d0d36cb413a148607d60922583a41c31acc1423",
          "sha1": "0896309ab2c1d820ada415c3de92894ee2588ba7",
          "md5": "8a1cad0e1e09f87fd9db6528e855c182"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chiselsandbits-1.2.6+1.20.4-sources.jar",
          "url": "chiselsandbits-1.2.6+1.20.4-sources.jar",
          "size": 524128,
          "sha512": "c608d9c4b20342d917b998b942d4aebcf71b44af1a0623b4830e3241f38e18b9f64936ba9697fffcb96fdbf02341df1acd250a84eb04e8ab776a17f7534b1c71",
          "sha256": "0f370ebb719ae14706f9dbf95c2bd3ca8f1dc972cbf89e4c9fda07cbc7c7f857",
          "sha1": "976236c273c5b805b0a23b12b25ccecb8e69ec2f",
          "md5": "b51be2c3accfab709986235f77b0fedc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chiselsandbits-1.2.6+1.20.4-javadoc.jar",
          "url": "chiselsandbits-1.2.6+1.20.4-javadoc.jar",
          "size": 1294357,
          "sha512": "9ae1407af22c42f78e2e619940c731162d902d064c70c48386d9fd1bf261708ffd63c81d223ede8e7e09021e20cbbc5a34f2b716d323c1ce1bb5efff6525a5f2",
          "sha256": "fcacc726235cf0acf782543b91bcc977ae8b5c54d494c1aefe8583b3e028f0bf",
          "sha1": "44b41d759eb4fb81ad5acf8ad3884ca021f79bbd",
          "md5": "c2712dd12c403faf4122d4f3fbcff641"
        }
      ]
    }
  ]
}
