{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "screen-adapter",
    "version": "1.3.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "screen-adapter-1.3.4-SNAPSHOT.jar",
          "url": "screen-adapter-1.3.4-SNAPSHOT.jar",
          "size": 4227,
          "sha512": "9378fa0e4d66f0d12919315ece0b09f34854ad1f6986ceee92826fbf035aea2c6ee4127fe4ff2cb874ee651d1419ac53938aea626f535c88efb938558c326c31",
          "sha256": "d6e7cbb1254b700ace2d897ca606285104697580ecd1525bfb28731cb7906a0f",
          "sha1": "7fd1fd82fa77daee0b0c4c803701eb0a0b3267aa",
          "md5": "2ada46f075a06b666a963fc4a74d6767"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.33"
          }
        }
      ],
      "files": [
        {
          "name": "screen-adapter-1.3.4-SNAPSHOT.jar",
          "url": "screen-adapter-1.3.4-SNAPSHOT.jar",
          "size": 4227,
          "sha512": "9378fa0e4d66f0d12919315ece0b09f34854ad1f6986ceee92826fbf035aea2c6ee4127fe4ff2cb874ee651d1419ac53938aea626f535c88efb938558c326c31",
          "sha256": "d6e7cbb1254b700ace2d897ca606285104697580ecd1525bfb28731cb7906a0f",
          "sha1": "7fd1fd82fa77daee0b0c4c803701eb0a0b3267aa",
          "md5": "2ada46f075a06b666a963fc4a74d6767"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen-adapter-1.3.4-SNAPSHOT-sources.jar",
          "url": "screen-adapter-1.3.4-SNAPSHOT-sources.jar",
          "size": 2606,
          "sha512": "3be4750d466079e2fa7488de1ee5f1aa6c19b20bdfc4447c8329672e96f0f30d42585c1786b7735823f6db813efccb112f4755e54775af757c65aa4821d2bed1",
          "sha256": "21581d24acffe36dc6a05add0a2dd1570ecaf5ea3066ad4a91b9718b1ad413d6",
          "sha1": "f496b6db113cfb64b554620011f4d3e584cd10f0",
          "md5": "97c54fcdb7098a2bd1ab170627e3483d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen-adapter-1.3.4-SNAPSHOT-javadoc.jar",
          "url": "screen-adapter-1.3.4-SNAPSHOT-javadoc.jar",
          "size": 27908,
          "sha512": "104b60f98501e6a58e5a9d02c11c14eb51e45d072154a7f6e63552d98b2fcf326c634483607ceabc51d7cbbc7cbd2017e641d8266e3e47b96de3268506291e1e",
          "sha256": "e902745d6582dc4cf931e7cc17c98446f83bb7b97098b3b4eed4b9dfa74f5019",
          "sha1": "9936f27b40434b7147057e08401743b5c70eaa8e",
          "md5": "64b6e09363413ffcd046f88c33b3d54b"
        }
      ]
    }
  ]
}
