{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "config",
    "version": "1.3.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-1.3.7-SNAPSHOT.jar",
          "url": "config-1.3.7-SNAPSHOT.jar",
          "size": 8215,
          "sha512": "1fbef38af92538a0a7a7166d8a359e7db6a54457b3437710e6d2fc29187b9e5c2a82e3dc1a8201aa686c3ba064aa8abfcaaefdadc26cf8fdd9b2dc55560c7ac1",
          "sha256": "efcb92b40d9caaff4f9119e0b67a8a90b9f36ffa1501cc913339bc27c7b7f99d",
          "sha1": "42d3d55fa059bab34e08f2b34da9a42c1e1ae43f",
          "md5": "93cd5b9b8f9f616870df51683044f995"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.33"
          }
        }
      ],
      "files": [
        {
          "name": "config-1.3.7-SNAPSHOT.jar",
          "url": "config-1.3.7-SNAPSHOT.jar",
          "size": 8215,
          "sha512": "1fbef38af92538a0a7a7166d8a359e7db6a54457b3437710e6d2fc29187b9e5c2a82e3dc1a8201aa686c3ba064aa8abfcaaefdadc26cf8fdd9b2dc55560c7ac1",
          "sha256": "efcb92b40d9caaff4f9119e0b67a8a90b9f36ffa1501cc913339bc27c7b7f99d",
          "sha1": "42d3d55fa059bab34e08f2b34da9a42c1e1ae43f",
          "md5": "93cd5b9b8f9f616870df51683044f995"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.7-SNAPSHOT-sources.jar",
          "url": "config-1.3.7-SNAPSHOT-sources.jar",
          "size": 4221,
          "sha512": "970f8f61e53b5614ea601e875ad757fed205209a694c86e479f29158eaf781fadbb9e950a61e037196ba8824966cea69558b2ea622217246e147d0f583be96ec",
          "sha256": "96bb292882365f7143238950692287a37fdb7f67a56ef1c6c712b059b89ca126",
          "sha1": "e5f90b0db616be5f02e5c201bb9fe135b3208af4",
          "md5": "2aba13e2a500ddcde64dcaade8359e45"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.7-SNAPSHOT-javadoc.jar",
          "url": "config-1.3.7-SNAPSHOT-javadoc.jar",
          "size": 45757,
          "sha512": "597f388cf1a0c7e4f57ae7e6f82f9d75d60209808546f9beefc5858c6140d23f62ade94f992a4e93c68a31b62fdc619067266fce4764f77ea97e0c1e9846733b",
          "sha256": "83e05f7c23057e844548469c3ec0fb4c5cbc9a3544351725c92df16f9cb6ae65",
          "sha1": "cec335f8aed7c8669327523db41d316b378fc895",
          "md5": "096365068a47ec43ee535be7cdde6aea"
        }
      ]
    }
  ]
}
