{
  "formatVersion": "1.1",
  "component": {
    "group": "mod.chiselsandbits",
    "module": "chiselsandbits",
    "version": "1.2.1-beta.4+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "20.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "chiselsandbits-1.2.1-beta.4+1.20.4.jar",
          "url": "chiselsandbits-1.2.1-beta.4+1.20.4.jar",
          "size": 1093779,
          "sha512": "4661e3bd7274c9ce5479da7ee272470666ed696a23e82f1bc13b3c5587b4add33dec7b33f9a0d35c624983cebe076c16bf4065bee7247195cfeb45daf7484cde",
          "sha256": "4ded4729333deb6d95d5cd6237fc8570601c2ceac1f4762c9c1e9da861a20c70",
          "sha1": "88509e6fae78462248b27400e30020a155c51e89",
          "md5": "bb4a4b4a66efef98ab3a198935891f85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "20.4.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.1+1.20.4"
          }
        },
        {
          "group": "com.jamieswhiteshirt",
          "module": "reach-entity-attributes",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.communi-suggestu.saecularia-caudices",
          "module": "saecularia-caudices-fabric",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "io.github.feltmc",
          "module": "fabricated-forge-caps",
          "version": {
            "requires": "0.1-1.20.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modernkeybinding",
          "version": {
            "requires": "1.20.4-1.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "chiselsandbits-1.2.1-beta.4+1.20.4.jar",
          "url": "chiselsandbits-1.2.1-beta.4+1.20.4.jar",
          "size": 1093779,
          "sha512": "4661e3bd7274c9ce5479da7ee272470666ed696a23e82f1bc13b3c5587b4add33dec7b33f9a0d35c624983cebe076c16bf4065bee7247195cfeb45daf7484cde",
          "sha256": "4ded4729333deb6d95d5cd6237fc8570601c2ceac1f4762c9c1e9da861a20c70",
          "sha1": "88509e6fae78462248b27400e30020a155c51e89",
          "md5": "bb4a4b4a66efef98ab3a198935891f85"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chiselsandbits-1.2.1-beta.4+1.20.4-sources.jar",
          "url": "chiselsandbits-1.2.1-beta.4+1.20.4-sources.jar",
          "size": 522152,
          "sha512": "a78bc398fddb9c3aa118f1b2ba3033d5550847ad29c58bab76ef7ab6433af8b7267018b5141c5085901d52362e5d40c58d7f497de0e5da9c2e7f261dbb9d0170",
          "sha256": "d846f59c7a2e8f7acebcb1c89ee47e9a4c1dacb75293bc5455b7dcddddd4c413",
          "sha1": "c8e89b8f8df97af70035da8101426c9f4b5e5757",
          "md5": "1c83c8b4d646dd5b0aec3e8b0f976fe2"
        }
      ]
    }
  ]
}
