{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "screen-adapter",
    "version": "1.3.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "screen-adapter-1.3.6-SNAPSHOT.jar",
          "url": "screen-adapter-1.3.6-SNAPSHOT.jar",
          "size": 4227,
          "sha512": "bb38e24d60d170459eca30079d839e674f2297e3c104f4355475813dbb14cf3c91161609bcd2d862e66437b86495a370cbe7750af93f0abc0cab5a6c814e404b",
          "sha256": "1c50148273b3b5396eac29c58a92f5e474c5fd9de66c50967f5afbba7c50e40d",
          "sha1": "9399992a25136dbaf1d31f311a0ba9e8f2e858c5",
          "md5": "92d6a6bebe1d8a0baafa9222cf260d34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.33"
          }
        }
      ],
      "files": [
        {
          "name": "screen-adapter-1.3.6-SNAPSHOT.jar",
          "url": "screen-adapter-1.3.6-SNAPSHOT.jar",
          "size": 4227,
          "sha512": "bb38e24d60d170459eca30079d839e674f2297e3c104f4355475813dbb14cf3c91161609bcd2d862e66437b86495a370cbe7750af93f0abc0cab5a6c814e404b",
          "sha256": "1c50148273b3b5396eac29c58a92f5e474c5fd9de66c50967f5afbba7c50e40d",
          "sha1": "9399992a25136dbaf1d31f311a0ba9e8f2e858c5",
          "md5": "92d6a6bebe1d8a0baafa9222cf260d34"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen-adapter-1.3.6-SNAPSHOT-sources.jar",
          "url": "screen-adapter-1.3.6-SNAPSHOT-sources.jar",
          "size": 2606,
          "sha512": "4bbf3018661f1b13653c7c6732cb036366b2c2de23b99f052d2773944c17ced8a47ca8ae4b81e91ed45f7ed506b89f8e3ca1b28cbf2918e0f42f80c8e897ffc8",
          "sha256": "da7cbc8b19eff52f622e6ed8b375ecd1c7c503d390d3dd8891fa400a34f2b7b6",
          "sha1": "fe97eea41ccbb0aca123eae1a3204ad1338cb362",
          "md5": "72f06b3d9e4039957d90b4bd8cf70862"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen-adapter-1.3.6-SNAPSHOT-javadoc.jar",
          "url": "screen-adapter-1.3.6-SNAPSHOT-javadoc.jar",
          "size": 27922,
          "sha512": "74ffb332768bcb501a39a8bfa29cbd68d2c9ea3b55670696062fa12ddb4d0e3939d0666e919705939f73bac96ca1c6135f092ed33f4709bd2a87958b04550470",
          "sha256": "2bc06e0703f0c84900b958ad822c7b4f088d7dfac3e5e3f44cd3602f4ca017d8",
          "sha1": "89b0c9fc1e7f999641924ed952932d8ce2cab96c",
          "md5": "7e9a295226b03eba1dc3b4b31318d9b8"
        }
      ]
    }
  ]
}
