{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.views",
    "module": "admin",
    "version": "1.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.27.jar",
          "url": "admin-1.0.27.jar",
          "size": 261,
          "sha512": "da393cec2e7a9a58b84cac12f7add3663bbf5e610a8b7cd994eb41724573d801a3510d9e793c0d4c33f0803c184b941bfcc4261710b537d22e940491c6532fbf",
          "sha256": "f25bd8684de1402e9230c4d264c348302e681a5a1bbb079f295b28e200243190",
          "sha1": "18c71bb245527267e022e3f6c73a40f108c8ab82",
          "md5": "71ca12208436377f77448b5d90350807"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.27.jar",
          "url": "admin-1.0.27.jar",
          "size": 261,
          "sha512": "da393cec2e7a9a58b84cac12f7add3663bbf5e610a8b7cd994eb41724573d801a3510d9e793c0d4c33f0803c184b941bfcc4261710b537d22e940491c6532fbf",
          "sha256": "f25bd8684de1402e9230c4d264c348302e681a5a1bbb079f295b28e200243190",
          "sha1": "18c71bb245527267e022e3f6c73a40f108c8ab82",
          "md5": "71ca12208436377f77448b5d90350807"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.27-sources.jar",
          "url": "admin-1.0.27-sources.jar",
          "size": 999,
          "sha512": "8107ec7419e5b350fffeac76b860c84d78e64b1bb9638d7a505f3c2500cb0fab9f3fd04f340bcf45416781b35fd10d9c966467ee2161005dacf25ad123144970",
          "sha256": "e3e6e9dafdddcbab9fe4d891a36fa3e173c49bcfaeae53dba1ee149d616846c0",
          "sha1": "7dfbcffc8b27321b9b6a78ec1554961cc751c3b3",
          "md5": "35b417e69f5f623bb7d3a351cb494a24"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.27-javadoc.jar",
          "url": "admin-1.0.27-javadoc.jar",
          "size": 261,
          "sha512": "da393cec2e7a9a58b84cac12f7add3663bbf5e610a8b7cd994eb41724573d801a3510d9e793c0d4c33f0803c184b941bfcc4261710b537d22e940491c6532fbf",
          "sha256": "f25bd8684de1402e9230c4d264c348302e681a5a1bbb079f295b28e200243190",
          "sha1": "18c71bb245527267e022e3f6c73a40f108c8ab82",
          "md5": "71ca12208436377f77448b5d90350807"
        }
      ]
    }
  ]
}
