{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.presenters",
    "module": "admin",
    "version": "1.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.36.jar",
          "url": "admin-1.0.36.jar",
          "size": 2112,
          "sha512": "f7dd6e22447d091f2b7a9832837badd9003a7e86053e316df2fb264a62d7d3a93460c170d5051b66aa9c332ba59c09b4b356abbbcf19a8581c8b58f30b6bccb9",
          "sha256": "268903036da7eee4709751ad1c9be2c34aae602d4819382fc8dcb221b36de0f4",
          "sha1": "69e4f99b4bdfcbcb284cc9c86728d9f7949bb1c2",
          "md5": "6635995c415b50f1b1641f432dfb1787"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "admin-1.0.36.jar",
          "url": "admin-1.0.36.jar",
          "size": 2112,
          "sha512": "f7dd6e22447d091f2b7a9832837badd9003a7e86053e316df2fb264a62d7d3a93460c170d5051b66aa9c332ba59c09b4b356abbbcf19a8581c8b58f30b6bccb9",
          "sha256": "268903036da7eee4709751ad1c9be2c34aae602d4819382fc8dcb221b36de0f4",
          "sha1": "69e4f99b4bdfcbcb284cc9c86728d9f7949bb1c2",
          "md5": "6635995c415b50f1b1641f432dfb1787"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.36-sources.jar",
          "url": "admin-1.0.36-sources.jar",
          "size": 1533,
          "sha512": "36af8426aa489d21ad2cac73d2ccd0576099d146ac9f8c0311ab7292a802c09a626f171673f5546324787fa85d538e3b18c5d8323e125168c62a1ea302710747",
          "sha256": "62bebf5a5c1c7045a22f949b065dd4b584342cc58bddb124df35a713fc39ba66",
          "sha1": "89d3ed03c6cb9ed2e5af7e1ddd2d01ed35ec20df",
          "md5": "f2aea84bc44d10ca009a5253171b5d8c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.36-javadoc.jar",
          "url": "admin-1.0.36-javadoc.jar",
          "size": 19938,
          "sha512": "fe94ae0b7cb187c1f6af1305ee9273a4243d3df9e56b7be8a1d18b5682c7f08957097440b337f3c74148e5a06325b1e3d27dfa3594ba6853fae2f390e0ca06f0",
          "sha256": "7351648b3178e3a8c1a7d9f05ad93547d6279b970a84bfc911c33000e4ab1215",
          "sha1": "25e0cc6ff39da44ebbceab5129f66ab11e90d4e7",
          "md5": "5b7f0b17900fbe219251a07a5567a2f5"
        }
      ]
    }
  ]
}
