{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.callhandler",
    "module": "callhandler",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callhandler-1.0.17.jar",
          "url": "callhandler-1.0.17.jar",
          "size": 1401,
          "sha512": "df9abd49995c0390b73f5f22ce4f73724e6dad7db9d9f0f848914d8a3d81106cd02fe6f685819ce2fc6116669411668b9cbc94b5aee6ef42a4195f5a590bdd9e",
          "sha256": "fe79a61e1de8a618373c7facbeaf86f883f7dd780b38e292efb9b69008299751",
          "sha1": "8e80d6f725243f661845f38734600100fc2aa26c",
          "md5": "99f40867fd14c483681d4e921b253efe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "callhandler-1.0.17.jar",
          "url": "callhandler-1.0.17.jar",
          "size": 1401,
          "sha512": "df9abd49995c0390b73f5f22ce4f73724e6dad7db9d9f0f848914d8a3d81106cd02fe6f685819ce2fc6116669411668b9cbc94b5aee6ef42a4195f5a590bdd9e",
          "sha256": "fe79a61e1de8a618373c7facbeaf86f883f7dd780b38e292efb9b69008299751",
          "sha1": "8e80d6f725243f661845f38734600100fc2aa26c",
          "md5": "99f40867fd14c483681d4e921b253efe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callhandler-1.0.17-sources.jar",
          "url": "callhandler-1.0.17-sources.jar",
          "size": 1265,
          "sha512": "9903eccf4d6b141bd7b535d83e330e27d5611ffb2ad61224546e0f80d5d2dde8de4111fdb16b117c3e263921f6c37a1d6fb2ee2df58df4c8ce96fe957487e27d",
          "sha256": "f1f6c81fb0c252a7a1f136e1f190c3563c033913c94a38aa54069ae06b3dcbf0",
          "sha1": "07da783ac70a8587445b06680de1d58b7b2e2d69",
          "md5": "6282cc384a2df24320d4f942900998ec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callhandler-1.0.17-javadoc.jar",
          "url": "callhandler-1.0.17-javadoc.jar",
          "size": 19260,
          "sha512": "42db17c9cfbdbfda6b9da8859a56e7bd4a62ad1e611d8954acbe2ec84cdcb70d95ae2c5fc9585a0139c94aa197f23a1565b906d05831c97dadbcc7f552fe5811",
          "sha256": "f1fc7466966676945806b2f7b5d93349687c0c5e02cdfa0b6f88eaa6393b3271",
          "sha1": "f22ea27d7aac10b9b04b31f1c64d0674fb091bf5",
          "md5": "b23f17df0ba01734b70ec84b16434358"
        }
      ]
    }
  ]
}
