{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "config",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-1.3.0-SNAPSHOT.jar",
          "url": "config-1.3.0-SNAPSHOT.jar",
          "size": 8164,
          "sha512": "5c06314b36368a8f87748aeb16dd508d83a2ad5aaf4673e8d1e57612d15ca4a3a31d474f124f885974986280beecbb1a491803b9de80e2b252f7c87d12fc66d4",
          "sha256": "df6409a0cde96e6ccecdaf0eafa9507ac84cef29feed7d957f510fb2390d4eec",
          "sha1": "c966e0ffd4138553e99d98d3e9098b5afc58652b",
          "md5": "7f32a792b4a5cf852ade0b8e85d58659"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.29"
          }
        }
      ],
      "files": [
        {
          "name": "config-1.3.0-SNAPSHOT.jar",
          "url": "config-1.3.0-SNAPSHOT.jar",
          "size": 8164,
          "sha512": "5c06314b36368a8f87748aeb16dd508d83a2ad5aaf4673e8d1e57612d15ca4a3a31d474f124f885974986280beecbb1a491803b9de80e2b252f7c87d12fc66d4",
          "sha256": "df6409a0cde96e6ccecdaf0eafa9507ac84cef29feed7d957f510fb2390d4eec",
          "sha1": "c966e0ffd4138553e99d98d3e9098b5afc58652b",
          "md5": "7f32a792b4a5cf852ade0b8e85d58659"
        }
      ]
    }
  ]
}
