{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "config",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-1.3.0-SNAPSHOT.jar",
          "url": "config-1.3.0-SNAPSHOT.jar",
          "size": 8164,
          "sha512": "5c06314b36368a8f87748aeb16dd508d83a2ad5aaf4673e8d1e57612d15ca4a3a31d474f124f885974986280beecbb1a491803b9de80e2b252f7c87d12fc66d4",
          "sha256": "df6409a0cde96e6ccecdaf0eafa9507ac84cef29feed7d957f510fb2390d4eec",
          "sha1": "c966e0ffd4138553e99d98d3e9098b5afc58652b",
          "md5": "7f32a792b4a5cf852ade0b8e85d58659"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.29"
          }
        }
      ],
      "files": [
        {
          "name": "config-1.3.0-SNAPSHOT.jar",
          "url": "config-1.3.0-SNAPSHOT.jar",
          "size": 8164,
          "sha512": "5c06314b36368a8f87748aeb16dd508d83a2ad5aaf4673e8d1e57612d15ca4a3a31d474f124f885974986280beecbb1a491803b9de80e2b252f7c87d12fc66d4",
          "sha256": "df6409a0cde96e6ccecdaf0eafa9507ac84cef29feed7d957f510fb2390d4eec",
          "sha1": "c966e0ffd4138553e99d98d3e9098b5afc58652b",
          "md5": "7f32a792b4a5cf852ade0b8e85d58659"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.0-SNAPSHOT-sources.jar",
          "url": "config-1.3.0-SNAPSHOT-sources.jar",
          "size": 4193,
          "sha512": "7c18e08428cd7a299f5e65771711a6abeca30b6a12b8d8c62d57a72e7b58f4751efec94a19c3f8f1b0298c09922fdd923e396adb6a9f0b233b644ddfdbd89238",
          "sha256": "b8d11dfbcbd476527972d943b99db85955cee07765b381f0544e2c99a43a55a2",
          "sha1": "14e53460fd8ff4563a08cc2fcc219a99735e9919",
          "md5": "0765ebc2b170b8e6b1ab1164a57f6e13"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.0-SNAPSHOT-javadoc.jar",
          "url": "config-1.3.0-SNAPSHOT-javadoc.jar",
          "size": 45700,
          "sha512": "05c0b9cfa586416627eb49bd5131acfc59c09e5261ffedfcd3916f01436da6b10db8ac17a04b7cca3859e804c7be4eb6597514b2b8b4955b0573875e075d1358",
          "sha256": "e40a2cc749a5c6af96c1329a1eeec879f1ec3218240cb03a25c4b60b9d53436d",
          "sha1": "655913aadf810be7f38a9b755e96aad811c392f2",
          "md5": "63066f833086c383f42433a503a43823"
        }
      ]
    }
  ]
}
