{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "config",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-1.3.0-SNAPSHOT.jar",
          "url": "config-1.3.0-SNAPSHOT.jar",
          "size": 8164,
          "sha512": "488c83d5f54f836ae22f01916f8db78c62b4933a6d3eceaaa80483356a324c87fafb52c7b047a9414fa2b8bae2b9ce920a7d8f8ec861eacae4963a81b953a045",
          "sha256": "d846b7988dd69b5c9a580894738b1fa1092d6d4aed91d2e3dd6fcd58a76f4f53",
          "sha1": "0ad1a94cd0865a925da57ba85e5496ed99d97e14",
          "md5": "bcb17e9f3564567f8ffda0129db20037"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.29"
          }
        }
      ],
      "files": [
        {
          "name": "config-1.3.0-SNAPSHOT.jar",
          "url": "config-1.3.0-SNAPSHOT.jar",
          "size": 8164,
          "sha512": "488c83d5f54f836ae22f01916f8db78c62b4933a6d3eceaaa80483356a324c87fafb52c7b047a9414fa2b8bae2b9ce920a7d8f8ec861eacae4963a81b953a045",
          "sha256": "d846b7988dd69b5c9a580894738b1fa1092d6d4aed91d2e3dd6fcd58a76f4f53",
          "sha1": "0ad1a94cd0865a925da57ba85e5496ed99d97e14",
          "md5": "bcb17e9f3564567f8ffda0129db20037"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.0-SNAPSHOT-sources.jar",
          "url": "config-1.3.0-SNAPSHOT-sources.jar",
          "size": 4193,
          "sha512": "f074655771c5b16fd42734f09662afe6518a099519e94767c82e9e8ca9067a548be6623c856e74b3b1ba6d8957c285b753d004971c2745814f4265d8a8705e48",
          "sha256": "9d39a3ca422949ca50aeac86254e111a613e60e49e1faef60988c54c3b178251",
          "sha1": "45fe39fad1d9ef9dc093e02d1a77f396e159a247",
          "md5": "41dd0862b2f4b208aa362669602e7282"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.0-SNAPSHOT-javadoc.jar",
          "url": "config-1.3.0-SNAPSHOT-javadoc.jar",
          "size": 45700,
          "sha512": "0c2eb2ed5e48b313702f2b6acdc33f8f21a802cd531a7c78b4cd3d27cffa70548deb60c1af9efff20a548edf50fef045c027f03fb0542c1777e054189a2f0d9a",
          "sha256": "170ed857f293c11b172a03548797447c2fd119f084daf7302c9bf2d3a69c09de",
          "sha1": "003c6f0a074ea9f464685d1ae4f19cbaeecf0251",
          "md5": "30f144933999779207d5da81e1da0b0c"
        }
      ]
    }
  ]
}
