{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "callee",
    "version": "1.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callee-1.0.18.jar",
          "url": "callee-1.0.18.jar",
          "size": 11356,
          "sha512": "21c8ab44ef176a657c0ca6cdf555879c83b7ef0e2d680d9d3b671fd89d7017a791a0dc45d1c018d2f8abb124ab3a3625b7948b3685b94b7c4a2a02241bfb1389",
          "sha256": "e85c1fcaa0ba0c8832c0a4ada479e267f915b700d9df03a3fe85a50105075030",
          "sha1": "2a58029e4a5da9178e5cd35f990134895a637af8",
          "md5": "b5b095270fd870a794dd26ad52c2b8be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.18"
          }
        }
      ],
      "files": [
        {
          "name": "callee-1.0.18.jar",
          "url": "callee-1.0.18.jar",
          "size": 11356,
          "sha512": "21c8ab44ef176a657c0ca6cdf555879c83b7ef0e2d680d9d3b671fd89d7017a791a0dc45d1c018d2f8abb124ab3a3625b7948b3685b94b7c4a2a02241bfb1389",
          "sha256": "e85c1fcaa0ba0c8832c0a4ada479e267f915b700d9df03a3fe85a50105075030",
          "sha1": "2a58029e4a5da9178e5cd35f990134895a637af8",
          "md5": "b5b095270fd870a794dd26ad52c2b8be"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.18-sources.jar",
          "url": "callee-1.0.18-sources.jar",
          "size": 8006,
          "sha512": "afd15857cb3023b444e712b5b7d890a7497e2973b6676303bf90786f3ea08be417029077c529b7b3a98d81d276414652f3e31a1b2f5ade0947b8c9d49fc90643",
          "sha256": "5ada5c8f4cdec919d5cd02df1548f0c686a024d020784a68238b5bf7972e161c",
          "sha1": "a4671af98e218589e2367632964540569a46d373",
          "md5": "a2970afdc5c205dce490274dc58359d4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.18-javadoc.jar",
          "url": "callee-1.0.18-javadoc.jar",
          "size": 81884,
          "sha512": "139736c6c2b5054d301171ac4e71698a07c151853f4c0bb73fdd6281e6d8f360f8ff13f5ef46321b60d0eee10fd7352327a364184f8d3f9107577f5a06d0b67b",
          "sha256": "3391c77fd4aa89e092a5a991288ce98b62c0d4d3d620f8d5a4b74e5a1872fc52",
          "sha1": "8765bb5e19da5e6a2328dd02e858295a19282e47",
          "md5": "25d948c18282ce76e965e5a1980a7b25"
        }
      ]
    }
  ]
}
