{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "config",
    "version": "1.3.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-1.3.4-SNAPSHOT.jar",
          "url": "config-1.3.4-SNAPSHOT.jar",
          "size": 8215,
          "sha512": "3865e92ab484fc27b5a6695ba9c29d219794b4ecc6c52d364b50d68c4ec5091b03beb8debb637f32b3dd229433a26111d584a094330183fca33c00875e27f6ec",
          "sha256": "eaa58b4bf810d05f10cb2b45d019be77773b71da67124b0b63f5d2a31bba5cad",
          "sha1": "7ede4badbe7158df172f921be833b7b7aa932d75",
          "md5": "059d0a10996c5c520288493d887705aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.33"
          }
        }
      ],
      "files": [
        {
          "name": "config-1.3.4-SNAPSHOT.jar",
          "url": "config-1.3.4-SNAPSHOT.jar",
          "size": 8215,
          "sha512": "3865e92ab484fc27b5a6695ba9c29d219794b4ecc6c52d364b50d68c4ec5091b03beb8debb637f32b3dd229433a26111d584a094330183fca33c00875e27f6ec",
          "sha256": "eaa58b4bf810d05f10cb2b45d019be77773b71da67124b0b63f5d2a31bba5cad",
          "sha1": "7ede4badbe7158df172f921be833b7b7aa932d75",
          "md5": "059d0a10996c5c520288493d887705aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.4-SNAPSHOT-sources.jar",
          "url": "config-1.3.4-SNAPSHOT-sources.jar",
          "size": 4221,
          "sha512": "c64c99b521a70197c14517285f00ac32237c4b427be84611cff51df616c52f3ec066c25034b7277463b522e0c03207a313d399e0fee1ba58a10116e137247a2d",
          "sha256": "25a80e39cd83c15df6fe00a52ee7417264264d6c70df1c33db6f6f812a51f5b6",
          "sha1": "8c9eb67bf1f7afe751651ca6c9afd1fb44b0027d",
          "md5": "bfb4e94d5fc108f966511ad9bf7eac42"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.4-SNAPSHOT-javadoc.jar",
          "url": "config-1.3.4-SNAPSHOT-javadoc.jar",
          "size": 45732,
          "sha512": "92f79c85f7a4972cbf70509a37d7b76e3ca3e466339b4424ae951e32b7685abd193db84636b91a7428c928a19820398a9e26e3b9b85d64234671059e29ad811d",
          "sha256": "def8f16fed1792c1687b66811a74c6d34b70b0b7823ca11329093ca187b5df91",
          "sha1": "89577b1ac560257c9d672c29bf7db15823fd48ed",
          "md5": "c5da2784dac9edcddb412cbb66494ce1"
        }
      ]
    }
  ]
}
