{
  "formatVersion": "1.1",
  "component": {
    "group": "mod.chiselsandbits",
    "module": "chiselsandbits",
    "version": "1.3.0+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "20.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "chiselsandbits-1.3.0+1.20.4.jar",
          "url": "chiselsandbits-1.3.0+1.20.4.jar",
          "size": 1099421,
          "sha512": "e717528837a0f1f601c9b029d037a07e459b9a3158142d333a6c23f7b8f16331277d7b93763826bba5200b330be2d7f56b531da3f7bbc48393e6bc162113ffda",
          "sha256": "28293a9ecd1ca6a9cf162492c0f6ab31b7d340b3d27ac671e3155b9ec22fb641",
          "sha1": "e6d2bb6bd40e32b48b1d3f9a4dbd437dd181d7dd",
          "md5": "0d1d4edf8a2bcdda533230053b4f35f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "20.4.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.1+1.20.4"
          }
        },
        {
          "group": "com.jamieswhiteshirt",
          "module": "reach-entity-attributes",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.communi-suggestu.saecularia-caudices",
          "module": "saecularia-caudices-fabric",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "io.github.feltmc",
          "module": "fabricated-forge-caps",
          "version": {
            "requires": "0.1-1.20.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modernkeybinding",
          "version": {
            "requires": "1.20.4-1.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "me.djtheredstoner",
          "module": "DevAuth-fabric",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "chiselsandbits-1.3.0+1.20.4.jar",
          "url": "chiselsandbits-1.3.0+1.20.4.jar",
          "size": 1099421,
          "sha512": "e717528837a0f1f601c9b029d037a07e459b9a3158142d333a6c23f7b8f16331277d7b93763826bba5200b330be2d7f56b531da3f7bbc48393e6bc162113ffda",
          "sha256": "28293a9ecd1ca6a9cf162492c0f6ab31b7d340b3d27ac671e3155b9ec22fb641",
          "sha1": "e6d2bb6bd40e32b48b1d3f9a4dbd437dd181d7dd",
          "md5": "0d1d4edf8a2bcdda533230053b4f35f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chiselsandbits-1.3.0+1.20.4-sources.jar",
          "url": "chiselsandbits-1.3.0+1.20.4-sources.jar",
          "size": 524496,
          "sha512": "a5f4e1a343de716da562553fd9f5aae5620eb5634214989bf8bfbb6f591880d97c23fe2d1c60493f12efd5c6622392ba2ccbd237479e1806def6ea6fc8a2f232",
          "sha256": "d9ef012f86bae2701f561eca8624a5157caccdfb1c8e0da40e2463bf900e6905",
          "sha1": "f478baabd60c9bd9e9eda9c7b38e0e347078c614",
          "md5": "4c749fc6e2d2baa33b260bb0dc7f8e62"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chiselsandbits-1.3.0+1.20.4-javadoc.jar",
          "url": "chiselsandbits-1.3.0+1.20.4-javadoc.jar",
          "size": 1330439,
          "sha512": "95aa9ad977056ac916dc15470d8f1edfbf77cc599c4b47c67e5669252aea16eff6330965a7bcfe3732db02a02693b4ff2e331652a6c7abda299b013663394284",
          "sha256": "8f439acfd76392fff39ccca23391e9c753d010d52884c6527367cf10bdb393f0",
          "sha1": "430eb8fbbe53f20a85341633ea0f0c4eec70b280",
          "md5": "e1a6f355b5e79957e5cd6eec7dae356d"
        }
      ]
    }
  ]
}
