{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.controllers",
    "module": "admin",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.15.jar",
          "url": "admin-1.0.15.jar",
          "size": 5157,
          "sha512": "d5809b1ccb04c2847995ec8afd29645113357fae2d6b9f8dc8367a8ae416054462408e0aab34eac2f11188385ad8fe53b6429ffb812cfe06b466005c57794f7d",
          "sha256": "c26ab2c630263ae1e7c21bd5cd80fd25a6ac7f82dea2926afa55a9d2abbee763",
          "sha1": "084e7494c6d02a5d90b3a682bdf25bb07c9935fc",
          "md5": "ab6f5eaa46a73559d95d15c0850bb300"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.15"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.15"
          }
        }
      ],
      "files": [
        {
          "name": "admin-1.0.15.jar",
          "url": "admin-1.0.15.jar",
          "size": 5157,
          "sha512": "d5809b1ccb04c2847995ec8afd29645113357fae2d6b9f8dc8367a8ae416054462408e0aab34eac2f11188385ad8fe53b6429ffb812cfe06b466005c57794f7d",
          "sha256": "c26ab2c630263ae1e7c21bd5cd80fd25a6ac7f82dea2926afa55a9d2abbee763",
          "sha1": "084e7494c6d02a5d90b3a682bdf25bb07c9935fc",
          "md5": "ab6f5eaa46a73559d95d15c0850bb300"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.15-sources.jar",
          "url": "admin-1.0.15-sources.jar",
          "size": 3383,
          "sha512": "8349da00c3b5f5207eb463443bdfdce2bad0641374a9c97bd1dd9e10cc77682035628eb4fc24361891e8501422612624c51e63e2985d7197212025a108da1096",
          "sha256": "a79b879943b7319827ca03d439e0cc8a787dd1c2ff2045847587c015e14b5198",
          "sha1": "484e38d370fa8527ece7477b7246e48cafbbf0f3",
          "md5": "634a560f4eab1e2bb1a7f873abbd8fcc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.15-javadoc.jar",
          "url": "admin-1.0.15-javadoc.jar",
          "size": 26419,
          "sha512": "9889e305bfb652d57f86c7c866c808a5d6f42ca27eec9570976266fb2491be7c868911b3f0d698589793dea02a8032b44ec9f05c43fa4937198b830cdbfe779a",
          "sha256": "3f1dfe3938f0cc1320a0b34580c33c16a176ec25271a431e2b1b4cebccf6bc3e",
          "sha1": "5e9cb399e33d94e754ef6522a7687464fa8d88f2",
          "md5": "90bb2ddf0e2100c578ae367cacd4f73a"
        }
      ]
    }
  ]
}
