{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.controllers",
    "module": "admin",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.15.jar",
          "url": "admin-1.0.15.jar",
          "size": 5183,
          "sha512": "d2f81bbee7c13fcd604f11b3a9c24c81f215a5fafa7f6e68ea4942031cb649e5ca62e8407416659ceaa2be836cd3b9307d8fbe1a2b25ced0e5c9bb79bacbed81",
          "sha256": "4ca2dfc0ff9f6fde2e673d1c16be8c15a297609b8b67b27ed443b5fd577d7cfe",
          "sha1": "0786b474918bc9529c27e63d8047deff0053684c",
          "md5": "05f7f260677c175c5c17c7f29b85f638"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.15"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.15"
          }
        }
      ],
      "files": [
        {
          "name": "admin-1.0.15.jar",
          "url": "admin-1.0.15.jar",
          "size": 5183,
          "sha512": "d2f81bbee7c13fcd604f11b3a9c24c81f215a5fafa7f6e68ea4942031cb649e5ca62e8407416659ceaa2be836cd3b9307d8fbe1a2b25ced0e5c9bb79bacbed81",
          "sha256": "4ca2dfc0ff9f6fde2e673d1c16be8c15a297609b8b67b27ed443b5fd577d7cfe",
          "sha1": "0786b474918bc9529c27e63d8047deff0053684c",
          "md5": "05f7f260677c175c5c17c7f29b85f638"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.15-sources.jar",
          "url": "admin-1.0.15-sources.jar",
          "size": 3383,
          "sha512": "8349da00c3b5f5207eb463443bdfdce2bad0641374a9c97bd1dd9e10cc77682035628eb4fc24361891e8501422612624c51e63e2985d7197212025a108da1096",
          "sha256": "a79b879943b7319827ca03d439e0cc8a787dd1c2ff2045847587c015e14b5198",
          "sha1": "484e38d370fa8527ece7477b7246e48cafbbf0f3",
          "md5": "634a560f4eab1e2bb1a7f873abbd8fcc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.15-javadoc.jar",
          "url": "admin-1.0.15-javadoc.jar",
          "size": 80653,
          "sha512": "6079b85bdc15d651d1125ab21c33a1c21a0b9eda823cd5c6b292259869104b17142334fb6c29619c48e58e7fc3ffb324070b43c6e58fcfdd7faac83310f15d33",
          "sha256": "d556a8f16ff787ab2f0da507b94e48e19ede7b9a7c9216518bdde0344710b592",
          "sha1": "2a345628f3eb3421e70dfc9b8e5a561180f13879",
          "md5": "93c23f09e6b2747ae69ba6829f4b0765"
        }
      ]
    }
  ]
}
