{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.presenters",
    "module": "admin",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.17.jar",
          "url": "admin-1.0.17.jar",
          "size": 2112,
          "sha512": "0369dfc155c8656d85c29f30c88b1fefd7ff434673d60487d0d0baca9004e9f85b90aa05e6a0a8bb474cefe4e46d36b1c4ac4df28f8e2a79c698b7389207e4b0",
          "sha256": "0a70396d607d03aaad5c15a68d5d69b95d99f064bcff8ef489a58a57e06bca89",
          "sha1": "cab08d69f40d3b20fd183269733b300d92596044",
          "md5": "ae83db3fed6615e799f24d680c4314df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "admin-1.0.17.jar",
          "url": "admin-1.0.17.jar",
          "size": 2112,
          "sha512": "0369dfc155c8656d85c29f30c88b1fefd7ff434673d60487d0d0baca9004e9f85b90aa05e6a0a8bb474cefe4e46d36b1c4ac4df28f8e2a79c698b7389207e4b0",
          "sha256": "0a70396d607d03aaad5c15a68d5d69b95d99f064bcff8ef489a58a57e06bca89",
          "sha1": "cab08d69f40d3b20fd183269733b300d92596044",
          "md5": "ae83db3fed6615e799f24d680c4314df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.17-sources.jar",
          "url": "admin-1.0.17-sources.jar",
          "size": 1717,
          "sha512": "cbc1483bb27f538648e901a049290346d24760fe08d1698f842d3c01821cb1a3ec34f3bd0786dd22a79fcd73ee8f1c6aab60caac5ee07ca1548474b42c2a744a",
          "sha256": "adfdc66c22504f33f082138b47e79cfa5b95595c38079e495d1fa0a922d0897a",
          "sha1": "ba17e7277ae5533423be50df6a83baea3e7438b8",
          "md5": "8930442a83cced45f348a35afc98f6a6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.17-javadoc.jar",
          "url": "admin-1.0.17-javadoc.jar",
          "size": 19918,
          "sha512": "682dbfa0cab0bba7dab205496445533b62e5e5ce4ba3d3ff9bf872d94cfd164b1c249bd3c8d888bf6a3919f42f43b21f78bd4d6b412a9078dd0ea8dda86f2622",
          "sha256": "7872b02d23fe3ce67889db5809d267824ee91ceb287efd7037744de90dc4ade5",
          "sha1": "c8ad6c07cad3796cd168261c69baa4cf162b18de",
          "md5": "ed075bdcb4b83baa50e33ad090b775a3"
        }
      ]
    }
  ]
}
