{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.presenters",
    "module": "admin",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.15.jar",
          "url": "admin-1.0.15.jar",
          "size": 2112,
          "sha512": "cfedd75bf0fcf16bc185968284c1c7ea8e4321cbd6d2cdb099a2878c33b8b9991dbaf9e472f5cb5ad125c42faf61f249ee120e674ee89f5ca43800adbc7017fb",
          "sha256": "a91caa59a4bc8c3ccd759402ff183412ecc6882e9800b2b7f1e5ceac726894a3",
          "sha1": "8277ed2cdaae714bf63713b31345933893934c50",
          "md5": "f7f77e78cf8c629fda4c0bc49401415e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.15"
          }
        }
      ],
      "files": [
        {
          "name": "admin-1.0.15.jar",
          "url": "admin-1.0.15.jar",
          "size": 2112,
          "sha512": "cfedd75bf0fcf16bc185968284c1c7ea8e4321cbd6d2cdb099a2878c33b8b9991dbaf9e472f5cb5ad125c42faf61f249ee120e674ee89f5ca43800adbc7017fb",
          "sha256": "a91caa59a4bc8c3ccd759402ff183412ecc6882e9800b2b7f1e5ceac726894a3",
          "sha1": "8277ed2cdaae714bf63713b31345933893934c50",
          "md5": "f7f77e78cf8c629fda4c0bc49401415e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.15-sources.jar",
          "url": "admin-1.0.15-sources.jar",
          "size": 1717,
          "sha512": "005699a64f7d2c216fcb28681447b4b2742d865b84c1e7f01f53ef95b1a19a3c62cb31a9f530834a080c0b576593fa486e479ec6d7a1679692dbf80eb46ea08b",
          "sha256": "4b72f4ad26d9d9776d3480f7097f69b6d9330c56a98e928bdafc70da0653af52",
          "sha1": "94ed5bfd4e45a93fd72af6d7e6723c85406b3f51",
          "md5": "a74b9dcca66ac2196f885e8984fa15fa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.15-javadoc.jar",
          "url": "admin-1.0.15-javadoc.jar",
          "size": 19911,
          "sha512": "a71d78f7bea626ecdb776979bb680107aed4fcfe7dba96d0f2b70960466bbce64458de29bb41b8fab9628daaf2539784fe21c14879c797b6b8a25b49dd04a8fd",
          "sha256": "b61d1d91ff9b46da9cb2ec7a2d66d1a8a1eba362410bea30c02a297a2b1ec65a",
          "sha1": "86d5c9960e5859bf8a2a2dfece8be09cd89b4a1d",
          "md5": "507dd4b16a849e4aed8e18b77b91d0a7"
        }
      ]
    }
  ]
}
