{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.presenters",
    "module": "admin",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.15.jar",
          "url": "admin-1.0.15.jar",
          "size": 2122,
          "sha512": "561eed60d935293f2343d9667fc75e434d36a20c946ab934275b06facb2a2d5f2bde2e5f484899ec0db2361cd8272dc0b1d594b584756abfde8d73cb822930ac",
          "sha256": "cdf781f2b30c2e7949e090e6ede3ce434cf03e74b60e33cce917288c1ada6f91",
          "sha1": "76388b5d23807e189c6f644e501f6ebce7740ecd",
          "md5": "357a07bdd47c6e12300db4f78900c850"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.15"
          }
        }
      ],
      "files": [
        {
          "name": "admin-1.0.15.jar",
          "url": "admin-1.0.15.jar",
          "size": 2122,
          "sha512": "561eed60d935293f2343d9667fc75e434d36a20c946ab934275b06facb2a2d5f2bde2e5f484899ec0db2361cd8272dc0b1d594b584756abfde8d73cb822930ac",
          "sha256": "cdf781f2b30c2e7949e090e6ede3ce434cf03e74b60e33cce917288c1ada6f91",
          "sha1": "76388b5d23807e189c6f644e501f6ebce7740ecd",
          "md5": "357a07bdd47c6e12300db4f78900c850"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.15-sources.jar",
          "url": "admin-1.0.15-sources.jar",
          "size": 1717,
          "sha512": "005699a64f7d2c216fcb28681447b4b2742d865b84c1e7f01f53ef95b1a19a3c62cb31a9f530834a080c0b576593fa486e479ec6d7a1679692dbf80eb46ea08b",
          "sha256": "4b72f4ad26d9d9776d3480f7097f69b6d9330c56a98e928bdafc70da0653af52",
          "sha1": "94ed5bfd4e45a93fd72af6d7e6723c85406b3f51",
          "md5": "a74b9dcca66ac2196f885e8984fa15fa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.15-javadoc.jar",
          "url": "admin-1.0.15-javadoc.jar",
          "size": 73740,
          "sha512": "87d6c3cc656f1523f6e834159a14cd1a2ed4ddee94f80176cd6a0be2e14879946e218707095d839295c9d697a865f70401eb9d484ff3b87084c59ebd66eafa73",
          "sha256": "d8c3ad81b999c414ddba9340a9153465a39f45f0e80661ce835ea8394ec912f2",
          "sha1": "573076a6225d6ac77efc133529f3126459a7bfc6",
          "md5": "8dc2343f9d083f5d50f9f3b87e5b787f"
        }
      ]
    }
  ]
}
