{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "caller",
    "version": "1.0.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "caller-1.0.35.jar",
          "url": "caller-1.0.35.jar",
          "size": 9367,
          "sha512": "a9c482fadfaef65b7c14191890d8c7f385285418411f7c7df2283cee2d00dacdc2f834f9ef5fac664d2e2aefece60518b8608f2a447daddcc6b088e957b5e9ac",
          "sha256": "d5fb953536866ca2c6fb32361b3f253f9adab481af30b0e14da7b266702efb30",
          "sha1": "6dc0ce94b7540dd02d4f5b91ce646b46f03b7cf0",
          "md5": "ca944c79e753c31736906093174f77ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caller-1.0.35.jar",
          "url": "caller-1.0.35.jar",
          "size": 9367,
          "sha512": "a9c482fadfaef65b7c14191890d8c7f385285418411f7c7df2283cee2d00dacdc2f834f9ef5fac664d2e2aefece60518b8608f2a447daddcc6b088e957b5e9ac",
          "sha256": "d5fb953536866ca2c6fb32361b3f253f9adab481af30b0e14da7b266702efb30",
          "sha1": "6dc0ce94b7540dd02d4f5b91ce646b46f03b7cf0",
          "md5": "ca944c79e753c31736906093174f77ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caller-1.0.35-sources.jar",
          "url": "caller-1.0.35-sources.jar",
          "size": 5615,
          "sha512": "279522479cf22d0d64e3468c9405458a55d0b435c5c7565836b746d738a8d721b11605cfb0501f13af0f532c3e204bef7f1facfd5562d0ded3f5d4167318c1b0",
          "sha256": "6ab7327992ff96fc6bedd34cc0d13372ede1f017cbcb3a13dbfcc250302f2792",
          "sha1": "7ed40adc74865e1a8c6e2073a4a00a1779eec0df",
          "md5": "3bbc3738439fa30b99e29cf4465ad9c6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caller-1.0.35-javadoc.jar",
          "url": "caller-1.0.35-javadoc.jar",
          "size": 61414,
          "sha512": "5943b55285b99d6cf3a451c6f3fe4b5d981b9996203112d971a057664ba8365cb816ae2fbefa89912806e9b98fa9cd17506a3f3e27e97d6a9800922fbc03b574",
          "sha256": "2ea0ba79a763c851866315b6283881f53a563ef58e19f72f75a4499af1700853",
          "sha1": "7721a0c5116b0f6bb609957d48f108e5c153f199",
          "md5": "ee24c9662b34ef9397074fe79b6e23af"
        }
      ]
    }
  ]
}
