{
  "formatVersion": "1.1",
  "component": {
    "group": "com.alessiodp.libby.maven.resolver",
    "module": "libby-maven-resolver",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libby-maven-resolver-1.0.1.jar",
          "url": "libby-maven-resolver-1.0.1.jar",
          "size": 1263526,
          "sha512": "a75ec42fa0c2ecd0b2debc704e4005bdadc8325947c4224bdd86488e8b5b8b2422eca052c727e1c776a967758bb879031f97f39f508e08ad5ec376a1b0421c08",
          "sha256": "8cbe663dbd10d53152a66884aebbd73531b4eb9c0c451ec524b8748be3c34781",
          "sha1": "8a548f958571b2585f396fca19463847bb186e4b",
          "md5": "f7ec9a688b11878b28c850892e25f000"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-impl",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-nop",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "libby-maven-resolver-1.0.1.jar",
          "url": "libby-maven-resolver-1.0.1.jar",
          "size": 1263526,
          "sha512": "a75ec42fa0c2ecd0b2debc704e4005bdadc8325947c4224bdd86488e8b5b8b2422eca052c727e1c776a967758bb879031f97f39f508e08ad5ec376a1b0421c08",
          "sha256": "8cbe663dbd10d53152a66884aebbd73531b4eb9c0c451ec524b8748be3c34781",
          "sha1": "8a548f958571b2585f396fca19463847bb186e4b",
          "md5": "f7ec9a688b11878b28c850892e25f000"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libby-maven-resolver-1.0.1.jar",
          "url": "libby-maven-resolver-1.0.1.jar",
          "size": 1263526,
          "sha512": "a75ec42fa0c2ecd0b2debc704e4005bdadc8325947c4224bdd86488e8b5b8b2422eca052c727e1c776a967758bb879031f97f39f508e08ad5ec376a1b0421c08",
          "sha256": "8cbe663dbd10d53152a66884aebbd73531b4eb9c0c451ec524b8748be3c34781",
          "sha1": "8a548f958571b2585f396fca19463847bb186e4b",
          "md5": "f7ec9a688b11878b28c850892e25f000"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libby-maven-resolver-1.0.1-javadoc.jar",
          "url": "libby-maven-resolver-1.0.1-javadoc.jar",
          "size": 73492,
          "sha512": "e0c51008fdedc9ba5a8a2d04b669a25a4f027169124b6e892559d0a8ddb2591699edc23e5b3d532798c9b20c1c8ddce0c1b85428847d334468d971dd5804cbb5",
          "sha256": "550f0c12c6c449b92e3bdc9e1708eaa0806c8422984d50bffd23d5e5ca7ebc92",
          "sha1": "6d0922dfba90de3b7778fbf75cc89fd5a2eb7658",
          "md5": "49a16d56585ad848ee477c4b92e80e52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libby-maven-resolver-1.0.1-sources.jar",
          "url": "libby-maven-resolver-1.0.1-sources.jar",
          "size": 2908,
          "sha512": "83ee0bf32fa9ade3ece0ee34a847017217f79781c22035ced12b186ce246a1b41acd36b5bfa3828f420a5e0cf4868b006dd89d4824561cacdb7b846edfe77e75",
          "sha256": "6280b546a9c5dbf2c51f484356f5325177040b052c48b2d330a8214b9593e831",
          "sha1": "84ef86b8bf7afa9f5ef4c74f0443f2bc7a6d02f2",
          "md5": "e3109a2556b75c053be7f58dd5d0d189"
        }
      ]
    }
  ]
}
