{
  "formatVersion": "1.1",
  "component": {
    "group": "com.alessiodp.libby.maven.resolver",
    "module": "libby-maven-resolver",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "libby-maven-resolver-1.0.1.jar",
          "url": "libby-maven-resolver-1.0.1.jar",
          "size": 2209486,
          "sha512": "a264f583416b2da138ffdce096501d0e300414142560895d72ee4b9b355f95de96ae3801f85e0548c286a895412c8f72bcd4de756c45393bb2bf5a5e25b559eb",
          "sha256": "6900fa963a816b0f9817a20ed7f9268edf90633785f989b6d2360283a2c2d75e",
          "sha1": "3490af91d3478ec446d03a059eea181d388a5367",
          "md5": "1cf8e1b82fe4d8c33ef3f6543ccd03d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-impl",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.8.5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-nop",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "libby-maven-resolver-1.0.1.jar",
          "url": "libby-maven-resolver-1.0.1.jar",
          "size": 2209486,
          "sha512": "a264f583416b2da138ffdce096501d0e300414142560895d72ee4b9b355f95de96ae3801f85e0548c286a895412c8f72bcd4de756c45393bb2bf5a5e25b559eb",
          "sha256": "6900fa963a816b0f9817a20ed7f9268edf90633785f989b6d2360283a2c2d75e",
          "sha1": "3490af91d3478ec446d03a059eea181d388a5367",
          "md5": "1cf8e1b82fe4d8c33ef3f6543ccd03d5"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libby-maven-resolver-1.0.1.jar",
          "url": "libby-maven-resolver-1.0.1.jar",
          "size": 2209486,
          "sha512": "a264f583416b2da138ffdce096501d0e300414142560895d72ee4b9b355f95de96ae3801f85e0548c286a895412c8f72bcd4de756c45393bb2bf5a5e25b559eb",
          "sha256": "6900fa963a816b0f9817a20ed7f9268edf90633785f989b6d2360283a2c2d75e",
          "sha1": "3490af91d3478ec446d03a059eea181d388a5367",
          "md5": "1cf8e1b82fe4d8c33ef3f6543ccd03d5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libby-maven-resolver-1.0.1-javadoc.jar",
          "url": "libby-maven-resolver-1.0.1-javadoc.jar",
          "size": 73492,
          "sha512": "e0c51008fdedc9ba5a8a2d04b669a25a4f027169124b6e892559d0a8ddb2591699edc23e5b3d532798c9b20c1c8ddce0c1b85428847d334468d971dd5804cbb5",
          "sha256": "550f0c12c6c449b92e3bdc9e1708eaa0806c8422984d50bffd23d5e5ca7ebc92",
          "sha1": "6d0922dfba90de3b7778fbf75cc89fd5a2eb7658",
          "md5": "49a16d56585ad848ee477c4b92e80e52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "libby-maven-resolver-1.0.1-sources.jar",
          "url": "libby-maven-resolver-1.0.1-sources.jar",
          "size": 3014,
          "sha512": "0118cbdeec382232361fb67ffabeb8afdabe90f2760f7b44cc1808e1536e4e72e8b77036e7aa32b0f3cc5a652bbaee07b81c1384394482fee8309709f3af229d",
          "sha256": "8b3875d3fbe68c1d9499cb350742d02d47369a10d8140c46b7a8bfa281cd884c",
          "sha1": "d3969e171521b345cbc9395f3006259c1a4ea9c9",
          "md5": "6f22fe535ee612857baa9dcb7a8c6c0e"
        }
      ]
    }
  ]
}
