{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "admin",
    "version": "1.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.36.jar",
          "url": "admin-1.0.36.jar",
          "size": 42668,
          "sha512": "fd01e9e4ae6aa4254e2707f2ae5e873f834a9c68f28c1fea6117ab0f1c67e103498983c39097e824641a409e622505b12973943e536858d91fa1a0df8c555c0d",
          "sha256": "76c0719175bcfd9b0f253de61561bf4436fc3731e795ecf33bd3d41a91ed34da",
          "sha1": "0edc4e3f1d1189a7f8e75c7a6fdf922e31babded",
          "md5": "dd92643cea4afe4963ed3f7c46460a0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "admin-1.0.36.jar",
          "url": "admin-1.0.36.jar",
          "size": 42668,
          "sha512": "fd01e9e4ae6aa4254e2707f2ae5e873f834a9c68f28c1fea6117ab0f1c67e103498983c39097e824641a409e622505b12973943e536858d91fa1a0df8c555c0d",
          "sha256": "76c0719175bcfd9b0f253de61561bf4436fc3731e795ecf33bd3d41a91ed34da",
          "sha1": "0edc4e3f1d1189a7f8e75c7a6fdf922e31babded",
          "md5": "dd92643cea4afe4963ed3f7c46460a0e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.36-sources.jar",
          "url": "admin-1.0.36-sources.jar",
          "size": 14919,
          "sha512": "069c79310e3961e7fe00398040db085e69a0a28d5f03685ca0083635faa4fed7ea8a524c4babc11089073032ec1cf232da2e7e01537192d987767db124db324d",
          "sha256": "f905528e4504dba45876aa29626615be06100f9efd35692cd24c6649b33716a6",
          "sha1": "b7f055d40667848c7bfcee96d5a1f88ed7eb5611",
          "md5": "7570f5ae962f0e25bea0768ad5292ff1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.36-javadoc.jar",
          "url": "admin-1.0.36-javadoc.jar",
          "size": 148187,
          "sha512": "97df2007a1d1a05a3d9bfe95cc37abffeb09793870f6c229400c18dbd6fb001042446e55bcc86cc9a114878f334ab6b6c37afe7bc97fbdee3f461da8ad545711",
          "sha256": "d8155402767694fc4e9374ccb87792ee22a7a9f27a3b8876b5a1f2685f75a9ee",
          "sha1": "b3ea7a57d537a9717240406e51f03781b1ccf080",
          "md5": "fe67b8cf3ca6260baa980e107f05edf8"
        }
      ]
    }
  ]
}
