{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "admin",
    "version": "1.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.36.jar",
          "url": "admin-1.0.36.jar",
          "size": 42656,
          "sha512": "129dd0f93db50cbd096ebbaf0bcab1104f06e8b416332f601d41ad79bbd0fc708a743f6e779beccf43c6dc6d36dab5dac954ae65f5ff324e34f71f61e4d69827",
          "sha256": "b6db02c02485f934d66325a972713547c405823b18d8021e597c932ad57f764a",
          "sha1": "b2177b896bdba4f8fa561bcf4edd889b4bb2c65c",
          "md5": "a71baad3a40756c3329800ad29d4bdc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "admin-1.0.36.jar",
          "url": "admin-1.0.36.jar",
          "size": 42656,
          "sha512": "129dd0f93db50cbd096ebbaf0bcab1104f06e8b416332f601d41ad79bbd0fc708a743f6e779beccf43c6dc6d36dab5dac954ae65f5ff324e34f71f61e4d69827",
          "sha256": "b6db02c02485f934d66325a972713547c405823b18d8021e597c932ad57f764a",
          "sha1": "b2177b896bdba4f8fa561bcf4edd889b4bb2c65c",
          "md5": "a71baad3a40756c3329800ad29d4bdc0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.36-sources.jar",
          "url": "admin-1.0.36-sources.jar",
          "size": 14919,
          "sha512": "35e2fc25cab1266e726d1861f385225ebd7c39493e164b2614940855544740c75419aabbd127133f643427853512e6d375578bddccfcd530f756ac11c227909b",
          "sha256": "9590bfafc32fdd7db4cf396f89c836a656ffbc504f67dd4b76ca0bce04ddc5a6",
          "sha1": "a64444053bb2082cf356c3083e9205f88da9aba3",
          "md5": "046a88b18f0a7f45c05ce23a2dbe1eb1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.36-javadoc.jar",
          "url": "admin-1.0.36-javadoc.jar",
          "size": 148187,
          "sha512": "57365d399d5e1ddfe9377c291ee2aa329565ccf73acb47d1a0326bdb10ae4f9cce3b2021e47b51427237df8d65ece9e12da80d749e7c7ba812980e55bd78bedf",
          "sha256": "76d3e0d39391a4a36f0498b5933f27562da470f9d142023bacb0abd412ad5163",
          "sha1": "1153d73594c1c76dd1a1ada600b4cd99f8d8c0e1",
          "md5": "c6f57dbf6f79d9d3dd80749e5b65caad"
        }
      ]
    }
  ]
}
