{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.controllers",
    "module": "callee",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callee-1.0.17.jar",
          "url": "callee-1.0.17.jar",
          "size": 261,
          "sha512": "f0a5ea4b16be539c63eefbe45e4c51514571ac4167bb89d2fa3fc59a903bbefe1617a6591bdef795a6a6cb6a1960685fb6bcc88a7e1bceaa12b11061857a2763",
          "sha256": "def6679f4b97fbcbf07e2de4ae011d1f3e25038f5ce30604c6b3c08bb3468be6",
          "sha1": "f3a54dbfe571fe71958f5afeaaf8e994e90f07f0",
          "md5": "634048398cebefe3bdc2182039a3d866"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.17"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "callee-1.0.17.jar",
          "url": "callee-1.0.17.jar",
          "size": 261,
          "sha512": "f0a5ea4b16be539c63eefbe45e4c51514571ac4167bb89d2fa3fc59a903bbefe1617a6591bdef795a6a6cb6a1960685fb6bcc88a7e1bceaa12b11061857a2763",
          "sha256": "def6679f4b97fbcbf07e2de4ae011d1f3e25038f5ce30604c6b3c08bb3468be6",
          "sha1": "f3a54dbfe571fe71958f5afeaaf8e994e90f07f0",
          "md5": "634048398cebefe3bdc2182039a3d866"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.17-sources.jar",
          "url": "callee-1.0.17-sources.jar",
          "size": 261,
          "sha512": "f0a5ea4b16be539c63eefbe45e4c51514571ac4167bb89d2fa3fc59a903bbefe1617a6591bdef795a6a6cb6a1960685fb6bcc88a7e1bceaa12b11061857a2763",
          "sha256": "def6679f4b97fbcbf07e2de4ae011d1f3e25038f5ce30604c6b3c08bb3468be6",
          "sha1": "f3a54dbfe571fe71958f5afeaaf8e994e90f07f0",
          "md5": "634048398cebefe3bdc2182039a3d866"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.17-javadoc.jar",
          "url": "callee-1.0.17-javadoc.jar",
          "size": 261,
          "sha512": "f0a5ea4b16be539c63eefbe45e4c51514571ac4167bb89d2fa3fc59a903bbefe1617a6591bdef795a6a6cb6a1960685fb6bcc88a7e1bceaa12b11061857a2763",
          "sha256": "def6679f4b97fbcbf07e2de4ae011d1f3e25038f5ce30604c6b3c08bb3468be6",
          "sha1": "f3a54dbfe571fe71958f5afeaaf8e994e90f07f0",
          "md5": "634048398cebefe3bdc2182039a3d866"
        }
      ]
    }
  ]
}
