{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.controllers",
    "module": "callee",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callee-1.0.17.jar",
          "url": "callee-1.0.17.jar",
          "size": 261,
          "sha512": "76329083d61e2703481d47d622cc3febe9ced6a490f1d3656f95943083344c7c961c5ae526cef3a7423a859e00f6ef0fa12bb1e67d4394d66ccf60e8cc3a4c47",
          "sha256": "c99d2949d6ec623c234b37eeaee876616a87bbaeda9e1337dd0e94661543b2d3",
          "sha1": "a02347941b2f18e8c2e9311cf086f2a7556c78c5",
          "md5": "6ac60354c54d9b13d1a23cb847cac33c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.17"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "callee-1.0.17.jar",
          "url": "callee-1.0.17.jar",
          "size": 261,
          "sha512": "76329083d61e2703481d47d622cc3febe9ced6a490f1d3656f95943083344c7c961c5ae526cef3a7423a859e00f6ef0fa12bb1e67d4394d66ccf60e8cc3a4c47",
          "sha256": "c99d2949d6ec623c234b37eeaee876616a87bbaeda9e1337dd0e94661543b2d3",
          "sha1": "a02347941b2f18e8c2e9311cf086f2a7556c78c5",
          "md5": "6ac60354c54d9b13d1a23cb847cac33c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.17-sources.jar",
          "url": "callee-1.0.17-sources.jar",
          "size": 261,
          "sha512": "76329083d61e2703481d47d622cc3febe9ced6a490f1d3656f95943083344c7c961c5ae526cef3a7423a859e00f6ef0fa12bb1e67d4394d66ccf60e8cc3a4c47",
          "sha256": "c99d2949d6ec623c234b37eeaee876616a87bbaeda9e1337dd0e94661543b2d3",
          "sha1": "a02347941b2f18e8c2e9311cf086f2a7556c78c5",
          "md5": "6ac60354c54d9b13d1a23cb847cac33c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.17-javadoc.jar",
          "url": "callee-1.0.17-javadoc.jar",
          "size": 261,
          "sha512": "76329083d61e2703481d47d622cc3febe9ced6a490f1d3656f95943083344c7c961c5ae526cef3a7423a859e00f6ef0fa12bb1e67d4394d66ccf60e8cc3a4c47",
          "sha256": "c99d2949d6ec623c234b37eeaee876616a87bbaeda9e1337dd0e94661543b2d3",
          "sha1": "a02347941b2f18e8c2e9311cf086f2a7556c78c5",
          "md5": "6ac60354c54d9b13d1a23cb847cac33c"
        }
      ]
    }
  ]
}
