{
  "formatVersion": "1.1",
  "component": {
    "group": "mod.chiselsandbits",
    "module": "chiselsandbits",
    "version": "1.2.0-beta.1+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "20.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "chiselsandbits-1.2.0-beta.1+1.20.4.jar",
          "url": "chiselsandbits-1.2.0-beta.1+1.20.4.jar",
          "size": 890268,
          "sha512": "385174e663e19443808476bf73c66d2709b2653c226fa4bf43b8c9a131f50fd23227a885d4427aa4079a4a9b33f2a9a40861165d6049b08f4b8fa098e4882304",
          "sha256": "f5194ad0efb102244a971c533402ce2a4536c374514a8336471315b0bea17d4c",
          "sha1": "c3a2a7c2e9941ddf970d8a17d6ac06c0707eae16",
          "md5": "a2a5d863329787fd64c48346e85c26a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "fuzs.forgeconfigapiport",
          "module": "forgeconfigapiport-fabric",
          "version": {
            "requires": "20.4.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.1+1.20.4"
          }
        },
        {
          "group": "com.jamieswhiteshirt",
          "module": "reach-entity-attributes",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.communi-suggestu.saecularia-caudices",
          "module": "saecularia-caudices-fabric",
          "version": {
            "requires": "1.0.39"
          }
        },
        {
          "group": "io.github.feltmc",
          "module": "fabricated-forge-caps",
          "version": {
            "requires": "0.1-1.20.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "modernkeybinding",
          "version": {
            "requires": "1.20.4-1.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "chiselsandbits-1.2.0-beta.1+1.20.4.jar",
          "url": "chiselsandbits-1.2.0-beta.1+1.20.4.jar",
          "size": 890268,
          "sha512": "385174e663e19443808476bf73c66d2709b2653c226fa4bf43b8c9a131f50fd23227a885d4427aa4079a4a9b33f2a9a40861165d6049b08f4b8fa098e4882304",
          "sha256": "f5194ad0efb102244a971c533402ce2a4536c374514a8336471315b0bea17d4c",
          "sha1": "c3a2a7c2e9941ddf970d8a17d6ac06c0707eae16",
          "md5": "a2a5d863329787fd64c48346e85c26a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chiselsandbits-1.2.0-beta.1+1.20.4-sources.jar",
          "url": "chiselsandbits-1.2.0-beta.1+1.20.4-sources.jar",
          "size": 517783,
          "sha512": "c3bf60cc097c92e5fde94b98e424a3c2a941a4f209c8520fbcb665a40ac2668f48fe2c44c8a44d9658561defd4773a7e8a000f27079daa83f74e785e3d43dd10",
          "sha256": "2922aff71ac57a9c6725dd049faaa51812514821ee55d60a5383bfed2bdd1203",
          "sha1": "4b91fe5c544d1dc87c8a5159002c44541ec7010d",
          "md5": "c11c68346b1ae754f36eef5ddc9d23c3"
        }
      ]
    }
  ]
}
