{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.views",
    "module": "admin",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.17.jar",
          "url": "admin-1.0.17.jar",
          "size": 261,
          "sha512": "e9b817f76d94d5cea3baddebde4c776383b8839479b790d0b3c22474231d5d76eef8c1c0f4c3201ea056dacdd081a1c368b715188c9470b32987b7e185f2900e",
          "sha256": "7e868412a33f2eb5a9d8e57bb957f8a2ede79f7c55a573f77ccaa29f0a59d5c5",
          "sha1": "4515b2edfcc99088f85d7c9508423aed89bb256a",
          "md5": "20642ba36cf9b71dd69eb53b5c8f2044"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.17.jar",
          "url": "admin-1.0.17.jar",
          "size": 261,
          "sha512": "e9b817f76d94d5cea3baddebde4c776383b8839479b790d0b3c22474231d5d76eef8c1c0f4c3201ea056dacdd081a1c368b715188c9470b32987b7e185f2900e",
          "sha256": "7e868412a33f2eb5a9d8e57bb957f8a2ede79f7c55a573f77ccaa29f0a59d5c5",
          "sha1": "4515b2edfcc99088f85d7c9508423aed89bb256a",
          "md5": "20642ba36cf9b71dd69eb53b5c8f2044"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.17-sources.jar",
          "url": "admin-1.0.17-sources.jar",
          "size": 999,
          "sha512": "5771d22a9d92eff37a853434a628933f615d117d59a433414754a178b3f5c025414fbfa231471ee2284f23ba7e45d8a3803800f877af00d6126f858591702b89",
          "sha256": "3643f94d6bc16e2557c7b1a4a5db439b173332cbcaa4c9a0ef5f2f0bc0abfa00",
          "sha1": "5a25214a55554cd2ce1316e9596c13cb32a4b975",
          "md5": "fa407e057a3ab2f9c0ba90a56d47da34"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.17-javadoc.jar",
          "url": "admin-1.0.17-javadoc.jar",
          "size": 261,
          "sha512": "e9b817f76d94d5cea3baddebde4c776383b8839479b790d0b3c22474231d5d76eef8c1c0f4c3201ea056dacdd081a1c368b715188c9470b32987b7e185f2900e",
          "sha256": "7e868412a33f2eb5a9d8e57bb957f8a2ede79f7c55a573f77ccaa29f0a59d5c5",
          "sha1": "4515b2edfcc99088f85d7c9508423aed89bb256a",
          "md5": "20642ba36cf9b71dd69eb53b5c8f2044"
        }
      ]
    }
  ]
}
