{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "config",
    "version": "1.3.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-1.3.9-SNAPSHOT.jar",
          "url": "config-1.3.9-SNAPSHOT.jar",
          "size": 8215,
          "sha512": "05fd0ef936641920b63f0214a2d01a475eca7d957ab4d2ebed4398dbe1bc70a932647780c192ab7f88f17dac0251e14f898aab3f425b28c1b5d35dbea0a44092",
          "sha256": "9368274dd5402bd1a3a7dc672deb9679a4031ebf4e9575209a3b3573c6180d92",
          "sha1": "2ddecc0825e95217e196f5d17b03ab9e77fe9daa",
          "md5": "09a8b29fe74e0d737d09442680bf4945"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.43"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.43"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.43"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.43"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.43"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.43"
          }
        }
      ],
      "files": [
        {
          "name": "config-1.3.9-SNAPSHOT.jar",
          "url": "config-1.3.9-SNAPSHOT.jar",
          "size": 8215,
          "sha512": "05fd0ef936641920b63f0214a2d01a475eca7d957ab4d2ebed4398dbe1bc70a932647780c192ab7f88f17dac0251e14f898aab3f425b28c1b5d35dbea0a44092",
          "sha256": "9368274dd5402bd1a3a7dc672deb9679a4031ebf4e9575209a3b3573c6180d92",
          "sha1": "2ddecc0825e95217e196f5d17b03ab9e77fe9daa",
          "md5": "09a8b29fe74e0d737d09442680bf4945"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.9-SNAPSHOT-sources.jar",
          "url": "config-1.3.9-SNAPSHOT-sources.jar",
          "size": 4221,
          "sha512": "104c77f53b963c8733b1fde76df36f8a60fe0508b97172b16daff62d4b9e3176d13262e6cf2d203263ae0c5a3d6b0945fe44dc09c739eda0518201245ffc0f96",
          "sha256": "368404b5af066b70f8a4240f19b2f3e6da2ea8825d4760064462ddad61a721f1",
          "sha1": "079b0b6a5ab43fc2b592dcb5f12c86e4d251205d",
          "md5": "2d64dc22b203cce87ad7877ca2f3bb64"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.9-SNAPSHOT-javadoc.jar",
          "url": "config-1.3.9-SNAPSHOT-javadoc.jar",
          "size": 45747,
          "sha512": "bf5467bccbee5f9dc35acdc029be30ae720e51b1d31b2faca8f2a2eab462653a604603907bd2558ce2eff15ba7be0fa45d0e78d4650cf06b016112ca3abea9f4",
          "sha256": "cadc774a7561228f554c745f4083048041b8af1c684c1b28e2e1ba09ff5c93f9",
          "sha1": "d9fa9507effd6e5282fd6ccfce1919ec7a7ed49d",
          "md5": "7674b97161ae5c3c323af8bb55f3c54b"
        }
      ]
    }
  ]
}
