{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "screen-adapter",
    "version": "1.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "screen-adapter-1.3.0-SNAPSHOT.jar",
          "url": "screen-adapter-1.3.0-SNAPSHOT.jar",
          "size": 4163,
          "sha512": "5b599693afcac0424cf6e8dfb4839b064b2cb385a136d2105b290ea7c91b435df68caa701710e2922c6ea31d3c8c0c6fb7d4eab506c6ef691d6465b3fdeccfc3",
          "sha256": "d628320f778f58f457878e6aaeaf940dce74c50c51499a11da864c03aefa8fc0",
          "sha1": "f0e4926bb0ac644651cc909a9a7c43805d73645c",
          "md5": "886cbed57ce5bfc51dc7cf34a836e1d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.29"
          }
        }
      ],
      "files": [
        {
          "name": "screen-adapter-1.3.0-SNAPSHOT.jar",
          "url": "screen-adapter-1.3.0-SNAPSHOT.jar",
          "size": 4163,
          "sha512": "5b599693afcac0424cf6e8dfb4839b064b2cb385a136d2105b290ea7c91b435df68caa701710e2922c6ea31d3c8c0c6fb7d4eab506c6ef691d6465b3fdeccfc3",
          "sha256": "d628320f778f58f457878e6aaeaf940dce74c50c51499a11da864c03aefa8fc0",
          "sha1": "f0e4926bb0ac644651cc909a9a7c43805d73645c",
          "md5": "886cbed57ce5bfc51dc7cf34a836e1d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen-adapter-1.3.0-SNAPSHOT-sources.jar",
          "url": "screen-adapter-1.3.0-SNAPSHOT-sources.jar",
          "size": 2561,
          "sha512": "954283676eddb1a40e0d342eedb0865055a378b958399b0914a439965ed443dd53b9cd2a59ec43e058880fc8e21311b57b4895062e55403263ccc6e1822b3a53",
          "sha256": "625570df5004c065a570988f346609e24427e6f6c40669f5c7c6668908e94cfa",
          "sha1": "b7a7920d408370a3915f541074d761660890e906",
          "md5": "2ea9aa40d3b3e31b50d917bb35843e02"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "screen-adapter-1.3.0-SNAPSHOT-javadoc.jar",
          "url": "screen-adapter-1.3.0-SNAPSHOT-javadoc.jar",
          "size": 27823,
          "sha512": "371f1d434612060d6e794c37f06889c241fc7a952dfc44daf68d6ab2391fe1b497c2eff41ba62d478c7f291fdab723e34384d88781c9a3d4e3243c09cb915168",
          "sha256": "878a69613985caa2129317a48ea56b9c815068704e582b8a6ee4f97b3e152ad2",
          "sha1": "86c3946d94d2d09aba8ca0a6cc5730f604cf7d7e",
          "md5": "c933a2021eb0fd95daf6d587a65c3b7c"
        }
      ]
    }
  ]
}
