{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "accessor",
    "version": "1.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "accessor-1.0.36.jar",
          "url": "accessor-1.0.36.jar",
          "size": 8792,
          "sha512": "097b844de19780381172db30665dd5a4f0edf4b092f846cb57ebae539e6cca759e863e38dfa59816537fa977de8fd24edbc3ec3f88607814de5094a921dde3d4",
          "sha256": "791aa31d6d415b46b1b4f8d94aae484b338d1b027dd2895c232cdb4a0ae3efef",
          "sha1": "f69c53c194367b3a5d3345e7d25d8e7954de87f6",
          "md5": "c368ad6331fe639924fc10e03894120f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessor-1.0.36.jar",
          "url": "accessor-1.0.36.jar",
          "size": 8792,
          "sha512": "097b844de19780381172db30665dd5a4f0edf4b092f846cb57ebae539e6cca759e863e38dfa59816537fa977de8fd24edbc3ec3f88607814de5094a921dde3d4",
          "sha256": "791aa31d6d415b46b1b4f8d94aae484b338d1b027dd2895c232cdb4a0ae3efef",
          "sha1": "f69c53c194367b3a5d3345e7d25d8e7954de87f6",
          "md5": "c368ad6331fe639924fc10e03894120f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessor-1.0.36-sources.jar",
          "url": "accessor-1.0.36-sources.jar",
          "size": 4219,
          "sha512": "e4eea1cc2135592c01e3ff2e70928549d5cd84cd52950b197b9b8e372a2d0d6e67cb6cb3635abfc8500eac1aa003289d41f5b2ee2a9a09077948bdb5a0121a28",
          "sha256": "899be6ba339710e6e7205e9be440cd43c174a5aecfc41419191f0f86c5dbac03",
          "sha1": "4ac55f2832888b68b7199937885d92dcc58d695c",
          "md5": "f5116eccf9413fb2d85d38c9016d4249"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessor-1.0.36-javadoc.jar",
          "url": "accessor-1.0.36-javadoc.jar",
          "size": 47516,
          "sha512": "8bcbf6b9db0b91a3f66f18c6563567f742949eb7444b84235104c7c18f584b067f8d9a6ca0fa8f9aba46ad134082b190d47e79ded41eb4a01bcc4dd7180376d8",
          "sha256": "0530382f56aa4e57561efdce9a8501d13efd5a120e322a619aaaf3707ac70940",
          "sha1": "780ba3de82d72cf9ff900204563f417c765b6929",
          "md5": "7f93bbcfab82682ac4e34f8bfd031651"
        }
      ]
    }
  ]
}
