{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "sound-adapter",
    "version": "1.3.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sound-adapter-1.3.5-SNAPSHOT.jar",
          "url": "sound-adapter-1.3.5-SNAPSHOT.jar",
          "size": 4076,
          "sha512": "11ccf7679dc878b5ff2f3ec3b56f05ef6931ffc09e095f291476739673f91107f6fc2744e465cdcec38821bc7adbd74295f0b00a6ec9bd78bc363dfafa02578e",
          "sha256": "94dd043a623454ae7233b5369a6554309e4c7372c12bd23c517c135402a5b06a",
          "sha1": "f8907b915e45bf943232465b4f2ce6d65e50b08e",
          "md5": "256380cc4e8a12407bb678bbf4e87751"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.33"
          }
        }
      ],
      "files": [
        {
          "name": "sound-adapter-1.3.5-SNAPSHOT.jar",
          "url": "sound-adapter-1.3.5-SNAPSHOT.jar",
          "size": 4076,
          "sha512": "11ccf7679dc878b5ff2f3ec3b56f05ef6931ffc09e095f291476739673f91107f6fc2744e465cdcec38821bc7adbd74295f0b00a6ec9bd78bc363dfafa02578e",
          "sha256": "94dd043a623454ae7233b5369a6554309e4c7372c12bd23c517c135402a5b06a",
          "sha1": "f8907b915e45bf943232465b4f2ce6d65e50b08e",
          "md5": "256380cc4e8a12407bb678bbf4e87751"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sound-adapter-1.3.5-SNAPSHOT-sources.jar",
          "url": "sound-adapter-1.3.5-SNAPSHOT-sources.jar",
          "size": 2905,
          "sha512": "86b144c492c817c0b0b4bcf0b37744fcccb87e9b01dec3d56fc5af298d12c6e2414e299d4a390daf8c5fdfe877cf1273a06b4d5b8c524fca1dc4705db03fc209",
          "sha256": "a9bbf89371228cbdcadd301f35799442880ca6072f91f9de5421514a284ceba4",
          "sha1": "14a1f4d2929398730e9958119918913a2c10b973",
          "md5": "4899668309f834a8a7442b6a2ed5a9a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sound-adapter-1.3.5-SNAPSHOT-javadoc.jar",
          "url": "sound-adapter-1.3.5-SNAPSHOT-javadoc.jar",
          "size": 28548,
          "sha512": "73aa7e18a45c9853a9dc659aed318111a488b4efd77572dfa241c6ba1355cd16f84a53f2e4f8bad30803f1cade1500bfc8e316bda0af244736e74795f1c7a270",
          "sha256": "896101b88487e2a32feaa3bdea7aa433a1ac4a089134c5dd64402c469f35452d",
          "sha1": "f462678672893cc17fe04a4845a3545e396e7702",
          "md5": "98955d645e8e79d4e495a6922d4edf19"
        }
      ]
    }
  ]
}
