{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "policy-impl",
    "version": "1.3.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "policy-impl-1.3.5-SNAPSHOT.jar",
          "url": "policy-impl-1.3.5-SNAPSHOT.jar",
          "size": 55403,
          "sha512": "e631b81bde5173a4c9c690b3b8246ac492e083a0ccc5acca0b6488711021ac3b0309f8d78e63a3e3e4c3d1a1d74298024d08cdbdcd4d85f098d97dff07d01c32",
          "sha256": "e291a5fb7a34ad777a8f207066f4dd68ede2d7e107a5653866b5a326ed3fcc30",
          "sha1": "93bdbe6ab8f0106104dccc01945444ddeadee4fe",
          "md5": "6a3e3723d0eb23dee1efdde5b61557fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "policy-impl-1.3.5-SNAPSHOT.jar",
          "url": "policy-impl-1.3.5-SNAPSHOT.jar",
          "size": 55403,
          "sha512": "e631b81bde5173a4c9c690b3b8246ac492e083a0ccc5acca0b6488711021ac3b0309f8d78e63a3e3e4c3d1a1d74298024d08cdbdcd4d85f098d97dff07d01c32",
          "sha256": "e291a5fb7a34ad777a8f207066f4dd68ede2d7e107a5653866b5a326ed3fcc30",
          "sha1": "93bdbe6ab8f0106104dccc01945444ddeadee4fe",
          "md5": "6a3e3723d0eb23dee1efdde5b61557fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "policy-impl-1.3.5-SNAPSHOT-sources.jar",
          "url": "policy-impl-1.3.5-SNAPSHOT-sources.jar",
          "size": 24783,
          "sha512": "34ca882caf0720c063fd1bd019540692bc56eeb8446da1faf40e97b4ae7fdc741e1dea091fc2cedaffbc88cb6fa59b8ec7669147218d25ef07600b35dbd8c9e5",
          "sha256": "8599a0ecbe5c491bcbe2d0f759b10de9fc7433cf9025bcc32b4bde1c2df986ef",
          "sha1": "9e89c2b094b1eafb7324b0fa847cf94390998e93",
          "md5": "f9a57044ef16943c1100b36f15583c67"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "policy-impl-1.3.5-SNAPSHOT-javadoc.jar",
          "url": "policy-impl-1.3.5-SNAPSHOT-javadoc.jar",
          "size": 195106,
          "sha512": "6a173b9dbc44ca90f5fa024c798bf44b28f5398639c8db59ee7bf62a410abc656c17594e9858d9c1133836815ce90d55ad38b7be2a8b2bfaa90f924866cdaa1c",
          "sha256": "2686d7f5a4563f21111d6d7434f6ad8bd83e8a88de03c74d6ca5f345c9e344fe",
          "sha1": "97a121b9e30edbe74d7a6382b47b28679150dad5",
          "md5": "3930afc0b71e0e73035e7da10410a3ed"
        }
      ]
    }
  ]
}
