{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "caller",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "caller-1.0.17.jar",
          "url": "caller-1.0.17.jar",
          "size": 261,
          "sha512": "f0a5ea4b16be539c63eefbe45e4c51514571ac4167bb89d2fa3fc59a903bbefe1617a6591bdef795a6a6cb6a1960685fb6bcc88a7e1bceaa12b11061857a2763",
          "sha256": "def6679f4b97fbcbf07e2de4ae011d1f3e25038f5ce30604c6b3c08bb3468be6",
          "sha1": "f3a54dbfe571fe71958f5afeaaf8e994e90f07f0",
          "md5": "634048398cebefe3bdc2182039a3d866"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caller-1.0.17.jar",
          "url": "caller-1.0.17.jar",
          "size": 261,
          "sha512": "f0a5ea4b16be539c63eefbe45e4c51514571ac4167bb89d2fa3fc59a903bbefe1617a6591bdef795a6a6cb6a1960685fb6bcc88a7e1bceaa12b11061857a2763",
          "sha256": "def6679f4b97fbcbf07e2de4ae011d1f3e25038f5ce30604c6b3c08bb3468be6",
          "sha1": "f3a54dbfe571fe71958f5afeaaf8e994e90f07f0",
          "md5": "634048398cebefe3bdc2182039a3d866"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caller-1.0.17-sources.jar",
          "url": "caller-1.0.17-sources.jar",
          "size": 1029,
          "sha512": "6958d4524791db23d53b751bb6a1d19448cd54f57ee2b16be455df0786f9d036d5a6d48dcc8f6fe1f8156af0ce3362bc9f04f04e3d149561eac9a91c9ab62488",
          "sha256": "24f6182f3f090fc8b8241907af1e484642a71321def1699e07caefa1c2baa1f6",
          "sha1": "7f2598d96c14bee4a6223a8591ad7eb323ea1bc1",
          "md5": "1b78d1a795bfc4aba5d887e080269040"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caller-1.0.17-javadoc.jar",
          "url": "caller-1.0.17-javadoc.jar",
          "size": 261,
          "sha512": "f60473a1f1b32afe85c44ec9e3753ae8a5efe304e6b9b6458934468b2674c4b8e02d23b57283efd95c67c0fbe5c5f4ac8c2b0a1a4c35ba2dcdc7993944034c0c",
          "sha256": "16308f2ac639905725355351a1fea448510b305ab07214c83b34a14643bdbfb4",
          "sha1": "e60e278c195270361c1da51e24eece69dea52048",
          "md5": "bbef70edf166bce784802314e46ad1fa"
        }
      ]
    }
  ]
}
