{
  "formatVersion": "1.1",
  "component": {
    "group": "net.indiespot.media",
    "module": "medialib-lwjgl3",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "medialib-lwjgl3-1.0.1-SNAPSHOT.jar",
          "url": "medialib-lwjgl3-1.0.1-SNAPSHOT.jar",
          "size": 726413,
          "sha512": "6f386361327caba01f3f938da4ca08ddfb210134240e7c784b94de21df6a795332df3a949eb2bd74c86f857ec99aa834b7f3a59e58315c7c9173c3c2e187ec19",
          "sha256": "460544fe9d82e7b9e19d3b95575ea7f5f11574b4c1a3e101666bbaa6e05bbbb4",
          "sha1": "1c889e83ad875e7239cf2ed906da5ba5763448c4",
          "md5": "6d9cd7c5eb7d632d838b82035f0fc368"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "medialib-lwjgl3-1.0.1-SNAPSHOT.jar",
          "url": "medialib-lwjgl3-1.0.1-SNAPSHOT.jar",
          "size": 726413,
          "sha512": "6f386361327caba01f3f938da4ca08ddfb210134240e7c784b94de21df6a795332df3a949eb2bd74c86f857ec99aa834b7f3a59e58315c7c9173c3c2e187ec19",
          "sha256": "460544fe9d82e7b9e19d3b95575ea7f5f11574b4c1a3e101666bbaa6e05bbbb4",
          "sha1": "1c889e83ad875e7239cf2ed906da5ba5763448c4",
          "md5": "6d9cd7c5eb7d632d838b82035f0fc368"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "medialib-lwjgl3-1.0.1-SNAPSHOT-sources.jar",
          "url": "medialib-lwjgl3-1.0.1-SNAPSHOT-sources.jar",
          "size": 349406,
          "sha512": "15d6b4eadd0ed562589210bfda4c1d6095b94571ea07921746f1aef605339c2ff97dc57d5f6f0b3c5a9a4ade119fcb98fd15bd5904a6e8d0ae7e58ec3ba26a32",
          "sha256": "b7fa7b49b6d033ddd9ae4cf1e750c24ab395fcd5be085d4eae42f8797e8d3ffc",
          "sha1": "90d4193e6c477cb1f22c8f78975a55a4febec274",
          "md5": "1d9605f235d617fafa6231824d35e746"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "medialib-lwjgl3-1.0.1-SNAPSHOT-javadoc.jar",
          "url": "medialib-lwjgl3-1.0.1-SNAPSHOT-javadoc.jar",
          "size": 1109169,
          "sha512": "01729c3811fe70a4abdd46193b632368375b2cf9b7a7e10a9c89441e4e579d5c02195f2fdd84c574ae051762b84513551f50ac0bf5b0302e93845ecefc618867",
          "sha256": "7601a654488eedcc5076d7346ed6d21b5336b01a58248b0badd6e4983f165b8c",
          "sha1": "0dc1119d7b155508b1808387663829e82bc5d166",
          "md5": "a87d40a776670997ed142342be1b3d51"
        }
      ]
    }
  ]
}
