{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.elenterius.fabiko",
    "module": "core",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.1.jar",
          "url": "core-0.0.1.jar",
          "size": 31600,
          "sha512": "5d67014c833421eabce73edc9061c06c2de5414e1ebf59b29bcda199df4ec526bfa43cfbf3959e113fae3961ea5a2fd83fbb8637bda40a74f03742b4d5d2e502",
          "sha256": "cc546dd08aa8b8a1575f3d147c79408feefe7e4d194a4d8805edfe2b0bcdc2d1",
          "sha1": "1aaa9e43bb397b8c42d17ce7825d1089b06d540e",
          "md5": "82ed0275b18a1b63edae279b72934240"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.7"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.1.jar",
          "url": "core-0.0.1.jar",
          "size": 31600,
          "sha512": "5d67014c833421eabce73edc9061c06c2de5414e1ebf59b29bcda199df4ec526bfa43cfbf3959e113fae3961ea5a2fd83fbb8637bda40a74f03742b4d5d2e502",
          "sha256": "cc546dd08aa8b8a1575f3d147c79408feefe7e4d194a4d8805edfe2b0bcdc2d1",
          "sha1": "1aaa9e43bb397b8c42d17ce7825d1089b06d540e",
          "md5": "82ed0275b18a1b63edae279b72934240"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-0.0.1-sources.jar",
          "url": "core-0.0.1-sources.jar",
          "size": 15839,
          "sha512": "1f7053a7e60a498e475273e1d5cd33051c891f3baf6f5e69c30ae8fa891de6e071568d95373c285aa284ce705262a3816940c8509cafc4f24d2bb49d9e10e331",
          "sha256": "921fd167d8c645e326378ea715830e808fcb27eb9f1ca6010d7a37c8bd78ca86",
          "sha1": "a35c49d8ba231c7bd349db862364c214cc2deaa6",
          "md5": "0014063058ed4488a3026e2abd061d6b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-0.0.1-javadoc.jar",
          "url": "core-0.0.1-javadoc.jar",
          "size": 138177,
          "sha512": "1908ddfdbed6b8a23bff6c79cfa7e5a2e082a8305916af0aeffe422d79d024bd94bca96ffad123b02dc2e5853551ebdf3396e811fa838d39349bef913c4ffa39",
          "sha256": "34b6d5b2cc01a6488c2466e9d270f23ec4914f8c571ef1f8d377a45ccbbab688",
          "sha1": "644f8d51f7ca30830989e4a969f643fcbd323f16",
          "md5": "31662c19e80cf04397dd15586f836af3"
        }
      ]
    }
  ]
}
