{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.datagateways",
    "module": "datagateways",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "datagateways-1.0.17.jar",
          "url": "datagateways-1.0.17.jar",
          "size": 261,
          "sha512": "8ce523d9e797763ad6ef3d137246c7f06ee33b46763a543cd3674a26bf37ce0d7e8f8def0123f36cf87786387f1f221ccfb5b30ba84ba343edf99cf87eca4c66",
          "sha256": "db6261f23b2ef27883fab9312f6f80ed6d7c178a69cbc649cf254f72354b8b7c",
          "sha1": "26b455d61904a87db65fbcdd5ee1cf622ae6fb55",
          "md5": "1f4ff8ee1a9672e5f20e48c92ee43930"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.17.jar",
          "url": "datagateways-1.0.17.jar",
          "size": 261,
          "sha512": "8ce523d9e797763ad6ef3d137246c7f06ee33b46763a543cd3674a26bf37ce0d7e8f8def0123f36cf87786387f1f221ccfb5b30ba84ba343edf99cf87eca4c66",
          "sha256": "db6261f23b2ef27883fab9312f6f80ed6d7c178a69cbc649cf254f72354b8b7c",
          "sha1": "26b455d61904a87db65fbcdd5ee1cf622ae6fb55",
          "md5": "1f4ff8ee1a9672e5f20e48c92ee43930"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.17-sources.jar",
          "url": "datagateways-1.0.17-sources.jar",
          "size": 261,
          "sha512": "8ce523d9e797763ad6ef3d137246c7f06ee33b46763a543cd3674a26bf37ce0d7e8f8def0123f36cf87786387f1f221ccfb5b30ba84ba343edf99cf87eca4c66",
          "sha256": "db6261f23b2ef27883fab9312f6f80ed6d7c178a69cbc649cf254f72354b8b7c",
          "sha1": "26b455d61904a87db65fbcdd5ee1cf622ae6fb55",
          "md5": "1f4ff8ee1a9672e5f20e48c92ee43930"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.17-javadoc.jar",
          "url": "datagateways-1.0.17-javadoc.jar",
          "size": 261,
          "sha512": "8ce523d9e797763ad6ef3d137246c7f06ee33b46763a543cd3674a26bf37ce0d7e8f8def0123f36cf87786387f1f221ccfb5b30ba84ba343edf99cf87eca4c66",
          "sha256": "db6261f23b2ef27883fab9312f6f80ed6d7c178a69cbc649cf254f72354b8b7c",
          "sha1": "26b455d61904a87db65fbcdd5ee1cf622ae6fb55",
          "md5": "1f4ff8ee1a9672e5f20e48c92ee43930"
        }
      ]
    }
  ]
}
