{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "policy-impl",
    "version": "1.3.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "policy-impl-1.3.7-SNAPSHOT.jar",
          "url": "policy-impl-1.3.7-SNAPSHOT.jar",
          "size": 55403,
          "sha512": "94c0e76d1f2849c71308140d0f3dcffec7d7a167532c80f8a200a3f76b05f460be232ad0c2a0aa856a8dbec98975a62db22539ff6c27a21d71d69f3e10d73d2b",
          "sha256": "38015e99436111b18bc8d35f2550e2b6c552ccd6f1b07640e9c4352d32c614f3",
          "sha1": "0b929044d7eb3efc373b26d03965d689ce1c8165",
          "md5": "a751ed40b5d5628e2dd1f45c76479aa2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "policy-impl-1.3.7-SNAPSHOT.jar",
          "url": "policy-impl-1.3.7-SNAPSHOT.jar",
          "size": 55403,
          "sha512": "94c0e76d1f2849c71308140d0f3dcffec7d7a167532c80f8a200a3f76b05f460be232ad0c2a0aa856a8dbec98975a62db22539ff6c27a21d71d69f3e10d73d2b",
          "sha256": "38015e99436111b18bc8d35f2550e2b6c552ccd6f1b07640e9c4352d32c614f3",
          "sha1": "0b929044d7eb3efc373b26d03965d689ce1c8165",
          "md5": "a751ed40b5d5628e2dd1f45c76479aa2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "policy-impl-1.3.7-SNAPSHOT-sources.jar",
          "url": "policy-impl-1.3.7-SNAPSHOT-sources.jar",
          "size": 24783,
          "sha512": "37769fcef539c0e0ba9427a7025a008a48176545bbf987b9d3a1c753979523205d4fb05e28ffc862e6730bef9000362d0df514c2d4cf1c24434ae8118c228e87",
          "sha256": "bc31844d4c61df5a1b9b61d74333f8687be866b82708cd7a222eaa5326021e18",
          "sha1": "9a683fd37e600e9041467391fdc6311eaaba33b4",
          "md5": "dcf25524b549350eb29ea44c61df4cb9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "policy-impl-1.3.7-SNAPSHOT-javadoc.jar",
          "url": "policy-impl-1.3.7-SNAPSHOT-javadoc.jar",
          "size": 195149,
          "sha512": "92da921f5a2274b4a5d865ba6b484520d540addd150498703cd5c03b2d0cd6281483d5761790bb40baadb0bf9591795ccadca9e849b8c7cf2c49ebc9c83361fd",
          "sha256": "f190e808be8ab08f9f339be036d103fd7a837477acc4557d6d290ea6feccc6cb",
          "sha1": "c43604c77468fe321df79449639e41ac519a8644",
          "md5": "07288c75c410535e7cd3b51ca0718356"
        }
      ]
    }
  ]
}
