{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.callhandler",
    "module": "callhandler",
    "version": "1.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callhandler-1.0.36.jar",
          "url": "callhandler-1.0.36.jar",
          "size": 1401,
          "sha512": "b62925d0ed03b577e3a98a6c2c840cce0d8c9c0f33b061d1c5398ac4d7d410cbbf3bd587369ba4618b8a17bab57cf011f13ab405c947369e2606704a489f3ae5",
          "sha256": "60309d42c5b522bc796bbbb52c69551ab66fea73d5780e4495b2fc3de3784d5f",
          "sha1": "14a4863fc90f4922599e4cddce8dcc79b64819ec",
          "md5": "47db76d4a85a670d3efbebe9ead5d9cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "callhandler-1.0.36.jar",
          "url": "callhandler-1.0.36.jar",
          "size": 1401,
          "sha512": "b62925d0ed03b577e3a98a6c2c840cce0d8c9c0f33b061d1c5398ac4d7d410cbbf3bd587369ba4618b8a17bab57cf011f13ab405c947369e2606704a489f3ae5",
          "sha256": "60309d42c5b522bc796bbbb52c69551ab66fea73d5780e4495b2fc3de3784d5f",
          "sha1": "14a4863fc90f4922599e4cddce8dcc79b64819ec",
          "md5": "47db76d4a85a670d3efbebe9ead5d9cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callhandler-1.0.36-sources.jar",
          "url": "callhandler-1.0.36-sources.jar",
          "size": 1264,
          "sha512": "4ff54b674de93b10705a422c210132e8cc0ee45da9ae948ddbb5e9c95dea62afbc20b076f434714a7da11ff65a14e994dbb1d5741288b1aa66f1252adb0893b6",
          "sha256": "c2697094c7533f24d31291a50b9da7b0f3a2330e0df147e04bfb8a60f18cd45f",
          "sha1": "c327a8b1e4d051ac6b5881fdb9d19754642ac816",
          "md5": "98376822f3acf1a4db7a24159316481b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callhandler-1.0.36-javadoc.jar",
          "url": "callhandler-1.0.36-javadoc.jar",
          "size": 19260,
          "sha512": "689f5dd4a363b5f67669c7c09a979ea5201ec4fbc563a630c70134e17fda81cf5bcf458ae0bcb079447ed41c531a5a73977d6ef5bb88ac0ca17325a83e1e50e3",
          "sha256": "2cd33e81fb4dd11f2e023ad9552f3284fc1d7bd622da1d8971da12bf2853a060",
          "sha1": "dab395b8a87f42416dc7fab05e3bbc66e18376eb",
          "md5": "0874c0c3f93151dff860cda55223dfee"
        }
      ]
    }
  ]
}
