{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.callhandler",
    "module": "callhandler",
    "version": "1.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callhandler-1.0.36.jar",
          "url": "callhandler-1.0.36.jar",
          "size": 1401,
          "sha512": "d960fb3aeeb2d2294f18d87b518c6e79d9ad37eface729985c4070d54c27b6e590c1c4c0f476bbaa70275ceeb8805774db185fc33bba1c14cd3ede9c47448ebf",
          "sha256": "241fbdcea5f4e7c5c524c05b4c51696475b2ca72ed23ab23e48edd7fe407641a",
          "sha1": "8995da0802e21771104c93f3289c1048ebd0c918",
          "md5": "4243241bf64dad0e42ebc14e53b452c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "callhandler-1.0.36.jar",
          "url": "callhandler-1.0.36.jar",
          "size": 1401,
          "sha512": "d960fb3aeeb2d2294f18d87b518c6e79d9ad37eface729985c4070d54c27b6e590c1c4c0f476bbaa70275ceeb8805774db185fc33bba1c14cd3ede9c47448ebf",
          "sha256": "241fbdcea5f4e7c5c524c05b4c51696475b2ca72ed23ab23e48edd7fe407641a",
          "sha1": "8995da0802e21771104c93f3289c1048ebd0c918",
          "md5": "4243241bf64dad0e42ebc14e53b452c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callhandler-1.0.36-sources.jar",
          "url": "callhandler-1.0.36-sources.jar",
          "size": 1264,
          "sha512": "f46805f3032f2e27b41031d75231f3b3b0eeb0f183175e83f5a7510b19bda58a6bb4c67647a9e11addd59ffc4a832af7394078eac0cdb5405b8dbf0d11a74eaf",
          "sha256": "212d19b9d0a81e22a1057860365d3a4e727ecb701775e1fbbef62c163d26ff84",
          "sha1": "a76e5588c389b1376e54d081cd3e93e041c2049b",
          "md5": "8003328cc6ca9e0060287d9608d8613a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callhandler-1.0.36-javadoc.jar",
          "url": "callhandler-1.0.36-javadoc.jar",
          "size": 19260,
          "sha512": "9824ecc512c748f66ae1d9fa3db964ad665dbd21cc183d8d69f8c419d8e67c4722f36046c3862faa2d43097933101b0eae334066931dd6781a2c30344a20b8d5",
          "sha256": "797d8561670bdbfff87ba44d508fd6a4051a69e416162a4427b5f9bc5fb39b38",
          "sha1": "e5729cb548e71408fd21b53dfba33a0c8601a214",
          "md5": "4a6bbdbdae4e396e5e96ba1a14137303"
        }
      ]
    }
  ]
}
