{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.presenters",
    "module": "callee",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callee-1.0.17.jar",
          "url": "callee-1.0.17.jar",
          "size": 261,
          "sha512": "17bf357f06042a8002094915439bc5a47e128f3624eec6e0b2b98028399429328e239b0873322f82264728ba4862853f562ccf21041e8ff5c50133356ea7c448",
          "sha256": "3fa19c1f3325c927c44197bc0fef391c18e2f8a2b140496f907de261b267c110",
          "sha1": "6649688d6bb0bac4fe88734be5603d65a49935b6",
          "md5": "299d2461173282c0b6dc239eb5bf8eba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.17.jar",
          "url": "callee-1.0.17.jar",
          "size": 261,
          "sha512": "17bf357f06042a8002094915439bc5a47e128f3624eec6e0b2b98028399429328e239b0873322f82264728ba4862853f562ccf21041e8ff5c50133356ea7c448",
          "sha256": "3fa19c1f3325c927c44197bc0fef391c18e2f8a2b140496f907de261b267c110",
          "sha1": "6649688d6bb0bac4fe88734be5603d65a49935b6",
          "md5": "299d2461173282c0b6dc239eb5bf8eba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.17-sources.jar",
          "url": "callee-1.0.17-sources.jar",
          "size": 261,
          "sha512": "e9b817f76d94d5cea3baddebde4c776383b8839479b790d0b3c22474231d5d76eef8c1c0f4c3201ea056dacdd081a1c368b715188c9470b32987b7e185f2900e",
          "sha256": "7e868412a33f2eb5a9d8e57bb957f8a2ede79f7c55a573f77ccaa29f0a59d5c5",
          "sha1": "4515b2edfcc99088f85d7c9508423aed89bb256a",
          "md5": "20642ba36cf9b71dd69eb53b5c8f2044"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.17-javadoc.jar",
          "url": "callee-1.0.17-javadoc.jar",
          "size": 261,
          "sha512": "e9b817f76d94d5cea3baddebde4c776383b8839479b790d0b3c22474231d5d76eef8c1c0f4c3201ea056dacdd081a1c368b715188c9470b32987b7e185f2900e",
          "sha256": "7e868412a33f2eb5a9d8e57bb957f8a2ede79f7c55a573f77ccaa29f0a59d5c5",
          "sha1": "4515b2edfcc99088f85d7c9508423aed89bb256a",
          "md5": "20642ba36cf9b71dd69eb53b5c8f2044"
        }
      ]
    }
  ]
}
