{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.views",
    "module": "callee",
    "version": "1.0.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callee-1.0.43.jar",
          "url": "callee-1.0.43.jar",
          "size": 261,
          "sha512": "7c85838fcb948ccbcf951ad1b4889e82bd5f1367e1c73fe6880e6cfd4fecb747dad6f6af67097fbb56f27943444444ee443ec3eaa486ceb204f8d1935badb8c4",
          "sha256": "4b2433898f5f6a7f2651d0baac6013cf3b4a724c480aba375ec59237dffcf790",
          "sha1": "15d87e7a97c9738c5b54863430809a9b433f972a",
          "md5": "c4ede14a8897e27823c752905015dc7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.43.jar",
          "url": "callee-1.0.43.jar",
          "size": 261,
          "sha512": "7c85838fcb948ccbcf951ad1b4889e82bd5f1367e1c73fe6880e6cfd4fecb747dad6f6af67097fbb56f27943444444ee443ec3eaa486ceb204f8d1935badb8c4",
          "sha256": "4b2433898f5f6a7f2651d0baac6013cf3b4a724c480aba375ec59237dffcf790",
          "sha1": "15d87e7a97c9738c5b54863430809a9b433f972a",
          "md5": "c4ede14a8897e27823c752905015dc7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.43-sources.jar",
          "url": "callee-1.0.43-sources.jar",
          "size": 261,
          "sha512": "7c85838fcb948ccbcf951ad1b4889e82bd5f1367e1c73fe6880e6cfd4fecb747dad6f6af67097fbb56f27943444444ee443ec3eaa486ceb204f8d1935badb8c4",
          "sha256": "4b2433898f5f6a7f2651d0baac6013cf3b4a724c480aba375ec59237dffcf790",
          "sha1": "15d87e7a97c9738c5b54863430809a9b433f972a",
          "md5": "c4ede14a8897e27823c752905015dc7e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.43-javadoc.jar",
          "url": "callee-1.0.43-javadoc.jar",
          "size": 261,
          "sha512": "7c85838fcb948ccbcf951ad1b4889e82bd5f1367e1c73fe6880e6cfd4fecb747dad6f6af67097fbb56f27943444444ee443ec3eaa486ceb204f8d1935badb8c4",
          "sha256": "4b2433898f5f6a7f2651d0baac6013cf3b4a724c480aba375ec59237dffcf790",
          "sha1": "15d87e7a97c9738c5b54863430809a9b433f972a",
          "md5": "c4ede14a8897e27823c752905015dc7e"
        }
      ]
    }
  ]
}
