{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "config",
    "version": "1.3.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-1.3.5-SNAPSHOT.jar",
          "url": "config-1.3.5-SNAPSHOT.jar",
          "size": 8215,
          "sha512": "9e49b0acd3dd5811b87cb6c70cefb1981e5dda8252b87a3790e77fc9dc18d8cb202e918d493c3975bc8391dc3e5d9bcf15f453bbef93f06a65f37b348b6e9ea1",
          "sha256": "c2ce294840d196684aaa93c874b16a3ccd098dffb348d0b84f77614951ede288",
          "sha1": "35f69563ef969112edd196516831a959e5d14711",
          "md5": "5a68a0c4b73e1e33eff336872f97cf15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.33"
          }
        }
      ],
      "files": [
        {
          "name": "config-1.3.5-SNAPSHOT.jar",
          "url": "config-1.3.5-SNAPSHOT.jar",
          "size": 8215,
          "sha512": "9e49b0acd3dd5811b87cb6c70cefb1981e5dda8252b87a3790e77fc9dc18d8cb202e918d493c3975bc8391dc3e5d9bcf15f453bbef93f06a65f37b348b6e9ea1",
          "sha256": "c2ce294840d196684aaa93c874b16a3ccd098dffb348d0b84f77614951ede288",
          "sha1": "35f69563ef969112edd196516831a959e5d14711",
          "md5": "5a68a0c4b73e1e33eff336872f97cf15"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.5-SNAPSHOT-sources.jar",
          "url": "config-1.3.5-SNAPSHOT-sources.jar",
          "size": 4221,
          "sha512": "87c0f880815bcf1e787a98bb9055bcba4ed3d625a58c705b753d2c30cd0d0a55a3b25ef57058f7e9f470c754558513d698c8517fbd8197f2ec3e83184a2a3204",
          "sha256": "cebc539ab9f53701e139da81a0ba87b2b04820b81faee7867f9496ce98b55480",
          "sha1": "a0969c0aa7ce1ebd1510c2d1d841354afe28fd1c",
          "md5": "1964706f52b032c27fbd510dc2e15743"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.5-SNAPSHOT-javadoc.jar",
          "url": "config-1.3.5-SNAPSHOT-javadoc.jar",
          "size": 45745,
          "sha512": "de47f238c947370eff40e59c821386dc6b18ffe9b0d70cdc2a7e487210fe05841397acd18e8e12ca8e382d2d62089914c79cfa7eebd8bbaa8c979508f5ce9b1b",
          "sha256": "36b07238a98be1a299c1e78a08c37c9a47893d310d79822e771bdbec3eba1b02",
          "sha1": "9b28aef5d03fcdbc7cd1e887ed74a9e13bfddefc",
          "md5": "e530ffd0cc79e1a59160c6fbd3021f55"
        }
      ]
    }
  ]
}
