{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.datagateways",
    "module": "datagateways",
    "version": "1.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "datagateways-1.0.25.jar",
          "url": "datagateways-1.0.25.jar",
          "size": 261,
          "sha512": "1dd7163edc198ad662b3d98acb4ced95ca336a95bcd92d28811c1cb1f4d731dc6c732fadad67e5d8f7c3863b96bfcaebb94c049ac5563ee25635c2128f0b6d9f",
          "sha256": "2fb8d6be97964803d6f882227ab266732d0f5c6ab513a2635564ba59b0237537",
          "sha1": "32bbe55533e412f69d9c92869aa4fb3c4b20af98",
          "md5": "946d7d9398738bcae2315d7d30db6bf0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.25.jar",
          "url": "datagateways-1.0.25.jar",
          "size": 261,
          "sha512": "1dd7163edc198ad662b3d98acb4ced95ca336a95bcd92d28811c1cb1f4d731dc6c732fadad67e5d8f7c3863b96bfcaebb94c049ac5563ee25635c2128f0b6d9f",
          "sha256": "2fb8d6be97964803d6f882227ab266732d0f5c6ab513a2635564ba59b0237537",
          "sha1": "32bbe55533e412f69d9c92869aa4fb3c4b20af98",
          "md5": "946d7d9398738bcae2315d7d30db6bf0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.25-sources.jar",
          "url": "datagateways-1.0.25-sources.jar",
          "size": 261,
          "sha512": "1dd7163edc198ad662b3d98acb4ced95ca336a95bcd92d28811c1cb1f4d731dc6c732fadad67e5d8f7c3863b96bfcaebb94c049ac5563ee25635c2128f0b6d9f",
          "sha256": "2fb8d6be97964803d6f882227ab266732d0f5c6ab513a2635564ba59b0237537",
          "sha1": "32bbe55533e412f69d9c92869aa4fb3c4b20af98",
          "md5": "946d7d9398738bcae2315d7d30db6bf0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.25-javadoc.jar",
          "url": "datagateways-1.0.25-javadoc.jar",
          "size": 261,
          "sha512": "1dd7163edc198ad662b3d98acb4ced95ca336a95bcd92d28811c1cb1f4d731dc6c732fadad67e5d8f7c3863b96bfcaebb94c049ac5563ee25635c2128f0b6d9f",
          "sha256": "2fb8d6be97964803d6f882227ab266732d0f5c6ab513a2635564ba59b0237537",
          "sha1": "32bbe55533e412f69d9c92869aa4fb3c4b20af98",
          "md5": "946d7d9398738bcae2315d7d30db6bf0"
        }
      ]
    }
  ]
}
