{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "config",
    "version": "1.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-1.3.1-SNAPSHOT.jar",
          "url": "config-1.3.1-SNAPSHOT.jar",
          "size": 8215,
          "sha512": "a625f47f81e9b0bb35dd2f6db2cebe6b2e3ea4c70b048263f44e5a55617240905e2be93dee6f412e56a497eac3b084989880ebaf4b11f5faf092d56f9beccc29",
          "sha256": "f9c0a1e5724e77cb2c85e40ed312f1d94f39fe3cc7fcf24a45105bbf89998259",
          "sha1": "dde3b51a2532b4b36ee71a92e61c2ede9fc8cbdb",
          "md5": "54bb577e2b5d923eea027696d7f9b129"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.33"
          }
        }
      ],
      "files": [
        {
          "name": "config-1.3.1-SNAPSHOT.jar",
          "url": "config-1.3.1-SNAPSHOT.jar",
          "size": 8215,
          "sha512": "a625f47f81e9b0bb35dd2f6db2cebe6b2e3ea4c70b048263f44e5a55617240905e2be93dee6f412e56a497eac3b084989880ebaf4b11f5faf092d56f9beccc29",
          "sha256": "f9c0a1e5724e77cb2c85e40ed312f1d94f39fe3cc7fcf24a45105bbf89998259",
          "sha1": "dde3b51a2532b4b36ee71a92e61c2ede9fc8cbdb",
          "md5": "54bb577e2b5d923eea027696d7f9b129"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.1-SNAPSHOT-sources.jar",
          "url": "config-1.3.1-SNAPSHOT-sources.jar",
          "size": 4221,
          "sha512": "420aca700f1ad6b5a0168ec582ba7b6536396d03821af9d613bc7227b6067a308b7ebb4d54ea41ed94444d8c555e8c25b3d87fb4b0b39a59aa7381c393ebe915",
          "sha256": "656676ba26dd4da66ac235b8ab0d021cdcce279e7c57594933fa8a39451f7108",
          "sha1": "7d3ee53ee0b9f58af624ce8c4854f28c0422e761",
          "md5": "e194cf045d6e0fa4977f49f174bf16cb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.1-SNAPSHOT-javadoc.jar",
          "url": "config-1.3.1-SNAPSHOT-javadoc.jar",
          "size": 45724,
          "sha512": "db3fbf694565106cda4dd3655182e71a8f0f5d138da4deb6adec0bd4a36adecff1aa719ffec9803fd4fbbd827a278c6719ede17cc6a12b3b960737c7ca20e624",
          "sha256": "140c3ae40dd94515c4d4e969c17295ce4c784c1a753d8e503c50a12d96445067",
          "sha1": "899707948950e09bc8ae1370b9c6ab0f465bded1",
          "md5": "74224764fca3b97f95d110d982708a7a"
        }
      ]
    }
  ]
}
