{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "config",
    "version": "1.3.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "config-1.3.1-SNAPSHOT.jar",
          "url": "config-1.3.1-SNAPSHOT.jar",
          "size": 8215,
          "sha512": "4347ffd310c4b233bf2bfc338b24225fbee635add8549c56f09d987f218cae9ece0d9750c29ca5500111f4392f1c47951bdae5d39ab4ef3cab0c050f95539246",
          "sha256": "07883e8be257e8ff977aecddc0a8b43aa1e4378e0be3ea24cebfa820d2b20173",
          "sha1": "a85da4e0be38a9b81a5489b8ad596d67ae6ce9c9",
          "md5": "543e418ecce14a260a1e1e3fc46c68e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.29"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.29"
          }
        }
      ],
      "files": [
        {
          "name": "config-1.3.1-SNAPSHOT.jar",
          "url": "config-1.3.1-SNAPSHOT.jar",
          "size": 8215,
          "sha512": "4347ffd310c4b233bf2bfc338b24225fbee635add8549c56f09d987f218cae9ece0d9750c29ca5500111f4392f1c47951bdae5d39ab4ef3cab0c050f95539246",
          "sha256": "07883e8be257e8ff977aecddc0a8b43aa1e4378e0be3ea24cebfa820d2b20173",
          "sha1": "a85da4e0be38a9b81a5489b8ad596d67ae6ce9c9",
          "md5": "543e418ecce14a260a1e1e3fc46c68e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.1-SNAPSHOT-sources.jar",
          "url": "config-1.3.1-SNAPSHOT-sources.jar",
          "size": 4221,
          "sha512": "eb23603be2408195f3ef8aca6073cd589bde5cb4a5fa2c5da3a9caa1b1b9020f5927261b72c5167df8045aa4b4f5a24830d1e9573e5a9f2352a3ff9e74d83aea",
          "sha256": "f16acb313b656a6fad7e814abacd26451eb301c8cc4c88c6a447b5c947740f13",
          "sha1": "686549b96c69911fc4c726130e966a0078348637",
          "md5": "d25cf760975ddaf7a58add1eb91480e9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-1.3.1-SNAPSHOT-javadoc.jar",
          "url": "config-1.3.1-SNAPSHOT-javadoc.jar",
          "size": 45724,
          "sha512": "16483b48b74b813f748a7a69bfcd990130bbdf1e6bc50fcf10cabb5e4a70114abe8537943a5de4db59a3a3190f481962190769b61618f387432fd1976e90dd20",
          "sha256": "1144aa589e1dc47a1f729c7b6fc98cc66f729d69c126c4a8747ff79dd0456c71",
          "sha1": "c73b769c1bca12b173796c48fe8cd3a8bd67f44d",
          "md5": "bf1223a69a94146e32f7057975b7ca19"
        }
      ]
    }
  ]
}
