{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "accessor",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "accessor-1.0.15.jar",
          "url": "accessor-1.0.15.jar",
          "size": 5357,
          "sha512": "aaf79a59a0cf87068e6edc87b309c860509b7a50c2e59db9b2d0528bace77edd3024ce901fa4cbba1ee4cf961cb244086b8b8f7c2001792100bbfe65aeab72c1",
          "sha256": "7ca39d20d347d6958f6d2c3fc05f9bc3169f905881360b570edf00c5f6220b0f",
          "sha1": "6f02e0c9fcb21fa0c47675b4febd6496e6d57377",
          "md5": "bfebd675bbdd8c123fc5eb181f678a44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessor-1.0.15.jar",
          "url": "accessor-1.0.15.jar",
          "size": 5357,
          "sha512": "aaf79a59a0cf87068e6edc87b309c860509b7a50c2e59db9b2d0528bace77edd3024ce901fa4cbba1ee4cf961cb244086b8b8f7c2001792100bbfe65aeab72c1",
          "sha256": "7ca39d20d347d6958f6d2c3fc05f9bc3169f905881360b570edf00c5f6220b0f",
          "sha1": "6f02e0c9fcb21fa0c47675b4febd6496e6d57377",
          "md5": "bfebd675bbdd8c123fc5eb181f678a44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessor-1.0.15-sources.jar",
          "url": "accessor-1.0.15-sources.jar",
          "size": 3802,
          "sha512": "98ccdc76263e0f55b3f871727ff45c780b436a21627b95865329e4aaabcd99fd64eee057ca83cc0d9f6003b14339777df923ddc1d71ca352df4a95ce91b80247",
          "sha256": "1abf5eadc5d83b0ee02a878f22c205b8c5ffc63f076a4866c1b80491806ca435",
          "sha1": "8c555eec3cb94f259453676dee054f9df915ebcf",
          "md5": "130873be8fce91428cfed9a4d10e4f71"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessor-1.0.15-javadoc.jar",
          "url": "accessor-1.0.15-javadoc.jar",
          "size": 90762,
          "sha512": "6c9e07842292d2a24d14f5804d0d501b1525edae858f4483c1bd67f2e8ba885ebd2e59b0377ec40f36c1687ab09994ae5d14f1bf20df0062746fa652b698704c",
          "sha256": "60ee60796b662e91a08f3caf5da4b3ce0308b1d51452ee5a6a406305ed83b0f7",
          "sha1": "901269b5fc7fc01f2bc2b25d4a1ac0f1f8f650df",
          "md5": "9745907789e254130be4ff42b207508a"
        }
      ]
    }
  ]
}
