{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "accessor",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "accessor-1.0.15.jar",
          "url": "accessor-1.0.15.jar",
          "size": 5305,
          "sha512": "e1118bcafc5b607ad2d1a8bc20863f1a404414d71050578048af6c74027cfbad6f6eda61820a37cc05878aa3c1d751bc5a63e340497f7e927e3ed51321589347",
          "sha256": "022b6590ef631693e35130afed464c62ded1373a68171a0f9fde02b41fd5bc87",
          "sha1": "e6f2ba1b050834279d89a878a86ba1c4e2895bb3",
          "md5": "2590b39e6b45ac0d36deb09fe3342fe8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessor-1.0.15.jar",
          "url": "accessor-1.0.15.jar",
          "size": 5305,
          "sha512": "e1118bcafc5b607ad2d1a8bc20863f1a404414d71050578048af6c74027cfbad6f6eda61820a37cc05878aa3c1d751bc5a63e340497f7e927e3ed51321589347",
          "sha256": "022b6590ef631693e35130afed464c62ded1373a68171a0f9fde02b41fd5bc87",
          "sha1": "e6f2ba1b050834279d89a878a86ba1c4e2895bb3",
          "md5": "2590b39e6b45ac0d36deb09fe3342fe8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessor-1.0.15-sources.jar",
          "url": "accessor-1.0.15-sources.jar",
          "size": 3802,
          "sha512": "98ccdc76263e0f55b3f871727ff45c780b436a21627b95865329e4aaabcd99fd64eee057ca83cc0d9f6003b14339777df923ddc1d71ca352df4a95ce91b80247",
          "sha256": "1abf5eadc5d83b0ee02a878f22c205b8c5ffc63f076a4866c1b80491806ca435",
          "sha1": "8c555eec3cb94f259453676dee054f9df915ebcf",
          "md5": "130873be8fce91428cfed9a4d10e4f71"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessor-1.0.15-javadoc.jar",
          "url": "accessor-1.0.15-javadoc.jar",
          "size": 37221,
          "sha512": "2da9369e7522ab378ce7ab8f0b340d4ffb85c91e0fc2cd1ea689c2d177d496e31c79755ae6ea1967f169d84719e2fc4829c62dfe91bd4aa94106a61845026433",
          "sha256": "e58ea26768e9dd3f3ad514392a676e3e0de8bd6f51f228f40fa5ded82a498044",
          "sha1": "32d64bcafd0324129052ee753d142ebdf81286d1",
          "md5": "893a89c5bfdce8cc850ee730d3f90821"
        }
      ]
    }
  ]
}
