{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "sound-adapter",
    "version": "1.3.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sound-adapter-1.3.8-SNAPSHOT.jar",
          "url": "sound-adapter-1.3.8-SNAPSHOT.jar",
          "size": 5022,
          "sha512": "1fc14a0f35bece9f397beb0b9b5fc46bac948ab906b0fc3e4d72c66fe5d722aea1b7c597745d702181d3fb6a99375a0b8e8294db9f3b7bd211fd82310ce3fdae",
          "sha256": "95909b34d7ac6cd28d5882f98f96f248763b03f0ec8b51651fed699e604b21fe",
          "sha1": "5486eef1f3adab018c388d522525247c6961c3f6",
          "md5": "8260234475401e2dcf7d5bc256f5379b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.41"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.41"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.41"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.41"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.41"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.41"
          }
        }
      ],
      "files": [
        {
          "name": "sound-adapter-1.3.8-SNAPSHOT.jar",
          "url": "sound-adapter-1.3.8-SNAPSHOT.jar",
          "size": 5022,
          "sha512": "1fc14a0f35bece9f397beb0b9b5fc46bac948ab906b0fc3e4d72c66fe5d722aea1b7c597745d702181d3fb6a99375a0b8e8294db9f3b7bd211fd82310ce3fdae",
          "sha256": "95909b34d7ac6cd28d5882f98f96f248763b03f0ec8b51651fed699e604b21fe",
          "sha1": "5486eef1f3adab018c388d522525247c6961c3f6",
          "md5": "8260234475401e2dcf7d5bc256f5379b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sound-adapter-1.3.8-SNAPSHOT-sources.jar",
          "url": "sound-adapter-1.3.8-SNAPSHOT-sources.jar",
          "size": 3317,
          "sha512": "3d00e53edcf9a5e20f23e7b6193c34c19489f153f0a48800d18f1136c333d8e3dc899600ea49d333d118d9c99dc6fb230009460ffd8dc3ac47e8bb89aebecab2",
          "sha256": "ba20561ad11d9d58e186c45b553c4a36f56fc7a033263c9f7fc79becaea7ddfa",
          "sha1": "90b4372260fe2313e58b2a3d73bb9a0f60d28f1d",
          "md5": "7de04dcfba6731186be26c7f28445983"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sound-adapter-1.3.8-SNAPSHOT-javadoc.jar",
          "url": "sound-adapter-1.3.8-SNAPSHOT-javadoc.jar",
          "size": 31856,
          "sha512": "acd0ff2e8bdacc9ad85948fc8bb50ecd27668d3161d02dffd997d1ab5273981cdf0e8fca4a969bcbd604987c54f73ce8ec581b2fad78d6ff42bc6e872e323a0e",
          "sha256": "dc7633cf90ed74da004beef0b065af181452772ab64c8ff4ca37e13228e7bf4c",
          "sha1": "41b126b0052b0293dcb5c744f800cb919fcf1e75",
          "md5": "e3872c58d7c1a92e5a417bff6cc5585e"
        }
      ]
    }
  ]
}
