{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.datagateways",
    "module": "datagateways",
    "version": "1.0.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "datagateways-1.0.40.jar",
          "url": "datagateways-1.0.40.jar",
          "size": 261,
          "sha512": "11bdeca76bc989410f90260fdb34d41c9022dc30601e85cd4a200b0b736a7ace6ebd16962b35a0d432d177bb634f73ef341938d29817713af3260e3faa2caf95",
          "sha256": "f55de0b6d1b5982a242d8bc2b55dbe83f5044b69f297712ca6946b032a5be8ad",
          "sha1": "e8a9c05706fbc5c58ec5a884df44a7f1991ffc3f",
          "md5": "5f2bbb711cd637de3735f6cae6cfad1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.40.jar",
          "url": "datagateways-1.0.40.jar",
          "size": 261,
          "sha512": "11bdeca76bc989410f90260fdb34d41c9022dc30601e85cd4a200b0b736a7ace6ebd16962b35a0d432d177bb634f73ef341938d29817713af3260e3faa2caf95",
          "sha256": "f55de0b6d1b5982a242d8bc2b55dbe83f5044b69f297712ca6946b032a5be8ad",
          "sha1": "e8a9c05706fbc5c58ec5a884df44a7f1991ffc3f",
          "md5": "5f2bbb711cd637de3735f6cae6cfad1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.40-sources.jar",
          "url": "datagateways-1.0.40-sources.jar",
          "size": 261,
          "sha512": "11bdeca76bc989410f90260fdb34d41c9022dc30601e85cd4a200b0b736a7ace6ebd16962b35a0d432d177bb634f73ef341938d29817713af3260e3faa2caf95",
          "sha256": "f55de0b6d1b5982a242d8bc2b55dbe83f5044b69f297712ca6946b032a5be8ad",
          "sha1": "e8a9c05706fbc5c58ec5a884df44a7f1991ffc3f",
          "md5": "5f2bbb711cd637de3735f6cae6cfad1c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.40-javadoc.jar",
          "url": "datagateways-1.0.40-javadoc.jar",
          "size": 261,
          "sha512": "11bdeca76bc989410f90260fdb34d41c9022dc30601e85cd4a200b0b736a7ace6ebd16962b35a0d432d177bb634f73ef341938d29817713af3260e3faa2caf95",
          "sha256": "f55de0b6d1b5982a242d8bc2b55dbe83f5044b69f297712ca6946b032a5be8ad",
          "sha1": "e8a9c05706fbc5c58ec5a884df44a7f1991ffc3f",
          "md5": "5f2bbb711cd637de3735f6cae6cfad1c"
        }
      ]
    }
  ]
}
