{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.controllers",
    "module": "caller",
    "version": "1.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "caller-1.0.25.jar",
          "url": "caller-1.0.25.jar",
          "size": 261,
          "sha512": "ee07758cec2efe8f0aea07b9f03b2113b62fbcfc2de3680846d94f7bb4a841e588c80cff01848b6b5fae63a14ca286d09358bff9172fc60ccff629bb237e1434",
          "sha256": "c66d8181dafdb2244f429ddb34409a6c74e068780d690b5ebba11f1ab5388078",
          "sha1": "0fffeabb26e5bf1e2b8e9c56035f4ce9084a2b89",
          "md5": "6331a81db426c8ae78bccce62843b22d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.25"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.25"
          }
        }
      ],
      "files": [
        {
          "name": "caller-1.0.25.jar",
          "url": "caller-1.0.25.jar",
          "size": 261,
          "sha512": "ee07758cec2efe8f0aea07b9f03b2113b62fbcfc2de3680846d94f7bb4a841e588c80cff01848b6b5fae63a14ca286d09358bff9172fc60ccff629bb237e1434",
          "sha256": "c66d8181dafdb2244f429ddb34409a6c74e068780d690b5ebba11f1ab5388078",
          "sha1": "0fffeabb26e5bf1e2b8e9c56035f4ce9084a2b89",
          "md5": "6331a81db426c8ae78bccce62843b22d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caller-1.0.25-sources.jar",
          "url": "caller-1.0.25-sources.jar",
          "size": 261,
          "sha512": "ee07758cec2efe8f0aea07b9f03b2113b62fbcfc2de3680846d94f7bb4a841e588c80cff01848b6b5fae63a14ca286d09358bff9172fc60ccff629bb237e1434",
          "sha256": "c66d8181dafdb2244f429ddb34409a6c74e068780d690b5ebba11f1ab5388078",
          "sha1": "0fffeabb26e5bf1e2b8e9c56035f4ce9084a2b89",
          "md5": "6331a81db426c8ae78bccce62843b22d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caller-1.0.25-javadoc.jar",
          "url": "caller-1.0.25-javadoc.jar",
          "size": 261,
          "sha512": "ee07758cec2efe8f0aea07b9f03b2113b62fbcfc2de3680846d94f7bb4a841e588c80cff01848b6b5fae63a14ca286d09358bff9172fc60ccff629bb237e1434",
          "sha256": "c66d8181dafdb2244f429ddb34409a6c74e068780d690b5ebba11f1ab5388078",
          "sha1": "0fffeabb26e5bf1e2b8e9c56035f4ce9084a2b89",
          "md5": "6331a81db426c8ae78bccce62843b22d"
        }
      ]
    }
  ]
}
