{
  "formatVersion": "1.1",
  "component": {
    "group": "com.modularmods.mcgltf",
    "module": "MCglTF",
    "version": "1.20.4-Fabric-3.3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "MCglTF-1.20.4-Fabric-3.3.0.0.jar",
          "url": "MCglTF-1.20.4-Fabric-3.3.0.0.jar",
          "size": 608801,
          "sha512": "c8282e7e256fc4124af14ae56cec8896bcd8b036f9c443bcf1999c52a496aad3b893b934e5d9718b678e01530fceb7d6e88746cf9749122768a42a777492bf1d",
          "sha256": "2efb90ca8983e7c128b9d7ac5bc19638dc2a15f256620d9c058bb7d782955a01",
          "sha1": "cd7ca8128b4630c921cf052cf67d3512b95568ff",
          "md5": "c477ea3a5c155423ae916695f21c1e68"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.97.2+1.20.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "iris",
          "version": {
            "requires": "1.7.2+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "MCglTF-1.20.4-Fabric-3.3.0.0.jar",
          "url": "MCglTF-1.20.4-Fabric-3.3.0.0.jar",
          "size": 608801,
          "sha512": "c8282e7e256fc4124af14ae56cec8896bcd8b036f9c443bcf1999c52a496aad3b893b934e5d9718b678e01530fceb7d6e88746cf9749122768a42a777492bf1d",
          "sha256": "2efb90ca8983e7c128b9d7ac5bc19638dc2a15f256620d9c058bb7d782955a01",
          "sha1": "cd7ca8128b4630c921cf052cf67d3512b95568ff",
          "md5": "c477ea3a5c155423ae916695f21c1e68"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MCglTF-1.20.4-Fabric-3.3.0.0-sources.jar",
          "url": "MCglTF-1.20.4-Fabric-3.3.0.0-sources.jar",
          "size": 503100,
          "sha512": "f3c9cba0bd6d5480b0323f6c25334b503919cffc16c83b3b91bc4457314ceab1871210cd46d77c883c161a97e3fbe3a2f68878eb7d2c2da342e72ccb2dc73607",
          "sha256": "fcc5ffbae7e9b33198afffb5f71333164606b96d0f2dc7aa1294b9b6c9c61c1d",
          "sha1": "e4bf4d329bb25a0650b4945506fba298fb08ef17",
          "md5": "f7fb0ebc4499679fd57a1fa36deb0bcc"
        }
      ]
    }
  ]
}
