{
  "formatVersion": "1.1",
  "component": {
    "group": "io.libp2p",
    "module": "jvm-libp2p",
    "version": "1.2.1R",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-libp2p-1.2.1R.jar",
          "url": "jvm-libp2p-1.2.1R.jar",
          "size": 1726119,
          "sha512": "56f533aab77a61dfc8781da1f9600a3ee7c3788925a359a259ee447172c0642290cac2eb6e64668beb75234528eb1dfff7f43fda3cc326d34fd587905e83cfbf",
          "sha256": "db3b5701c907128c686e2a85ff3d9186024b3e8dbeedbfc9325edadad118cc0b",
          "sha1": "ff3a52dd51b1704520f943b6e2aa131fef69e904",
          "md5": "26d94dc3d18776a14ab231d977c4576e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-codec-http",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-classes-epoll",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-x86_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-aarch_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-x86_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-aarch_64"
            }
          }
        },
        {
          "group": "io.netty.incubator",
          "module": "netty-incubator-codec-native-quic",
          "version": {
            "requires": "0.0.71.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-incubator-codec-native-quic",
              "type": "jar",
              "extension": "jar",
              "classifier": "windows-x86_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-x86_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "linux-aarch_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-x86_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "osx-aarch_64"
            }
          }
        },
        {
          "group": "io.netty",
          "module": "netty-tcnative-boringssl-static",
          "version": {
            "requires": "2.0.70.Final"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "netty-tcnative-boringssl-static",
              "type": "jar",
              "extension": "jar",
              "classifier": "windows-x86_64"
            }
          }
        },
        {
          "group": "com.github.multiformats",
          "module": "java-multibase",
          "version": {
            "requires": "v1.1.1"
          }
        },
        {
          "group": "tech.pegasys",
          "module": "noise-java",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-common",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport",
          "version": {
            "requires": "4.1.118.Final"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-libp2p-1.2.1R.jar",
          "url": "jvm-libp2p-1.2.1R.jar",
          "size": 1726119,
          "sha512": "56f533aab77a61dfc8781da1f9600a3ee7c3788925a359a259ee447172c0642290cac2eb6e64668beb75234528eb1dfff7f43fda3cc326d34fd587905e83cfbf",
          "sha256": "db3b5701c907128c686e2a85ff3d9186024b3e8dbeedbfc9325edadad118cc0b",
          "sha1": "ff3a52dd51b1704520f943b6e2aa131fef69e904",
          "md5": "26d94dc3d18776a14ab231d977c4576e"
        }
      ]
    }
  ]
}
