{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.callhandler",
    "module": "callhandler",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callhandler-1.0.15.jar",
          "url": "callhandler-1.0.15.jar",
          "size": 1401,
          "sha512": "ecda6b053c1926eb38e86aa012748379651af0b78ef46cf3710f31b74edf2c4470df90061fbab6aafc5c6d1588020af4828081afc1d8551ef290a3744fa240ec",
          "sha256": "6aa4bc6890c19733c39ed329efd71d3b9ddca2ef109a1b107c28551141305720",
          "sha1": "5d7228962b09e03b9b7824f29645b2c129c06f44",
          "md5": "39ed6f5ccb101e6677f7fbebf9a30774"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.15"
          }
        }
      ],
      "files": [
        {
          "name": "callhandler-1.0.15.jar",
          "url": "callhandler-1.0.15.jar",
          "size": 1401,
          "sha512": "ecda6b053c1926eb38e86aa012748379651af0b78ef46cf3710f31b74edf2c4470df90061fbab6aafc5c6d1588020af4828081afc1d8551ef290a3744fa240ec",
          "sha256": "6aa4bc6890c19733c39ed329efd71d3b9ddca2ef109a1b107c28551141305720",
          "sha1": "5d7228962b09e03b9b7824f29645b2c129c06f44",
          "md5": "39ed6f5ccb101e6677f7fbebf9a30774"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callhandler-1.0.15-sources.jar",
          "url": "callhandler-1.0.15-sources.jar",
          "size": 1265,
          "sha512": "a99a3ad0c1416c0995a2dc12dd6a9cd209b102e0f8c5acb270787acb9ece8e49a141d079672e7957f6fd97f29ece9c5c286eea0e429bf6f7f2b188e9bc2b0a20",
          "sha256": "5f288f05bb044c8bff64b599a8a344be9bf311e6db80c4e71032c658e4bae753",
          "sha1": "e3e5e8465c3334fe9bdd413524ff95db254eee56",
          "md5": "7a743cb79c8a2ef4b35afc94e85f1451"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callhandler-1.0.15-javadoc.jar",
          "url": "callhandler-1.0.15-javadoc.jar",
          "size": 19253,
          "sha512": "0561fa1b1ce34f779fd4f78ca05a065be042a724c5a51d08cfb530991624ee423a2d0151988ea10a3421e1eb726f9c89823cc1586447959310d475b29a1b1970",
          "sha256": "6dcab391aa99006cbedd3569a7f4f8ebc92b5fe79ff93f512e952926affee9c5",
          "sha1": "3de84a8e72d56925696b26494082cd5cc91c9397",
          "md5": "a125415a4511889d46fd3fb776c01220"
        }
      ]
    }
  ]
}
