{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.callhandler",
    "module": "callhandler",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callhandler-1.0.15.jar",
          "url": "callhandler-1.0.15.jar",
          "size": 1407,
          "sha512": "acb114255e4604852edd7f9b27e38df9399ac341fd4a2c76a5558a57ee3a3a4c8b7a8afd84cd4da89038930c46fe31639cd07c48c13496c52cfc2afc0e0fefef",
          "sha256": "e944a34e751000849e0883af1b919aaad416ba55116df02b395ca1b9d7975ee7",
          "sha1": "cdc59aca59e1d1ff62692dd95275142d3303c3b6",
          "md5": "eb6ec9a4959a4f7abaa15dcd5f83e8fe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.15"
          }
        }
      ],
      "files": [
        {
          "name": "callhandler-1.0.15.jar",
          "url": "callhandler-1.0.15.jar",
          "size": 1407,
          "sha512": "acb114255e4604852edd7f9b27e38df9399ac341fd4a2c76a5558a57ee3a3a4c8b7a8afd84cd4da89038930c46fe31639cd07c48c13496c52cfc2afc0e0fefef",
          "sha256": "e944a34e751000849e0883af1b919aaad416ba55116df02b395ca1b9d7975ee7",
          "sha1": "cdc59aca59e1d1ff62692dd95275142d3303c3b6",
          "md5": "eb6ec9a4959a4f7abaa15dcd5f83e8fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callhandler-1.0.15-sources.jar",
          "url": "callhandler-1.0.15-sources.jar",
          "size": 1265,
          "sha512": "a99a3ad0c1416c0995a2dc12dd6a9cd209b102e0f8c5acb270787acb9ece8e49a141d079672e7957f6fd97f29ece9c5c286eea0e429bf6f7f2b188e9bc2b0a20",
          "sha256": "5f288f05bb044c8bff64b599a8a344be9bf311e6db80c4e71032c658e4bae753",
          "sha1": "e3e5e8465c3334fe9bdd413524ff95db254eee56",
          "md5": "7a743cb79c8a2ef4b35afc94e85f1451"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callhandler-1.0.15-javadoc.jar",
          "url": "callhandler-1.0.15-javadoc.jar",
          "size": 72978,
          "sha512": "b72266a2f71dddb87072b8211eb39a5fe5671bb99e605bb7e6f6796fd0fe7ab5bfb583e904e91327559e55cff222f7c7d06e5db66aca0bf88e7103b91d9ab34e",
          "sha256": "33f3db3fe90ad2f881a64091f6db215f7e07051e6673a4b1b5b40c119ceb2cfd",
          "sha1": "b7406367f5092312a6ef0b26e1f7c3f6fd01f2e8",
          "md5": "ae3dce9f0c61624829d6b4028e8622dd"
        }
      ]
    }
  ]
}
