{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "policy-impl",
    "version": "1.3.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "policy-impl-1.3.4-SNAPSHOT.jar",
          "url": "policy-impl-1.3.4-SNAPSHOT.jar",
          "size": 55253,
          "sha512": "7138c41a485b934607355f43e7d4afd3e78f6bb1a73713eaefc4bdafcec426bb4a3361511599fd248a3a1e3598b4cb10f52a001354873e19d54a5deffd69a797",
          "sha256": "1e35bbb33c1d961b3d9cf48b7d279d0f73388dbefd91e7551fa582009a2ff318",
          "sha1": "196ae5d48c44057da2d893407f5b72359b5ae7a8",
          "md5": "84beaabb8ea3d5e52a165130943ac6da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "policy-impl-1.3.4-SNAPSHOT.jar",
          "url": "policy-impl-1.3.4-SNAPSHOT.jar",
          "size": 55253,
          "sha512": "7138c41a485b934607355f43e7d4afd3e78f6bb1a73713eaefc4bdafcec426bb4a3361511599fd248a3a1e3598b4cb10f52a001354873e19d54a5deffd69a797",
          "sha256": "1e35bbb33c1d961b3d9cf48b7d279d0f73388dbefd91e7551fa582009a2ff318",
          "sha1": "196ae5d48c44057da2d893407f5b72359b5ae7a8",
          "md5": "84beaabb8ea3d5e52a165130943ac6da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "policy-impl-1.3.4-SNAPSHOT-sources.jar",
          "url": "policy-impl-1.3.4-SNAPSHOT-sources.jar",
          "size": 24722,
          "sha512": "b1a3b7190499369ceef2ea9e3424c2ccfd7ab0f2abccb643eb54ce1aef7eae81146d6b2adb50bfe33ae730d610bb8f3440f7c80f354c64a31dc53a6c92cb613f",
          "sha256": "6eee1452c08dc6402a5f6fa3ebfda12eae20388ec27363883a9a3877d58ac5e4",
          "sha1": "0cb416f5d8a903bf140d3d153afa2b56ced094fe",
          "md5": "436f4eb4223886c6a564d7a23bab9102"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "policy-impl-1.3.4-SNAPSHOT-javadoc.jar",
          "url": "policy-impl-1.3.4-SNAPSHOT-javadoc.jar",
          "size": 195052,
          "sha512": "26db9c4df5556b5fd397f25acabe9d78bbda6753d3743ee5a9e1c35a57888aa1949a08df9d2ca2615958f6c97994dfd59247748e9ac11218ad5bbfa31da61a2c",
          "sha256": "b31793131e457c303ffe400bbdabb9b8be4ec85c7afe08a24f07569ecf1382a3",
          "sha1": "69a25b9dc594d762427b8a89b29a61d73f2211e6",
          "md5": "2fb90f9e750737f1ddd3db2c2f29d903"
        }
      ]
    }
  ]
}
