{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore",
    "module": "policy-impl",
    "version": "1.3.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "policy-impl-1.3.4-SNAPSHOT.jar",
          "url": "policy-impl-1.3.4-SNAPSHOT.jar",
          "size": 55403,
          "sha512": "9a38de6ca538c71a6348f7c63dcedef7781140457195a66ff1e1b7ba61ba0529a4c732c8ecdaf6df1b32a2a740d298b721509bf930dd34bfa9f820b5bda05770",
          "sha256": "4b8905578207341194c0a6131ada1486ab51e12a4fe1f7dd2c1c43fa3b3ae186",
          "sha1": "c2d7470b3a6ce86afdc55e75db967c11ec636207",
          "md5": "09bb19ee8c444413ca008b8cdeb4e7d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.callhandler",
          "module": "callhandler",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.datagateways",
          "module": "datagateways",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "admin",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "callee",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.33"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "files": [
        {
          "name": "policy-impl-1.3.4-SNAPSHOT.jar",
          "url": "policy-impl-1.3.4-SNAPSHOT.jar",
          "size": 55403,
          "sha512": "9a38de6ca538c71a6348f7c63dcedef7781140457195a66ff1e1b7ba61ba0529a4c732c8ecdaf6df1b32a2a740d298b721509bf930dd34bfa9f820b5bda05770",
          "sha256": "4b8905578207341194c0a6131ada1486ab51e12a4fe1f7dd2c1c43fa3b3ae186",
          "sha1": "c2d7470b3a6ce86afdc55e75db967c11ec636207",
          "md5": "09bb19ee8c444413ca008b8cdeb4e7d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "policy-impl-1.3.4-SNAPSHOT-sources.jar",
          "url": "policy-impl-1.3.4-SNAPSHOT-sources.jar",
          "size": 24783,
          "sha512": "3cdfb1c54098013f05c3dca67a981215d650edbb7ae5fc6fd02d8900db791e61a84097b69536392d4ee44150673081a84a223eaecfca6dd55c84d6ab85f415af",
          "sha256": "00b50b6fd9fbe1649360e323605abca920b70767503c1689453ec2c8c60abad6",
          "sha1": "bda22e58dc14495ff2742b4d20d4b53e9eb3aebc",
          "md5": "35e3a856b46c58d8465fb3ec510e9905"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "policy-impl-1.3.4-SNAPSHOT-javadoc.jar",
          "url": "policy-impl-1.3.4-SNAPSHOT-javadoc.jar",
          "size": 195052,
          "sha512": "61e30c1f8e16f9ba6ec810ce54ff65232fa8e5ebcdb74e076f89ba987a20256baf5d58a35a58750869d005dfc251338fa66b3e5ef25b7a0d40be97670a9d0c02",
          "sha256": "fc8da36e4ddb6d7a4e6db8ab4db2f2f0ef5e9139975b4d75182352b776286560",
          "sha1": "e65d1292653ad3c5c1e7e3281093b660298c9e27",
          "md5": "b535ca7462791a4dd8d91694259a4a6e"
        }
      ]
    }
  ]
}
