{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.controllers",
    "module": "caller",
    "version": "1.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "caller-1.0.27.jar",
          "url": "caller-1.0.27.jar",
          "size": 261,
          "sha512": "3718b46f515d6c7d3275a6f08e178e64dd26126eea38dac90e4e40cfb9cd8bd4478b91e2b885db611c8ac6ee4eeabe692f7c7bc5ef136e1d9e539f205b06ddef",
          "sha256": "30cda2fa13753d1237e0c1445601b18cb796d63d1740df046e89665752880d6e",
          "sha1": "6cb78de394a02c4b8dc59adb2acb38202f2fd25f",
          "md5": "a189c933dbef461c5fa82729647cbb22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.27"
          }
        },
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "caller",
          "version": {
            "requires": "1.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "caller-1.0.27.jar",
          "url": "caller-1.0.27.jar",
          "size": 261,
          "sha512": "3718b46f515d6c7d3275a6f08e178e64dd26126eea38dac90e4e40cfb9cd8bd4478b91e2b885db611c8ac6ee4eeabe692f7c7bc5ef136e1d9e539f205b06ddef",
          "sha256": "30cda2fa13753d1237e0c1445601b18cb796d63d1740df046e89665752880d6e",
          "sha1": "6cb78de394a02c4b8dc59adb2acb38202f2fd25f",
          "md5": "a189c933dbef461c5fa82729647cbb22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caller-1.0.27-sources.jar",
          "url": "caller-1.0.27-sources.jar",
          "size": 261,
          "sha512": "3718b46f515d6c7d3275a6f08e178e64dd26126eea38dac90e4e40cfb9cd8bd4478b91e2b885db611c8ac6ee4eeabe692f7c7bc5ef136e1d9e539f205b06ddef",
          "sha256": "30cda2fa13753d1237e0c1445601b18cb796d63d1740df046e89665752880d6e",
          "sha1": "6cb78de394a02c4b8dc59adb2acb38202f2fd25f",
          "md5": "a189c933dbef461c5fa82729647cbb22"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caller-1.0.27-javadoc.jar",
          "url": "caller-1.0.27-javadoc.jar",
          "size": 261,
          "sha512": "3718b46f515d6c7d3275a6f08e178e64dd26126eea38dac90e4e40cfb9cd8bd4478b91e2b885db611c8ac6ee4eeabe692f7c7bc5ef136e1d9e539f205b06ddef",
          "sha256": "30cda2fa13753d1237e0c1445601b18cb796d63d1740df046e89665752880d6e",
          "sha1": "6cb78de394a02c4b8dc59adb2acb38202f2fd25f",
          "md5": "a189c933dbef461c5fa82729647cbb22"
        }
      ]
    }
  ]
}
