{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "callee",
    "version": "1.0.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callee-1.0.36.jar",
          "url": "callee-1.0.36.jar",
          "size": 12735,
          "sha512": "7bb68ec5bf94a487274c760591d341e596762f792703c2cc8a090f89ae7e2de0da038a6d09be4023ae8b6816eddc417a5f08283fcd4ce6c0d1ffa50d9d2dd22a",
          "sha256": "5ae2223bb40b62f8761d74a00184a4a7b315e03994916b2e01029b3f247bdf06",
          "sha1": "5a13c89ef85edb803a765b53db7c06dd25a44c18",
          "md5": "4629aceddbfa7830c4e0af269c2a79b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.36"
          }
        }
      ],
      "files": [
        {
          "name": "callee-1.0.36.jar",
          "url": "callee-1.0.36.jar",
          "size": 12735,
          "sha512": "7bb68ec5bf94a487274c760591d341e596762f792703c2cc8a090f89ae7e2de0da038a6d09be4023ae8b6816eddc417a5f08283fcd4ce6c0d1ffa50d9d2dd22a",
          "sha256": "5ae2223bb40b62f8761d74a00184a4a7b315e03994916b2e01029b3f247bdf06",
          "sha1": "5a13c89ef85edb803a765b53db7c06dd25a44c18",
          "md5": "4629aceddbfa7830c4e0af269c2a79b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.36-sources.jar",
          "url": "callee-1.0.36-sources.jar",
          "size": 7827,
          "sha512": "8880d3695b32cdf084d1800cb1a9e945c81264b2f6c05770f740daab6a35e21030b5a81439640230299a9f881226ce0615e92b4d6762c667317016d7fbaa9e95",
          "sha256": "75041244ee857a9dd29e38f239f504595543c9830323e4e2e2bf85daf5b5668c",
          "sha1": "1e761f69917ce04a2f394928cea9707001a33d76",
          "md5": "c9df1eeacc4a9e396e007e583f9b3e99"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callee-1.0.36-javadoc.jar",
          "url": "callee-1.0.36-javadoc.jar",
          "size": 84836,
          "sha512": "f58201c78c61f7187d4f2fc01d5bde463da9898c36fb1b519c63ea1642d8044bb1060bccaecdc09c963aecbc353f1f7aebcd366b8cb98117a641816dc3cbbcd5",
          "sha256": "337ff84135f9a641f90d7dcd754c2c7342f5301d6fd821e21cb8cb13dd2743d1",
          "sha1": "57e54845067257c77fac133224539daba9f4402e",
          "md5": "6e1bc3289bcd6c1e47238d4494c9ad87"
        }
      ]
    }
  ]
}
