{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.views",
    "module": "admin",
    "version": "1.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "admin-1.0.22.jar",
          "url": "admin-1.0.22.jar",
          "size": 261,
          "sha512": "32227b4166ce7eb857aa9b338ce3726bfa5fa00194d7403f84aa040fa6bc407ca00eaccd04cd29d5c6055676d87bb9fd0164c15dd5d974773d57b488c78add24",
          "sha256": "d2ce2889bf4c4caddf4c439612836b5aa2c11c36684bbb6bcd3cccf94455f433",
          "sha1": "7043a351ed1fd7d6a8004b7a0fcdad819237508e",
          "md5": "47fbc52fb5786af13537517b8f416209"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.22.jar",
          "url": "admin-1.0.22.jar",
          "size": 261,
          "sha512": "32227b4166ce7eb857aa9b338ce3726bfa5fa00194d7403f84aa040fa6bc407ca00eaccd04cd29d5c6055676d87bb9fd0164c15dd5d974773d57b488c78add24",
          "sha256": "d2ce2889bf4c4caddf4c439612836b5aa2c11c36684bbb6bcd3cccf94455f433",
          "sha1": "7043a351ed1fd7d6a8004b7a0fcdad819237508e",
          "md5": "47fbc52fb5786af13537517b8f416209"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.22-sources.jar",
          "url": "admin-1.0.22-sources.jar",
          "size": 999,
          "sha512": "fdc73de13898c81d37d34a0e072adb22021c17f95175807c26ac484f25ac6edb21caaccabbd9bbdc4c8fc46549bd2aa15d67212ea88a2389ad6f5e96773e49f7",
          "sha256": "11d06f6fadce8b7ce9517bca50ba36f9aa8bd585c9bae51c4c56993280b2b041",
          "sha1": "def2ef68a44be3d709a2b3c5c3828241398343c6",
          "md5": "aa5e707c8e9bf2bb95753fbdfc2a387f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "admin-1.0.22-javadoc.jar",
          "url": "admin-1.0.22-javadoc.jar",
          "size": 261,
          "sha512": "32227b4166ce7eb857aa9b338ce3726bfa5fa00194d7403f84aa040fa6bc407ca00eaccd04cd29d5c6055676d87bb9fd0164c15dd5d974773d57b488c78add24",
          "sha256": "d2ce2889bf4c4caddf4c439612836b5aa2c11c36684bbb6bcd3cccf94455f433",
          "sha1": "7043a351ed1fd7d6a8004b7a0fcdad819237508e",
          "md5": "47fbc52fb5786af13537517b8f416209"
        }
      ]
    }
  ]
}
