{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.callhandler",
    "module": "callhandler",
    "version": "1.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "callhandler-1.0.27.jar",
          "url": "callhandler-1.0.27.jar",
          "size": 1401,
          "sha512": "2ba3f4cf8b0a51c83ccb6090c305e1532019a612ab0d905cc66c9dbe97fae181d5b8a574cd3794558da5f57c14ca7b5e35f572c1dcd6b0b815ce1d74fe42bb9e",
          "sha256": "253f549e93e9913197f94748b4731d77b4d82d62b7a77efb55d525c30035ec3a",
          "sha1": "6fcf84e5b45dbf990fdc30ae760dad2f02b63513",
          "md5": "547c1a5a38be86feafaa9e96c8da4b2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.singlerr.semaphore.interactors",
          "module": "accessor",
          "version": {
            "requires": "1.0.27"
          }
        }
      ],
      "files": [
        {
          "name": "callhandler-1.0.27.jar",
          "url": "callhandler-1.0.27.jar",
          "size": 1401,
          "sha512": "2ba3f4cf8b0a51c83ccb6090c305e1532019a612ab0d905cc66c9dbe97fae181d5b8a574cd3794558da5f57c14ca7b5e35f572c1dcd6b0b815ce1d74fe42bb9e",
          "sha256": "253f549e93e9913197f94748b4731d77b4d82d62b7a77efb55d525c30035ec3a",
          "sha1": "6fcf84e5b45dbf990fdc30ae760dad2f02b63513",
          "md5": "547c1a5a38be86feafaa9e96c8da4b2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callhandler-1.0.27-sources.jar",
          "url": "callhandler-1.0.27-sources.jar",
          "size": 1265,
          "sha512": "6da9aaec567fda985e759692bd50d83ce5bd5710fe55b1992c4c68d132119496ec54f2c7cbdcbc099fc6584b0dc469da33c5a03ecc6847d3c040847997722664",
          "sha256": "4dea90313043fe1800c97bd235e9b106e0089939b698182f30a696666c6fc7e3",
          "sha1": "853f6d61989739cf672ca8a9e1f2573dfc8e5d5e",
          "md5": "fc8901d6bd94401fc82d46f453546994"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "callhandler-1.0.27-javadoc.jar",
          "url": "callhandler-1.0.27-javadoc.jar",
          "size": 19263,
          "sha512": "119547b15c020a343538fbf49f9d995435507c2dd6a9158bfc40d6c4b9c237b1578092f75a743b9d2d305f1ea846f7233afbe35ebd816794a9ee1004698b5601",
          "sha256": "0a7c45d00f55d6564ee54eeb0bee2f726e029b4528f8c113793a3e6d185a962e",
          "sha1": "38f8ec1c2ffb2d05e2de8d8760bdc9322177e64d",
          "md5": "ee21467fec620991497c4f62a11a48dd"
        }
      ]
    }
  ]
}
