{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.datagateways",
    "module": "datagateways",
    "version": "1.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "datagateways-1.0.16.jar",
          "url": "datagateways-1.0.16.jar",
          "size": 261,
          "sha512": "216e06c94f3b1364efc42d80ea988c6d56f22165b4b1e2027265cbd9a7318f10d631870a701ae0d4b9cb98b196c236f42396c1564a97694d04ef79191d7dedcf",
          "sha256": "5acb3d13412a6d1ca2b1bfded63dc6ffc033fc3e9cd3e9f734c9f401475b5fd8",
          "sha1": "d380a95e459ebcdbe45d304bd6a612e05df6d45c",
          "md5": "ba09a40ecaef43b2bf6b2ce7beddd21d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.16.jar",
          "url": "datagateways-1.0.16.jar",
          "size": 261,
          "sha512": "216e06c94f3b1364efc42d80ea988c6d56f22165b4b1e2027265cbd9a7318f10d631870a701ae0d4b9cb98b196c236f42396c1564a97694d04ef79191d7dedcf",
          "sha256": "5acb3d13412a6d1ca2b1bfded63dc6ffc033fc3e9cd3e9f734c9f401475b5fd8",
          "sha1": "d380a95e459ebcdbe45d304bd6a612e05df6d45c",
          "md5": "ba09a40ecaef43b2bf6b2ce7beddd21d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.16-sources.jar",
          "url": "datagateways-1.0.16-sources.jar",
          "size": 261,
          "sha512": "216e06c94f3b1364efc42d80ea988c6d56f22165b4b1e2027265cbd9a7318f10d631870a701ae0d4b9cb98b196c236f42396c1564a97694d04ef79191d7dedcf",
          "sha256": "5acb3d13412a6d1ca2b1bfded63dc6ffc033fc3e9cd3e9f734c9f401475b5fd8",
          "sha1": "d380a95e459ebcdbe45d304bd6a612e05df6d45c",
          "md5": "ba09a40ecaef43b2bf6b2ce7beddd21d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.16-javadoc.jar",
          "url": "datagateways-1.0.16-javadoc.jar",
          "size": 261,
          "sha512": "216e06c94f3b1364efc42d80ea988c6d56f22165b4b1e2027265cbd9a7318f10d631870a701ae0d4b9cb98b196c236f42396c1564a97694d04ef79191d7dedcf",
          "sha256": "5acb3d13412a6d1ca2b1bfded63dc6ffc033fc3e9cd3e9f734c9f401475b5fd8",
          "sha1": "d380a95e459ebcdbe45d304bd6a612e05df6d45c",
          "md5": "ba09a40ecaef43b2bf6b2ce7beddd21d"
        }
      ]
    }
  ]
}
