{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.datagateways",
    "module": "datagateways",
    "version": "1.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "datagateways-1.0.16.jar",
          "url": "datagateways-1.0.16.jar",
          "size": 261,
          "sha512": "8566e11c0a04f0d6a2b40939d8715093fcfd67115e0e6b3bfe3b34f7353d8ea31629bb50b54e713f74e2c29a8890f8d22b521dc467d077e69fcbc4a8c69db35d",
          "sha256": "d61270ded1178584187d1970b36d83b7452b65ff688e6d763810739ef668d7bc",
          "sha1": "ed94963bef215830a166d49f32ec46a37787dee2",
          "md5": "5516ee7b0c4184a4e720844ef4da028d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.16.jar",
          "url": "datagateways-1.0.16.jar",
          "size": 261,
          "sha512": "8566e11c0a04f0d6a2b40939d8715093fcfd67115e0e6b3bfe3b34f7353d8ea31629bb50b54e713f74e2c29a8890f8d22b521dc467d077e69fcbc4a8c69db35d",
          "sha256": "d61270ded1178584187d1970b36d83b7452b65ff688e6d763810739ef668d7bc",
          "sha1": "ed94963bef215830a166d49f32ec46a37787dee2",
          "md5": "5516ee7b0c4184a4e720844ef4da028d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.16-sources.jar",
          "url": "datagateways-1.0.16-sources.jar",
          "size": 261,
          "sha512": "4f8f32c07cbfd644854619fea227f6bcea2a7ec52711bd4109863bb659e47f5a5bd29c76629747fddde80262c1adce952fd5f02a11d8023372eecc6aea7ee59d",
          "sha256": "cda505c263c5a25f10efda77471c79f9181c59d58fb88023bed54d8378452a8a",
          "sha1": "a0399fd08d3910005e4038cf3c37bc97b3fe4c92",
          "md5": "561bd65d566bea09a6a7bee3199d931a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "datagateways-1.0.16-javadoc.jar",
          "url": "datagateways-1.0.16-javadoc.jar",
          "size": 261,
          "sha512": "4f8f32c07cbfd644854619fea227f6bcea2a7ec52711bd4109863bb659e47f5a5bd29c76629747fddde80262c1adce952fd5f02a11d8023372eecc6aea7ee59d",
          "sha256": "cda505c263c5a25f10efda77471c79f9181c59d58fb88023bed54d8378452a8a",
          "sha1": "a0399fd08d3910005e4038cf3c37bc97b3fe4c92",
          "md5": "561bd65d566bea09a6a7bee3199d931a"
        }
      ]
    }
  ]
}
