{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "accessor",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "accessor-1.0.17.jar",
          "url": "accessor-1.0.17.jar",
          "size": 4905,
          "sha512": "1c22446e47bfbd3361944f2664a0fce0cb40a0d4eda233d7e7e0d0357878bccb40c17acc2083eedc210a80e626b70d5a31e71dbd251291fefa77a1448972cba4",
          "sha256": "2ed0e0bd53298366361719d4044922a1c45b1404adc3fc6fb513d8b7154a2970",
          "sha1": "d99342b2b4b8572f92ae8f98dcb1f5ca903ad0e2",
          "md5": "c215a9207297b82699636e0528c52c58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessor-1.0.17.jar",
          "url": "accessor-1.0.17.jar",
          "size": 4905,
          "sha512": "1c22446e47bfbd3361944f2664a0fce0cb40a0d4eda233d7e7e0d0357878bccb40c17acc2083eedc210a80e626b70d5a31e71dbd251291fefa77a1448972cba4",
          "sha256": "2ed0e0bd53298366361719d4044922a1c45b1404adc3fc6fb513d8b7154a2970",
          "sha1": "d99342b2b4b8572f92ae8f98dcb1f5ca903ad0e2",
          "md5": "c215a9207297b82699636e0528c52c58"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessor-1.0.17-sources.jar",
          "url": "accessor-1.0.17-sources.jar",
          "size": 3686,
          "sha512": "7067e7faa29db92e2dbba0b91e977a3eabde190778d5673b303f908391e3df3ba4e47e1c26e5f3152fc6e7672e2cba6dbba58070ea76b30a8602278d929837af",
          "sha256": "2dde3e0689596963322bc49735afdaf91a1304103f16e5ab5e234b4cace4e681",
          "sha1": "2520cf86a18084567c6a473cb98c36496bcc3fde",
          "md5": "8335f43c9c53f1f40999e41ef0851756"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessor-1.0.17-javadoc.jar",
          "url": "accessor-1.0.17-javadoc.jar",
          "size": 37095,
          "sha512": "c2aad7bed02844735a62ca16b5ed4ef0e1ec71246ce29bc7338fba5ac87614629c8ce8be5d52245b9f653b144127b51c827046c00d44e283506670c2f9f1df00",
          "sha256": "6ffbd7186d1ad89fb0abd2da3adbd89ffd423f7f17bccd58836e78a5bd49a997",
          "sha1": "3ab79f9bb4fb59d3fbfaeb7a1d55711151e0e23d",
          "md5": "b74a4c720c5ad7e7e99b7bcd2f56a6e5"
        }
      ]
    }
  ]
}
