{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.singlerr.semaphore.interactors",
    "module": "accessor",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "accessor-1.0.17.jar",
          "url": "accessor-1.0.17.jar",
          "size": 4905,
          "sha512": "156f49f24a445bd732fa2fa1684b0d38af5200bacd871859ac969f48b4757bd6cc18d2f29d3cd816e6876b7822f269e30bd2dcf9fd3e1ef4c62662957262361d",
          "sha256": "c418821565e59505c704d1ac13f8e162d21406e48934f833bd34d3dcd388a044",
          "sha1": "e801ff8e33c856ef54c7ad4779db6cdf37dea734",
          "md5": "1e32fe15b1e611a255c30c0debc67094"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessor-1.0.17.jar",
          "url": "accessor-1.0.17.jar",
          "size": 4905,
          "sha512": "156f49f24a445bd732fa2fa1684b0d38af5200bacd871859ac969f48b4757bd6cc18d2f29d3cd816e6876b7822f269e30bd2dcf9fd3e1ef4c62662957262361d",
          "sha256": "c418821565e59505c704d1ac13f8e162d21406e48934f833bd34d3dcd388a044",
          "sha1": "e801ff8e33c856ef54c7ad4779db6cdf37dea734",
          "md5": "1e32fe15b1e611a255c30c0debc67094"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessor-1.0.17-sources.jar",
          "url": "accessor-1.0.17-sources.jar",
          "size": 3686,
          "sha512": "98427d8beadbca115c5e566b08d9a82151fd2861ad99009449964a525907df08dea03cc88efaed74781b7fbd50eba8d6d48a918e771c7abd7d5d470ca434aa03",
          "sha256": "373321ba8f78bdc4893f978dc31df3f159d20a6002e87ae55ac200c3f98485a3",
          "sha1": "4950e2c0cd10b9a8c592f4c4ec0a8851fc63b54b",
          "md5": "62caa01908582b07a89713164b792821"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessor-1.0.17-javadoc.jar",
          "url": "accessor-1.0.17-javadoc.jar",
          "size": 37095,
          "sha512": "3011ad898683f15b82e1c4f81feb80b5091037b4d89d3ffd0e63f42147fbf4c0b5d76c9972e930e9f7f8d793b42a19d49a4f71cf1bb662e83918ffb0b1490cde",
          "sha256": "5212c301e12127e8acf76d24cfbad9ad502f04d55fc157b1c38a6b0eb0a4e3b3",
          "sha1": "c0c3ff5180189baef83d78385435f086b7f74622",
          "md5": "e88ad91a2eaee6c49a9f40cbab9dda62"
        }
      ]
    }
  ]
}
